### ISSUE TITLE
希望加一个功能，强类型检查

### ISSUE THREAD

**Issue by 49694445** [EmmyLua/IntelliJ-EmmyLua#1]
类似java那样强类型检测的编辑器。
可以设立一个开关，如果一个文档 有这行注释  use strict，就检测
如果这个 类被@注明了，，又：一个不存在的函数，或属性。
 就警告提示这个函数或属性不存在，

**Comment by tangzx** [comment]
放在后续计划中

**Comment by tangzx** [comment]
see #53
