### ISSUE TITLE
Very slow debugging

### ISSUE THREAD

**Issue by slanska** [EmmyLua/IntelliJ-EmmyLua#100]
Stepping over is painfully slow - every step takes ~1 minute or so, so it might look like debugging is frozen. I am running EmmyLua on MacBook,  CLion 2017.3. Also, running in debug mode is slow in general - it takes couple of minutes to reach first breakpoint.

**Comment by tangzx** [comment]
Remote debugger use `mobdebug.lua` as backend, the debugger core. You can debug with another opensource lua ide `ZeroBraneStudio` which also use `modebug.lua` as backend, and please feed back : It's Emmy's problem or mobdebug's problem?

**Comment by adriweb** [comment]
Mobdebug works fine here on Intellij/EmmyLua, from a Luajit in a remote device, and the IDE is on Linux (but I can try on macOS later if needed)

**Comment by slanska** [comment]
Sure, I will try ZeroBraneStudio and let you know in this thread. Thanks.

**Comment by slanska** [comment]
FYI: I tried debugging my project in ZeroBrane and it is working as fast as I would expect.

**Comment by tangzx** [comment]
Thanks a lot !  I'll try it

**Comment by slanska** [comment]
In case if you are interested in checking slow debugging - here is a small demo which freezes ZeroBrane and makes EmmyLua very sluggish. The only dependency is cjson (lua-cjson)
[slow_debug_demo.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/1666366/slow_debug_demo.zip)

**Comment by slanska** [comment]
FYI: PKulchenko, author of ZeroBrane, suggested the quick fix for this issue:

> I think it's related to the photo elements more than anything else, as the stack window will try to fix UTF8 encoding before showing the content and given that the photos are long enough (50k+), it takes a long time to scan and fix them. I added trimming to maxlen already specified for other fields, which should address this issue.

https://github.com/pkulchenko/ZeroBraneStudio/issues/863

It really  helped and debugging is find now with ZeroBrane.
Not sure if this fix can be applied to EmmyLua, though, but if you could - that would be just great.

**Comment by tangzx** [comment]
[EmmyLua-1.2.3b3.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/1673053/EmmyLua-1.2.3b3.zip)
HI, @slanska please try this build.

Thanks for your suggestion, but actually the main reason is that my bad performance code of mobdebug response data handler.  And also I striped the larger string data.

![image](https://user-images.githubusercontent.com/3354360/35505293-aa905f42-0520-11e8-8a49-c4f05cbaa933.png)

**Comment by slanska** [comment]
@tangzx Thanks a lot for the update and custom build. I tried it and with complete JSON data I do not see differences so far - it is still very slow, so it looks like almost frozen. 
I also wanted to mention that fix applied by @pkulchenko in his ZeroBrane did not help too much, either.
After I realizes that I am debugging on smaller data and tried on larger one, ZeroBrane hangup again. 
And FYI: indexing after plugin update again took long time, with high CPU usage.
Thanks again for your help and efforts. Let me know if you need additional info or want me to try something  else.

**Comment by tangzx** [comment]
sorry, the wrong build. try this
[EmmyLua-1.2.3b4.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/1688873/EmmyLua-1.2.3b4.zip)
, it should be worked. and please notice that you have to use the lastest mobdebug.lua version ([`0.70`](https://github.com/pkulchenko/MobDebug/archive/0.70.zip))

**Comment by slanska** [comment]
@tangzx  I tried your last build and made sure that I am using mobdebug 0.70 - problem still stays. If it is OK for you, I can give you exact step to try on my real project, if you think this could be helpful.

**Comment by tangzx** [comment]
Yes, it works ok for me, just see the gif file below

![rec](https://user-images.githubusercontent.com/3354360/35773502-a6a19dec-098f-11e8-88d1-f3c472cbe9a1.gif)
