### ISSUE TITLE
调试希望可以支持条件断点

### ISSUE THREAD

**Issue by 792453582** [EmmyLua/IntelliJ-EmmyLua#101]
在调试一个bug时，这个bug出现在循环之中的某个特定的值，就非常想打一个条件断点

**Comment by tangzx** [comment]
![image](https://user-images.githubusercontent.com/3354360/35370624-dbd5ee50-01c9-11e8-9c5d-24aa7858b0ba.png)

已有的功能

**Comment by 792453582** [comment]
提示表达式错误，我还以为不支持，原来是可以的啊

**Comment by tangzx** [comment]
这个错误不影响，后面会改掉。
