### ISSUE TITLE
Code completion triggers after "." in .py comments inside dicts

### ISSUE THREAD

**Issue by LilyMaster** [EmmyLua/IntelliJ-EmmyLua#105]
I am using PyCharm 2017.3, EmmyLua 1.2.2 and the post-fix completion dialogue activates after I type `.` in comment in .py file-type. 

As I can see, it triggers only for comments beside values inside dicts. See in picture, other comments do not trigger this.

![image](https://user-images.githubusercontent.com/9978292/35671765-16f9bafe-0745-11e8-9161-1625886b9033.png)

P.S. I have post-fix completion disabled.

**Comment by tangzx** [comment]
I had `PyCharm 2017.3` installed with no `EmmyLua` plugin. But it still shows `for` postfix completion template. So maybe it's not Emmy's problem. :-)
![image](https://user-images.githubusercontent.com/3354360/35731597-30c9f176-0851-11e8-9fc8-dfc098e4cbaf.png)

**Comment by LilyMaster** [comment]
True. Same here. I might have jumped the gun when testing, did not finish waiting for indexing at the moment... EmmyLua is not responsible, looks like.
