### ISSUE TITLE
regardless of the "soft wraps" option

### ISSUE THREAD

**Issue by myshzzx** [EmmyLua/IntelliJ-EmmyLua#106]
没有设置软换行, 编辑器代码依然软换行了
![image](https://user-images.githubusercontent.com/2025090/35779720-bc1a9af2-0a0c-11e8-816b-fd0ed9a3a385.png)

**Comment by tangzx** [comment]
软换行是IDEA的功能，Emmy并没有做处理，看看是不是有别的原因。
