### ISSUE TITLE
Run 输出中文乱码

### ISSUE THREAD

**Issue by ngstyle** [EmmyLua/IntelliJ-EmmyLua#107]
![image](https://user-images.githubusercontent.com/7988330/35962169-6d8fe464-0ceb-11e8-8dd7-7ae284b07d00.png)
RT

**Comment by tangzx** [comment]
群里最新版，运行设置项新加了 output charset，可以试试

**Comment by ngstyle** [comment]
@tangzx 感谢，可以啦
