### ISSUE TITLE
请问可以支持consulo吗

### ISSUE THREAD

**Issue by c6u2** [EmmyLua/IntelliJ-EmmyLua#111]
https://github.com/consulo/consulo/wiki/Downloads 这个IDE也是用的JETBRAINS的内核开发的，但是相对于RIDER和IDEA效率要高一些，感觉是专门为了UNITY开发用的，希望可以支持这个IDE

**Comment by tangzx** [comment]
它基于IDEA的版本太旧了，支持不了
