### ISSUE TITLE
Poor support of multiple return values

### ISSUE THREAD

**Issue by MinusKube** [EmmyLua/IntelliJ-EmmyLua#115]
I'm trying to make a method return multiple values, and I want to use the type safety inspections and the emmylua doc.

But, when I call a method which returns 2 values from a method which should return 2 values, the inspection tells me the number of return values is not correct, but it is.

Here is a screen of what I'm talking of: 
![image](https://user-images.githubusercontent.com/13206601/37035890-4294d388-214e-11e8-9478-d58bb747eda1.png)

Example of reproduction with simple code:
```java
---@class Test
local test = {}

---@return number, number
function test.methodTwo()
  return test.methodOne()
end

---@return number, number
function test.methodOne()
  return 5, 5
end```

**Comment by tangzx** [comment]
Issue has been resolved, try the eap version [1.2.3-eap-28](https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/artifacts)
