### ISSUE TITLE
导入DLL注释，没有命名空间的类不会导出

### ISSUE THREAD

**Issue by xp168** [EmmyLua/IntelliJ-EmmyLua#123]
导入DLL注释，没有命名空间的类不会导出
![image](https://user-images.githubusercontent.com/7510080/48473225-046c9080-e833-11e8-80c9-d132d754fa33.png)

没有namespace的类 在这里不会生成注释类

**Comment by ice1000** [comment]
请提供更详细的描述，否则关issue
