### ISSUE TITLE
关于require auto-completion的小建议

### ISSUE THREAD

**Issue by CodeMasterYi** [EmmyLua/IntelliJ-EmmyLua#124]
![3k4ce_w o 6 ia mejq2wj0](https://user-images.githubusercontent.com/10430162/38182284-02dd5b48-366b-11e8-832e-40236dc53f15.jpg)
首先呢，我设置了以上lua源文件的后缀名了，当我require一个名叫config.lua.txt的脚本时，auto-completion只是简单得把后缀名.txt去掉，提示config.lua，而不是帮我去掉我实际使用得后缀名

可能你觉得把.lua直接去掉就好了，但是这样子，所有的txt文件都识别成lua文件了，强迫症不能忍了
当然，本来.lua.txt这种后缀已经够难受，怎奈Unity官方还不支持.lua后缀，不爽~

**Comment by tangzx** [comment]
这是使用者自身的问题，暂不为特例去做支持是现阶段的原则。你可以在xlua里自定义loader去支持正常的.lua后缀

**Comment by CodeMasterYi** [comment]
阿唐，你把重点弄错了，我说的是require代码提示，不是怎么让lua方案支持某种后缀的lua文件

**Comment by tangzx** [comment]
没搞错啊，你说的require的代码提示问题正是因为后缀不常规导致的

**Comment by tangzx** [comment]
这处问题先放着，有空我看看
