### ISSUE TITLE
Wrong local functions syntax highlightig

### ISSUE THREAD

**Issue by Zaklinatel** [EmmyLua/IntelliJ-EmmyLua#126]
![image](https://user-images.githubusercontent.com/4108046/38416805-877686a8-39c8-11e8-9703-80b07328b68c.png)

In syntax highlighting settings is no option like "local function" and local functions highlights as local variables.

PhpStorm 2017.3

**Comment by tangzx** [comment]
Can you please show me your whole example code? And what's the version of EmmyLua?

**Comment by Zaklinatel** [comment]
Version 1.2.3

there is code + screenshot
```
local localVar = 'something' -- local var, ok

function globalFunction() -- global function, ok
  -- ...
end

local function localFunction() -- local variable highlighting
  -- ...
end

function test()
  globalFunction(); -- ok

  -- call local fn
  localFunction() -- up value highlighting
  localFunction() -- local variable..?
  localFunction() -- up value..?
end
```

![image](https://user-images.githubusercontent.com/4108046/38470777-3c4eb94c-3b9a-11e8-96b7-d86523202591.png)

**Comment by tangzx** [comment]
![image](https://user-images.githubusercontent.com/3354360/38477856-c55bedd4-3be7-11e8-83bc-ce58c9d96f35.png)

It's ok in my case. I can't reappear the issue ... (PhpStorm 2017.3 & IDEA 2017.3)

**Comment by Zaklinatel** [comment]
I noticed a certain pattern... In last two calls function highlights as local variable.

![image](https://user-images.githubusercontent.com/4108046/38491411-5cc6f9d0-3c1e-11e8-8502-abc2f744c284.png)
![image](https://user-images.githubusercontent.com/4108046/38491143-a33c218e-3c1d-11e8-8d0b-319bd28b24d1.png)
![image](https://user-images.githubusercontent.com/4108046/38491159-aa5feb26-3c1d-11e8-9175-b2f88e2d324c.png)

**Comment by tangzx** [comment]
I see, you changed the `up value` color style, that may cause foreground-color fighting between `up value` and `local function/variable`.

**Comment by Zaklinatel** [comment]
Yep. I dont want up value looks like local function and local variable, it craetes a mess in the code. I tried to separate them visually.
Can you please add individual style setting for local functions in next release?
And would be greate to set hard priority in styles.

Thank you

**Comment by tangzx** [comment]
Try it [1.2.4-eap-8](https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/1.2.4-eap-8/artifacts)

**Comment by Zaklinatel** [comment]
Much better, thank you!
