### ISSUE TITLE
remote debug调试时client主动断开但是idea没有断开

### ISSUE THREAD

**Issue by crazybie** [EmmyLua/IntelliJ-EmmyLua#128]
客户端调用mobdebug.done()主动断开调试器时，emmylua没有对应断开。（老版本v1.2.2好像是对的）
正常情况下console下会显示Disconnected。

导致的问题是，client无法重复连接debugger，第二次连接必定卡死。

问题版本：1.2.3

**Comment by tangzx** [comment]
测试了一下没毛病，你用的`mobdebug`是什么版本？
