### ISSUE TITLE
不支持 Rider 2018.1

### ISSUE THREAD

**Issue by wpp1983** [EmmyLua/IntelliJ-EmmyLua#137]
不支持 Rider 2018.1 
报错信息：“Fail to load plugin descriptor from file EmmyLua.zip”

**Comment by tangzx** [comment]
试了没问题，用最新版 [EmmyLua-1.2.4](https://github.com/EmmyLua/IntelliJ-EmmyLua/releases/download/1.2.4/EmmyLua-1.2.4.zip) 或者在插件仓库在线安装
