### ISSUE TITLE
新版本的跳转无法使用

### ISSUE THREAD

**Issue by SakuraMaaya** [EmmyLua/IntelliJ-EmmyLua#140]
我现在仍然在使用旧的1.1.7版本
新版本找引用找不到。。。旧版可以，是设置问题吗
![e1](https://user-images.githubusercontent.com/35125751/39291161-a7cf2a08-4964-11e8-8a7f-52d360df7cc1.png)
![e2](https://user-images.githubusercontent.com/35125751/39291166-abe004b4-4964-11e8-8132-8b1a78cfad2b.png)

**Comment by tangzx** [comment]
请放上示例代码

**Comment by SakuraMaaya** [comment]
用zip本地安装更新后跳转正常了，是不是通过plugins里面的更新会出问题呢

**Comment by Duniwah** [comment]
我也遇到了，往后退了一个版本就正常了
