### ISSUE TITLE
在Idea中运行报错

### ISSUE THREAD

**Issue by Lovnx** [EmmyLua/IntelliJ-EmmyLua#142]
Error running 'hello.lua': Cannot run program "lua.exe" (in directory "C:\Users\Administrator\IdeaProjects\lua-test\src"): CreateProcess error=2, 系统找不到指定的文件。

**Comment by tangzx** [comment]
lua.exe 没有找到，自己安装/编译lua.exe
并设置path目录或者在运行配置里将 program 设置 lua.exe 的绝对路径

**Comment by Lovnx** [comment]
![tim 20180511110704](https://user-images.githubusercontent.com/26428832/39904652-8d0009ec-550b-11e8-9b7a-cfb5e5bd97b0.png)
解决了！谢谢

**Comment by Lovnx** [comment]
加个微信，兄弟

**Comment by tangzx** [comment]
进Q群 `29850775 `

**Comment by longshilin** [comment]
补充一下，可以对lua运行模板进行配置
![TIM截图20190709182541](https://user-images.githubusercontent.com/18352884/60881142-a1bf7d80-a277-11e9-98d1-e05503a05bb8.png)

**Comment by DustinQi** [comment]
非常感谢，遇到了同样问题，已解决
