### ISSUE TITLE
Class in separate files

### ISSUE THREAD

**Issue by cmingjian** [EmmyLua/IntelliJ-EmmyLua#148]
当我想在不同的文件中定义一个类，比如[这个](https://gist.github.com/cmingjian/eb298d5873b511ae9d7eb7e78899e30e)例子。怎么写标注可以让插件正常解析Player这个类呢？我参考文档在不同的文件写--- @class Player会提示"Duplicate class...."，这当然不是一个BUG。但是我想知道，有没有什么方法可以让类型分析在这种情况下正常工作？

谢谢~

**Comment by tangzx** [comment]
不能，可以加上命名空间的概念（其实还是类名的一部分）
`---@class ns1.Player`

`---@class ns2.Player`
