### ISSUE TITLE
repeat块中无法识别变量

### ISSUE THREAD

**Issue by yuz10** [EmmyLua/IntelliJ-EmmyLua#151]
![image](https://user-images.githubusercontent.com/14816818/40411705-c2794ad8-5ea3-11e8-8b2c-826faeefa532.png)

**Comment by tangzx** [comment]
已经解决， 用最新版
https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/1.2.5-eap-17/artifacts
