### ISSUE TITLE
debugger freeze: mac版本用mobdebug调试时单步,Evaluate求值易卡死

### ISSUE THREAD

**Issue by songtm** [EmmyLua/IntelliJ-EmmyLua#156]
按照文档构造好调试环境,点击调试, 能进断点,点击单步能成功, 但是多点击几次单步 经常会出现卡死(单步按钮变灰)导致调试无法进行下去;
进断点后,进行表达式求值(Evaluate),输入print("xx"),点击Evaluate,卡死(偶尔能成功)
![qq20180601-165239](https://user-images.githubusercontent.com/8175056/40831718-52a980b8-65bc-11e8-8964-3ce4a79686e3.png)

intellij 2018.1.4
osx:10.13.1
emmylua: 1.2.5-eap-17
mobdebug:"0.703"

**Comment by tangzx** [comment]
无法重现，怎么测试？

**Comment by tangzx** [comment]
@adriweb What's your emmylua version, `1.2.4` ?  We have new eap version `1.2.5-eap-17+` (with mobdebug.lua ver 0.70+), fixed some known issues. 

Version | CI status
--------|----------
IDEA 171|[![Build status](https://ci.appveyor.com/api/projects/status/m25uajpqa2fft8ah?svg=true)](https://ci.appveyor.com/project/EmmyLua/intellij-emmylua)
IDEA 172-181|[![Build status](https://ci.appveyor.com/api/projects/status/m25uajpqa2fft8ah?svg=true)](https://ci.appveyor.com/project/EmmyLua/intellij-emmylua)
IDEA 182|[![Build status](https://ci.appveyor.com/api/projects/status/xvahlg1ceiy16dxl?svg=true)](https://ci.appveyor.com/project/EmmyLua/intellij-emmylua-7n83m)

**Comment by adriweb** [comment]
Hi,

Versions as follow:
 * Intellij IDEA 2018.2 EAP (182)
 * EmmyLua (182) v1.2.5 EAP (12)
 * mobdebug v0.702

**Comment by adriweb** [comment]
Any update @tangzx ?

**Comment by tangzx** [comment]
@adriweb Not yet.  :worried:

**Comment by ice1000** [comment]
Isn't the debug functionality only available on Windows? Why Linux?

**Comment by adriweb** [comment]
Nah, it was working just fine on Linux and macOS some time ago.
It's using mobdebug, which is a multiplatform lua lib.

**Comment by songtm** [comment]
@tangzx I just made a pull request for this problem, it also fixed the none topmost stack frame lua table display problem 
![qq20180814-2047262](https://user-images.githubusercontent.com/8175056/44092880-446927ce-a004-11e8-9bc1-1c20088029a2.png)

**Comment by ice1000** [comment]
@songtm Good to see that! Please take a look at my comments plz
