### ISSUE TITLE
How to annotate function spread parameter

### ISSUE THREAD

**Issue by 1moere1** [EmmyLua/IntelliJ-EmmyLua#157]
How can I annotate something like
```
---@param ??? Type
function name(...)

end
```

**Comment by songtm** [comment]
maybe you could just leave it alone, it will give you the "any" tip;
![qq20180605-142753](https://user-images.githubusercontent.com/8175056/40958674-af33297a-68cc-11e8-9d4f-a000ce50e042.png)
