### ISSUE TITLE
智能提示失效

### ISSUE THREAD

**Issue by leafsnow** [EmmyLua/IntelliJ-EmmyLua#159]
环境：
1.intellij
2.Version: 1.2.5-eap-17

问题描述：
1.同文件的智能提示失效了
---@class GoodsGroupCircle:DisplayObj
GoodsGroupCircle = class("GoodsGroupCircle", DisplayObj)
![image](https://user-images.githubusercontent.com/6291246/41089591-cc3de4a2-6a74-11e8-98e2-a19ea4ce7add.png)
提示一个全局变量，就有问题了。！！！！！【但是使用module() 包裹该类一切提示都正常】

![image](https://user-images.githubusercontent.com/6291246/41089707-114691d4-6a75-11e8-8481-5cf32e1a9f70.png)
只输入self 会弹出智能提示 该类的方法以及其父类的方法，当时多输入一个: self:智能提示就消失了。

![image](https://user-images.githubusercontent.com/6291246/41089809-4e8203b2-6a75-11e8-96de-c0c908e8fa81.png)
调用方法 self:_createGoodsItem()  不能跳转

2.完整代码如下
---@class GoodsGroupCircle:DisplayObj
GoodsGroupCircle = class("GoodsGroupCircle", DisplayObj)

local defaultOptions = {
    nScale = 1,
    columnsNum = 0,
    cellSize = Vector2(88,88),
    spacing = Vector2(0,0),
    childAlignment = TextAnchor.UpperLeft,
}
defaultOptions.__index = defaultOptions;

function GoodsGroupCircle:ctor(gameObj, options)
    options = options or {};
    setmetatable(options, defaultOptions);
    self.options = options;
    self.copyOptions = clone(self.options);
    self.gameObj = gameObj;
    GoodsGroupCircle.super.ctor(self);
    self.curDataNum = 0;
end

function GoodsGroupCircle:init()
    self:_createGoodsItem()
    if self.gameObj ~= nil then
        self:setObj(self.gameObj);
    else
        print("GoodsGroupCircle 对应的GameObject为空"..debug.traceback());
        return;
    end
    self.goodsPoolList = {};
    self.activeGoodsList = {};
end

function GoodsGroupCircle:onGUI(data)
    self.activeGoodsList = {};
    self.data = data or {};
    for i=1,#self.data do
        local goodsImageItem = self:_createGoodsItem(i);
        goodsImageItem.renderIndex = i;
        goodsImageItem:setData(self.data[i]);
        goodsImageItem:setParent(self.myObj);
        local pos = self:_generatorPos(i);
        goodsImageItem:setLocalPosition(pos);
        goodsImageItem:setScale(Vector3.one);
        goodsImageItem:setActive(true);
    end
    if #self.goodsPoolList > #self.data then
        for i=#self.data+1,#self.goodsPoolList do
            self.goodsPoolList[i]:setActive(false);
        end
    end
end

function GoodsGroupCircle:_createGoodsItem(index)
    local goodsImageItem = self.goodsPoolList[index];
    if goodsImageItem == nil then
        if self.options.itemRender then--自己的render
            goodsImageItem = self.options.itemRender.new(self.copyOptions);
            if Util.isNil(goodsImageItem.myObj) then
                if not Util.isNil(self.options.itemRenderPrefab) then
                    goodsImageItem:setObjAndInstantiate(self.options.itemRenderPrefab);
                else
                    goodsImageItem:loadPrefab(self.options.itemRenderPrefabName);
                end
            end
        else--默认GoodsImage
            goodsImageItem = GoodsImage.new(self.copyOptions);
        end
        self.goodsPoolList[index] = goodsImageItem;
    else
        if not Util.isNil(goodsImageItem.myObj) then
            goodsImageItem.myObj:SetActive(true);
        end
    end
    table.insert(self.activeGoodsList, goodsImageItem);
    return goodsImageItem
end

function GoodsGroupCircle:_generatorPos(index)
    self:_createGoodsItem()
end

**Comment by tangzx** [comment]
无法重现，请提供更多的信息
