### ISSUE TITLE
WebStorm 2018.2 EAP support

### ISSUE THREAD

**Issue by dannybloe** [EmmyLua/IntelliJ-EmmyLua#160]
Howdee folks, 

Is it possible to make this plugin show up in WebStorm 2018.2 EAP? 

Cheers, 
Danny

**Comment by tangzx** [comment]
Already supported, but didn't upload to jetBrains plugins repository, You can download this eap version and install manually. https://ci.appveyor.com/project/EmmyLua/intellij-emmylua-7n83m

**Comment by dannybloe** [comment]
Next update of WebStorm 2018.2 EAP breaks the plug-in again. I feel lost coz I can't do without this great plugin! Love it! 

Build #WS-182.3341.1, built on June 19, 2018
WebStorm EAP User
Expiration date: July 19, 2018
JRE: 1.8.0_152-release-1226-b7 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

**Comment by tangzx** [comment]
What's the "ws breaks the plug-in" means ? Are there any errors shown ?

**Comment by dannybloe** [comment]
Wow.. that's weird. Today the plug-in just works. After installing and running 182.3341.1 WebStorm said the plug-in wasn't compatible and it turned it off. I just turned it on again and now it works.
Sorry for the commotion. Keep up the good work!
