### ISSUE TITLE
EmmyLua likely hangs CLion for a long time

### ISSUE THREAD

**Issue by vstakhov** [EmmyLua/IntelliJ-EmmyLua#161]
Hello, I've started to observe quite bad IDE hangs when trying to work with Lua code using EmmyLua. Hangs usually start when I type function name and put the first `(`. After that, IDE is completely unresponsive for quite a long time (couple of minutes). I also see quite bad hangs when trying to search symbols that are also presumably related to Lua.

I have captured couple of snapshots of `jstack` during hangs if that helps:

http://termbin.com/e4vz
http://termbin.com/i16s
http://termbin.com/s7vw

EmmyLua completion setup tab is also empty in my IDE, so I cannot even disable those completions. Is there anything else I can do to resolve this issue (or help you to resolve it)? It is really extremely annoying for me.

**Comment by tangzx** [comment]
Is there some larger lua files? Here's a known issue : larger file (over thousands of lines) cause bad performance.

**Comment by vstakhov** [comment]
Hum, not sure. Does it count all files or just the current one? My Lua code is mostly placed here: https://github.com/vstakhov/rspamd/tree/master/lualib

Is there any way to disable some inspections to speed up IDE?

**Comment by tangzx** [comment]
I had clone your lualib and all going well in my testing (Clion 2017.1.2). Any other infos ?

**Comment by vstakhov** [comment]
In fact, it now runs pretty smoothly. There was a huge xml file from the test framework that could also cause issues with symbols. Upon removal of it and cleaning up the caches I could not observe the issue. However, it would still be good to configure inspections level for Lua.
