### ISSUE TITLE
老大，能不能显示这个中文注释？

### ISSUE THREAD

**Issue by vincentCheng** [EmmyLua/IntelliJ-EmmyLua#164]
![qq 20180625093005](https://user-images.githubusercontent.com/6327228/41826222-7301d67a-785a-11e8-82c0-96308861d084.png)
![qq 20180625093012](https://user-images.githubusercontent.com/6327228/41826223-73528af2-785a-11e8-9ed0-e8e5c87afdb1.png)
如题。
现在虽然写上去了，但是看不到啊。

**Comment by tangzx** [comment]
在提示出来的时候按 Ctrl + Q
