### ISSUE TITLE
bad ordering of items in the new popup

### ISSUE THREAD

**Issue by nazrhyn** [EmmyLua/IntelliJ-EmmyLua#165]
![image](https://user-images.githubusercontent.com/1672405/42062737-92451408-7afc-11e8-86c6-7a0a80f5e9c4.png)

After installing this plugin, the **New > Lua File** and **New > Lua Tutorial** entries show up _above_ the **New > File** item. This means that I can no longer use <kbd>ALT</kbd> + <kbd>I</kbd>, <kbd>ENTER</kbd> to create a new file. This is a pretty big deal, as it adds additional keyboard or mouse inputs to an action that is performed _quite_ often.

These items should be inserted below the divider, along with the other type-specific items such as **HTML File** or **Javascript File**.

**Comment by nazrhyn** [comment]
@tangzx Thanks for the quick change! I was looking at the diff:

```
relative-to-action="NewXml"
```

What if there is no **New Xml** item? Also, wouldn't this also need to be changed for the **Lua Tutorial** item?

Thanks!

**Comment by tangzx** [comment]
Will be last if there no **New Xml**, **Lua Tutorial** always after **Lua File**.
Just to be sure, I had changed `New Xml` to `NewFromTemplate`

**Comment by nazrhyn** [comment]
Awesome. Thanks, again :heart:.
