### ISSUE TITLE
Lockup when entering function names

### ISSUE THREAD

**Issue by davidgiven** [EmmyLua/IntelliJ-EmmyLua#166]
Using idea-IC-181.5281.24, I'm seeing a complete IDE lockup after entering the first couple of characters of an identifier name.

CPU usage is minimal, which means it's not a spin, and the IDEA window doesn't respond to resize events. Is this a deadlock of some description?

This is on my mostly-Lua-based project at https://github.com/davidgiven/wordgrinder; it's a generic big-bag-of-files project with no frameworks.

I did get this 1000-line stacktrace out of it when I killed the process, which may be useful?

[stackdump.txt](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/2156653/stackdump.txt)

**Comment by ice1000** [comment]
@tangzx AFAIK he has give IDEA version.

**Comment by ice1000** [comment]
Take a look at the stacktrace. Maybe it's useful
