### ISSUE TITLE
EmmyLua lost context when coding in Evalute Window.

### ISSUE THREAD

**Issue by luchuanbaker** [EmmyLua/IntelliJ-EmmyLua#168]
```lua
User = {}
function User.getData()
  local data1 = User._data1
  local data2 = User._data2     --line 4
end
```

While you are debugging the code as shown above, and the current line is line 4, then you press "Ctrl + U" to open the Evaluate Window, in the express input box, when you input "data1" there is no auto complete, and the font of "data1" is italic that indicates it's an undefined variable, but it is defined in fact, so I guess the EmmyLua doesn't provide a correct context to Idea....
And maybe the problem is in the following code(EmmyLua doesn't use the xSourcePosition):
```kotlin
class LuaDebuggerEditorsProvider : XDebuggerEditorsProvider() {
    override fun getFileType(): FileType {
        return LuaFileType.INSTANCE
    }

    override fun createDocument(project: Project,
                                s: String,
                                xSourcePosition: XSourcePosition?,
                                evaluationMode: EvaluationMode): Document {
        val file = LuaElementFactory.createFile(project, s)
        return PsiDocumentManager.getInstance(project).getDocument(file)!!
    }
}
```

**Comment by tangzx** [comment]
solved
