### ISSUE TITLE
debugger is launched even of plain configuration started

### ISSUE THREAD

**Issue by throwable-one** [EmmyLua/IntelliJ-EmmyLua#171]
Hello,
Thank you for this plugin.
When I run lua run configration it tries to attach debugger, while there is separate run type for that in Inellij. 
Is it intentional?

**Comment by LoSuCuBus** [comment]
same for me, how to run without debugging ?

**Comment by ice1000** [comment]
Ping @tangzx

**Comment by tangzx** [comment]
try the last version pls.
