### ISSUE TITLE
userdata做key的table，无法查看对应的value

### ISSUE THREAD

**Issue by xujiezhige** [EmmyLua/IntelliJ-EmmyLua#174]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | C2017.3.5 Ultimate
 EmmyLua version |  v1.2.4
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. …
function Main()
    local goUI = GameObject.Find("UI")

    local testTable = {}
    testTable[goUI.transform] = {nihao = {type = "xujie"}}

    print("TestTable:")
    for k, v in pairs(testTable) do
        print(k)
    end
end
2. …
3. …

What happens?（出现什么问题？）
-------------
这是调试器内的值，对应 com.tang.intellij.lua.debugger.attach.value.LuaXTable@4d25bb75的Table，无法展开

goUI = {userdata} UI (UnityEngine.GameObject)
testTable = {table} 
 com.tang.intellij.lua.debugger.attach.value.LuaXTable@4d25bb75 = {table} 

What were you expecting to happen?（期望？）
-----------------------------------------
…
可以查看对应的值
Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by tangzx** [comment]
新版调试器支持
