### ISSUE TITLE
[Suggestion] region/endregion alias

### ISSUE THREAD

**Issue by adriweb** [EmmyLua/IntelliJ-EmmyLua#175]
To expand on #2.

Several other editors support `{{{`/`}}}` as a start/end of a custom foldable area, like we have in EmmyLua with `region`/`endregion`.
Could it be possible to support this braces tag as an alias for region?

The goal is to have better direct compatiblity to (and from) code written with other editors.

Thanks!

**Comment by faseceroo** [comment]
Working great but not following fold settings, custom folding regions are always expanded on file open ignoring the settings.

![image](https://user-images.githubusercontent.com/93630866/215008523-a17491d1-2300-44f7-b0ca-044c3f19c5d6.jpg)
