### ISSUE TITLE
断点调试中文字符串内容乱码

### ISSUE THREAD

**Issue by ngstyle** [EmmyLua/IntelliJ-EmmyLua#177]
断点调试中文字符串内容乱码

**Comment by tangzx** [comment]
请根据issue模板来填写详细内容

**Comment by ngstyle** [comment]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2018.1.2
 EmmyLua version | v1.2.5
 OS                        |  Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
断点调试

What happens?（出现什么问题？）
-------------
中文字符变量乱码

What were you expecting to happen?（期望？）
-----------------------------------------
望能正确显示中文字符

![format](https://user-images.githubusercontent.com/7988330/43635082-a180f1fc-9740-11e8-986e-3173b847f746.png)


Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------


Any other comments?（其它说明）
------------------------

**Comment by luchuanbaker** [comment]
信息太少了！
调试的什么程序？lua.exe？Unity？cocos？
文件编码是？
调试配置的参数是？
控制台输出是否乱码？
方便提供部分测试代码和测试环境？
