### ISSUE TITLE
迭代器返回类型识别失败

### ISSUE THREAD

**Issue by jinsediaoying** [EmmyLua/IntelliJ-EmmyLua#178]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IC2018.2 EAP
 EmmyLua version | v1.2.5
 OS                        | win 7

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
![t yesn i 3 n874 ebo7](https://user-images.githubusercontent.com/25916527/44076249-ff5fa678-9f8e-11e8-9311-682c7aaa881c.png)

What happens?（出现什么问题？）
-------------
无法识别迭代器返回的类型

**Comment by ice1000** [comment]
你写错了

**Comment by ice1000** [comment]
你的写法的含义是，`test()`返回一个函数，这个函数没有参数，返回`number,A`，因此如果你改成`a()`，再按一下`.`，就可以看到代码提示了。
改成`@return number,A`应该就没有问题。当然也不排除阿唐又写了bug，当然那就是另外一回事了，不属于这个issue讨论范畴。

**Comment by tangzx** [comment]
写法没问题，已解决

**Comment by ice1000** [comment]
@tangzx 蛤？这语义要是对的话那这岂不是很不清真？明明是`return`后面应该跟返回类型啊，怎么跟的是函数类型呢

**Comment by tangzx** [comment]
没错，函数本身也是一种类型
可以看成
`---@return (fun():number, A)`

**Comment by tangzx** [comment]
他那个是省略了，完整的应该是这样
```lua
---@return fun():number, A
function t.test()
    return function()
        return 1, A
    end
end
```

**Comment by ice1000** [comment]
黑历史++
