### ISSUE TITLE
Attach方式调试断点取消后还是会断到

### ISSUE THREAD

**Issue by huang1shan2** [EmmyLua/IntelliJ-EmmyLua#182]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version | [e.g. v1.2.5]
 OS                        | [e.g. OSX 10.13.4, Windows 10]

What happens?（出现什么问题？）
-------------
Attach方式调试，断点取消后还是会断到。
就算终止调试重新Attach还是没法取消之前的断点。

**Comment by huang1shan2** [comment]
重启IDEA这个情况并不会消失.

**Comment by tangzx** [comment]
暂时无法重现

**Comment by tangzx** [comment]
旧版调试不再处理
