### ISSUE TITLE
如果lua工程在windows下的目录链接（mklink  /J）里面，文件对话框（Ctrl+Shift+N）无法列出lua文件

### ISSUE THREAD

**Issue by silverera** [EmmyLua/IntelliJ-EmmyLua#188]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2018.1 (Ultimate Edition)Build #IU-181.4203.550, built on March 27, 2018
 EmmyLua version | 1.2.5-IDEA172
 OS                        | Windows 7 6.1

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 在D盘有一个工程目录client
2. 把该目录复制到C盘，然后重命名D盘这个client成其他名字（工程太大删除很慢）
3. 在D盘给C:\client建一个目录链接（mklink  /J client C:\client）（必须保持相同名字client）
2. 打开D:\client下面的lua工程

What happens?（出现什么问题？）
-------------
菜单Navigate/Files（Ctrl+Shift+N）看不到lua文件，Search Everywhere（double shift）可以看到

What were you expecting to happen?（期望？）
-----------------------------------------
Ctrl+Shift+N能显示工程中的lua文件

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by luchuanbaker** [comment]
试试 mklink /d

**Comment by tangzx** [comment]
试了一下，好像没问题（顺便学到一招）
![image](https://user-images.githubusercontent.com/3354360/45400784-22c1de80-b680-11e8-80aa-5378d2f9f21a.png)

**Comment by luchuanbaker** [comment]
只把编译输出目录移动到ssd即可。。。

**Comment by crazybie** [comment]
等下我试试

**Comment by crazybie** [comment]
E盘下面的链接![qq 20180912123705](https://user-images.githubusercontent.com/7721769/45402564-c9aa7880-b688-11e8-9e85-b9e57f8d0a38.png)

**Comment by luchuanbaker** [comment]
![image](https://user-images.githubusercontent.com/6761331/45402699-8a305c00-b689-11e8-9348-74ec24e3cc27.png)
![image](https://user-images.githubusercontent.com/6761331/45402737-c2d03580-b689-11e8-9b55-f2a9c9c7fe22.png)
可以哦

**Comment by luchuanbaker** [comment]
不会没有设置source folder吧

**Comment by crazybie** [comment]
> 不会没有设置source folder吧

设置是放在工程里面的，源目录打开时对的没有问题。而且奇怪的是，我重新建一个目录链接，把名字换了，就没有问题了

**Comment by ice1000** [comment]
那暂且算作无法复现的bug？

**Comment by crazybie** [comment]
而且奇怪的是，我重新建一个相同源目录的链接，把链接后的名字换了，就没有问题了。是不是什么缓存用了老的名字。
因为我为了保持老的结构，链接后的目录名字保持不变。

**Comment by luchuanbaker** [comment]
> 而且奇怪的是，我重新建一个相同源目录的链接，把链接后的名字换了，就没有问题了。是不是什么缓存用了老的名字。
> 因为我为了保持老的结构，链接后的目录名字保持不变。

这个应该是idea的缓存，清空idea的缓存问题应该就修复了。

**Comment by crazybie** [comment]
我改一下重现步骤，然后试了一下，必现。

**Comment by crazybie** [comment]
> > 而且奇怪的是，我重新建一个相同源目录的链接，把链接后的名字换了，就没有问题了。是不是什么缓存用了老的名字。
> > 因为我为了保持老的结构，链接后的目录名字保持不变。
> 
> 这个应该是idea的缓存，清空idea的缓存问题应该就修复了。

哪里清

**Comment by ice1000** [comment]
形如 `用户/.IntelliJIdea2018.2/` 的目录吧应该是

**Comment by ice1000** [comment]
不过这里面还有你的所有插件什么的。。。

**Comment by crazybie** [comment]
> > 而且奇怪的是，我重新建一个相同源目录的链接，把链接后的名字换了，就没有问题了。是不是什么缓存用了老的名字。
> > 因为我为了保持老的结构，链接后的目录名字保持不变。
> 
> 这个应该是idea的缓存，清空idea的缓存问题应该就修复了。

删了用户配置缓存可以，但是代价有点大，idea像重装了一样。。

**Comment by luchuanbaker** [comment]
> > > 而且奇怪的是，我重新建一个相同源目录的链接，把链接后的名字换了，就没有问题了。是不是什么缓存用了老的名字。
> > > 因为我为了保持老的结构，链接后的目录名字保持不变。
> > 
> > 
> > 这个应该是idea的缓存，清空idea的缓存问题应该就修复了。
> 
> 删了用户配置缓存可以，但是代价有点大，idea像重装了一样。。
。。。。。不对。。。。
File ---Invalid Cache / Restart。。。。。

**Comment by crazybie** [comment]
> > > > 而且奇怪的是，我重新建一个相同源目录的链接，把链接后的名字换了，就没有问题了。是不是什么缓存用了老的名字。
> > > > 因为我为了保持老的结构，链接后的目录名字保持不变。
> > > 
> > > 
> > > 这个应该是idea的缓存，清空idea的缓存问题应该就修复了。
> > 
> > 
> > 删了用户配置缓存可以，但是代价有点大，idea像重装了一样。。
> > 。。。。。不对。。。。
> > File ---Invalid Cache / Restart。。。。。

是的，这个可以

**Comment by silverera** [comment]
就是缓存的问题，File ---Invalid Cache / Restart可以
