### ISSUE TITLE
支持local function

### ISSUE THREAD

**Issue by Xenofex** [EmmyLua/IntelliJ-EmmyLua#191]
你好！非常感谢，这个插件做的很不错。只是发现local function在目前的版本1.2.5-IDEA182并不支持，描述如下：

```lua
local function_a, function_b

---@param a string 参数1
---@param b string 参数2
---@param c string 参数3
function_a = function(a, b, c)
end

---@param a string 参数1
---@param b string 参数2
function_b = function(a, b)
end

```

类似上面的声明，在function_a, function_b上按F1，并看不到文档。希望能支持一下local function，谢谢！

**Comment by tangzx** [comment]
严格来说只有在声明处标注的文档才显示，而你后面的属于赋值操作
两种方法解决
```lua
---@param a string 参数1
---@param b string 参数2
---@param c string 参数3
local function_a = function(a, b, c)
end
```

```lua
---@type fun(a: string, b: string, c: string):void
local function_a

...

function_a = function(a, b, c)
end

```

**Comment by Xenofex** [comment]
感谢回复！我可能会采用`@type`的写法，因为`local function function_a(a, b, c)`会造成函数就在写此处的地方之后生效，因此往往会出现一个文件里函数互相调用于是要根据依赖关系排布声明顺序，有时候因为循环依赖还无法做到的情况。

**Comment by ice1000** [comment]
是的，你想要的那种分析是做不到的，复杂度太高（比如我一个变量被赋值多次，就有多种可能的分析结果，就很纠结）。如果你觉得这个回答可以接受的话把issue关了吧。

**Comment by Xenofex** [comment]
如果把
```lua
function_a = function(a, b, c)
```

作为function_a的类型和文档判别，是否可行？

**Comment by tangzx** [comment]
不能，正如 @ice1000 说的这样做的代价有点高

**Comment by ice1000** [comment]
@Xenofex 不行。你没法保证 `function_a` 就只是一个当前作用域的变量，有可能会是从极复杂的上下文中出现的变量。
另外，IDE插件也应该保护自己的CPU占用。。。

**Comment by Xenofex** [comment]
好的，了解了，感谢两位的回答。
