### ISSUE TITLE
用中文字符命名函数，识别不了

### ISSUE THREAD

**Issue by kunius** [EmmyLua/IntelliJ-EmmyLua#192]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version | [e.g. v1.2.5]
 OS                        | [e.g. OSX 10.13.4, Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. …
2. …
3. …

What happens?（出现什么问题？）
-------------
…

What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by kunius** [comment]
lua可以识别，intellij 识别不了，，，比如 function 黑暗（一） ()

**Comment by ice1000** [comment]
http://lua-users.org/wiki/UnicodeIdentifers

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/46586016-5a853180-ca46-11e8-9448-be60178ed15b.png)

Verified.

**Comment by ice1000** [comment]
Sorry, mistakenly created a commit. Reverted by a force push.

**Comment by ice1000** [comment]
@kunius 已修复
