### ISSUE TITLE
luacheck 没有结果输出

### ISSUE THREAD

**Issue by haolly** [EmmyLua/IntelliJ-EmmyLua#195]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2018.2.4 IDEA CE
 EmmyLua version |  1.2.5 IDEA182
 OS                        | win10

What happens?（出现什么问题？）
-------------
在lua文件中右键run luacheck, 没有结果， 只显示了一个文件名

![image](https://user-images.githubusercontent.com/2383231/47011833-6e7f1080-d175-11e8-8afe-4b50ee81dbea.png)

luacheck 的路径是正确的
![image](https://user-images.githubusercontent.com/2383231/47011942-af772500-d175-11e8-915e-b8608c1c266a.png)

**Comment by haolly** [comment]
每次手动去右键运行luacheck 确实略麻烦，https://github.com/EmmyLua/IntelliJ-EmmyLua/issues/68 这里说的 saveAction 并不能解决问题

**Comment by tangzx** [comment]
可能是你这个文件本身无问题，显示为空。可能要加个提示性的东西

**Comment by haolly** [comment]
![image](https://user-images.githubusercontent.com/2383231/47084385-e61c7080-d245-11e8-8d67-5b93ea50c40e.png)

![image](https://user-images.githubusercontent.com/2383231/47084406-f9c7d700-d245-11e8-9ee2-c7c4ef06b11f.png)

文件是有问题的，上面的图片是同一个文件的luacheck 结果，上面的那个是 sublimetext + luacheck 的输出，下面是 EmmyLua 的输出，没有输出

**Comment by ice1000** [comment]
可以把你用的LuaCheck和这个文件发上来吗

**Comment by haolly** [comment]
> 可以把你用的LuaCheck和这个文件发上来吗

和文件没有关系的，一个简单的有语法错误的test文件都没有任何输出
![image](https://user-images.githubusercontent.com/2383231/47126441-3eda2080-d2bb-11e8-89fc-d532c1cd35b0.png)


[luacheck.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/2489899/luacheck.zip)

**Comment by haolly** [comment]
换了 IDEA CE 2017.1.6 就正常了

**Comment by haolly** [comment]
又不行了。。
