### ISSUE TITLE
Distinction between a class and instance (of a class) - static vs instance methods/variables

### ISSUE THREAD

**Issue by Benjamin-Dobell** [EmmyLua/IntelliJ-EmmyLua#197]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA 2018.2.4 (Ultimate Edition) - Build #IU-182.4505.22, built on September 18, 2018
 EmmyLua version | 1.2.5-IDEA182
 OS                        | macOS 10.13.6

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Create a class, add a static method e.g. using the sample code found in the README animation:

```lua
---@class MyClass
---@field public child MyClass
local cls = {}

function cls:init(name, child)
    self.child = child
    self.name = name
end

---@return MyClass
function cls.new()
    --todo: return new instance
end
```
2. Instantiate an instance of the class (or `@type MyClass` a variable):

```lua
local instance = cls.new()
```

3. Access auto-complete on the instance e.g.

```lua
instance.-- Leave your text cursor here
```

What happens?（出现什么问题？）
-------------
Auto-complete suggests static methods which do not exist on the instance, in this case `new`:

![screen shot 2018-10-18 at 2 43 04 am](https://user-images.githubusercontent.com/482276/47099296-b76fbb80-d280-11e8-98f8-ae9f031935d1.png)

The inverse is also true, if you have a reference to `cls`, instance methods are suggested.

What were you expecting to happen?（期望？）
-----------------------------------------
Only see instance variables/functions on references to an instance of a class, only see static variables/instances on references to a class.
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
As shown in the screenshot above.

Any other comments?（其它说明）
------------------------
I believe there's also no way to type annotate a _reference to a class_.

e.g. Dynamic instantiation example:

```lua
---@class Transport @parent class
---@public field name string
local transport = {}

---@return Transport
function transport.new()
    --todo: return new instance
end

function transport:move()end

---@class Car : Transport @Car extends Transport
local car = {}
function car:move()end

---@return Car
function car.new()
    --todo: return new instance
end

---@class Ship : Transport @Ship extends Transport
local ship = {}

---@return Ship
function ship.new()
    --todo: return new instance
end
```

Now let's create a function that takes a reference to a Transport class (_not_ an instance):

```lua
---@type transportCls ?????? -- <=== WHAT GOES HERE?
---@return Transport
function buildTransport(transportCls)
    return transportCls.new()
end
```

If we were to annotate `transportCls` as `---@type transportCls Transport` that would be incorrect, as that's how you annotate a method that takes an _instance_ of a class. Instances of the class do not have the required `new` function.

**Comment by ice1000** [comment]
@tangzx 意思是说实例上补全出了静态方法。

**Comment by ice1000** [comment]
IMO it's correct. You can call static functions on an object with `.` like `a.staticFunc()`, or instance functions on an object with self passed manually like `a.instanceFunc(a)`, or use `:` like `a:instanceFunc()`.

Why do you think we shouldn't provide completion for valid codes?

**Comment by Benjamin-Dobell** [comment]
> You can call static functions on an object with . like a.staticFunc(),

Here's some sample code, entered in Lua CLI, demonstrating this is not the case:

```lua
> ---@class MyClass
> ---@field public child MyClass
> cls = {}
> 
> function cls:init(name, child)
>>     self.child = child
>>     self.name = name
>> end
> 
> ---@return MyClass
> function cls.new()
>>     local hmm = {}
>>     cls.init(hmm, 'Bob', nil)
>>     return hmm
>> end
> 
> instance = cls.new()
> 
> huh = instance.new()
stdin:1: attempt to call a nil value (field 'new')
stack traceback:
	stdin:1: in main chunk
	[C]: in ?
```

> or instance functions on an object with self passed manually like a.instanceFunc(a), or use : like a:instanceFunc().

This also depends on how your classes are implemented.

I'm using closures to implement my classes because support for _true_ private variables is extremely important to me. As such, none of my methods take a `self` as the first argument.

**Comment by ice1000** [comment]
Plus, if you have this (codes copied from the link above):

```lua
local MyClass = {} -- the table representing the class, which will double as the metatable for the instances
MyClass.__index = MyClass -- failed table lookups on the instances should fallback to the class table, to get methods
```

Your second code should work. This means the completion is correct.

**Comment by Benjamin-Dobell** [comment]
It may be popular, but it's also unsafe, slower at runtime, and doesn't support common OOP such as encapsulation.

I'm using another approach which is also quite common and documented on the same website you just linked:

http://lua-users.org/wiki/ObjectOrientationClosureApproach

The advantages are also documented on that same page.

_Nonetheless_, at the very least, static methods should _never_ be accessible on instances, no matter which approach you're using.

**Comment by adriweb** [comment]
True private vars are nice, but closure-based OOP is severely bad for RAM and speed when you have quite a few instances (I have some benchmarks somewhere, I did some time ago, for work stuff)

Your suggestion to support it would be interesting, but I fear being able to do so would be quite a big task, and may confuse people expecting a different default than whatever the plugin would ship with (I assume the other way, non-closure based). And considering it's not a language built-in, there's simply too many possible variants to correctly handle them all.

**Comment by Benjamin-Dobell** [comment]
> True private vars are nice, but closure-based OOP is severely bad for RAM and speed when you have quite a few instances (I have some benchmarks somewhere, I did some time ago, for work stuff)

It must depend on implementation, the link I just provided claims closures are faster. Admittedly, I've not benchmarked. It definitely uses more RAM, but realistically I don't care about speed or RAM usage that much, I'm more interested in trying to write correct and maintainable code.

I do respect there are different approaches. However, it would be nice to support my use case, marking this as _invalid_ is a bit rough.

Nonetheless, irrespective of approach, a class and an _instance_ are inherently different things e.g. Which metatable will be hit etc. Not having a distinction between them is incorrect.

**Comment by adriweb** [comment]
> Nonetheless, irrespective of approach, a class and an _instance_ are inherently different things e.g.

That's very true, but unless there's specific annotations to add (to at least not provide autocompletion for "new" on an instance, for example), I'm not sure how that would be done (unless hardcoding some method names... but that would probably not make everyone happy? idk)

> Which metatable will be hit etc.

That also depends quite a bit on the implementation. And instance vs Class, parent class, parent classes in case of multiple inheritance oop...

> Not having a distinction between them is incorrect.

Not fully optimal, at best, I'd say. But not incorrect- it's just an implementation choice after all.

**Comment by Benjamin-Dobell** [comment]
```lua
MyClass.__index = MyClass
```

Is this actually common though? Isn't it pretty normal to have instances that have a method that is the same name as a static function, but _isn't_ the same function?

e.g. I have a `Logger`:

```lua
Logger.setLogLevel(Logger.INFO) -- Set global default log level

---@type Logger @typically this is a sub-class e.g. RemoteLogger
local logger -- Assigned somewhere
logger.setLogLevel(Logger.ERROR)

Logger.log('Some warning', Logger.WARNING) -- Logs to console (default logger)

logger.log('Some warning', Logger.WARNING) -- Does not log this message, the log level for _this_ logger is set to only log errors.
```

I definitely don't have statistics on how common this approach is, but I would have assumed this was pretty standard practice.

Also, I still don't really know how you can go about doing any sort of dynamic instantiation (builder pattern etc.) like `buildTransport` in my initial comment. `transportCls` should always be a _class_, not an instance, all sorts of shenanigans could have happened to the instance e.g. `new` might be a `boolean` field on a subclass 😕

**Comment by tangzx** [comment]
As @ice1000 and @adriweb say, your suggestion is rigorous and can be apply to oop based language, but not lua. It's hard to decide whether or not a property/method is static.

> Please understand that we only provide support for the most popular and widely used approach of simulating class-based object-oriented programming in a prototyping language.
---

> I believe there's also no way to type annotate a reference to a class.
Please take a look at documentation for annotation `@generic`.

```lua
---@generic T : Transport @ <<< define a generic parameter type T
---@param transportCls T @ <<< @param not @type
---@return T
function buildTransport(transportCls)
    return transportCls.new()
end
```
