### ISSUE TITLE
使用 : 访问table函数出现Missing argument警告

### ISSUE THREAD

**Issue by slaier** [EmmyLua/IntelliJ-EmmyLua#199]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IU-182.4129.33
 EmmyLua version | 1.2.6
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
```lua
---@class class
local class = {}

---@param self Class
---@param v number
function class.method(self, v)
    print(v)
end

function class:method2() end

class:method(1)
```

What happens?（出现什么问题？）
-------------
1. 出现Missing argument警告

![image](https://user-images.githubusercontent.com/30682486/47228219-43a3ef00-d3f7-11e8-8984-691372454c0b.png)

2. 缺少代码提示

![image](https://user-images.githubusercontent.com/30682486/47228985-296b1080-d3f9-11e8-9bcf-479cfb924a46.png)

What were you expecting to happen?（期望？）
-----------------------------------------
1. 没有警告
2. method(v) [class] void 代码提示

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
none

Any other comments?（其它说明）
------------------------
none

**Comment by tangzx** [comment]
目前 Lint > Type safety 系列的 Inspections 还不够完善，处于实验阶段，建议不要开启。
另外第个问题是由于你类型写错了，注意大小写
`---@param self Class` 应写成 `---@param self class`
