### ISSUE TITLE
Getting runtime error while trying to execute  coroutine.yield() function

### ISSUE THREAD

**Issue by dinesh-hirani** [EmmyLua/IntelliJ-EmmyLua#200]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version | [e.g. v1.2.5]
 OS                        | [e.g. OSX 10.13.4, Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Please execute this 

```lua
function Utils:waitForTime(time,update)
        local now = system.getTimer()
        local ends_at = now + time
        while now < ends_at do

            if update then
                update()
            end
            coroutine.yield()
            now = system.getTimer()
        end
end 
```

What happens?（出现什么问题？）
-------------
getting error "attempt to yield across metamethod/C-call boundary"

What were you expecting to happen?（期望？）
-----------------------------------------
Coroutine should work fine.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by tangzx** [comment]
Please google the error "attempt to yield across metamethod/C-call boundary"
