### ISSUE TITLE
子table中的函数无法正确识别

### ISSUE THREAD

**Issue by onlonely** [EmmyLua/IntelliJ-EmmyLua#201]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version | [e.g. v1.2.5]
 OS                        | [e.g. OSX 10.13.4, Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
使用如下代码
```
local test={}
test.aclass={}
function test.aclass.funname(...)
  print(...)
end
```
此时使用test.aclass.这样是不能点出funname方法的

但是如果这样书写库
```
local test={}
local aclass={}
test.aclass=aclass
function aclass.funname(...)
  print(...)
end
```
此时使用test.aclass.这样能点出funname方法

What were you expecting to happen?（期望？）
-----------------------------------------
两种写法在lua中都是支持的
在插件中好像就无法识别出来

**Comment by tangzx** [comment]
这是一个已知问题#46
你可以这样做

```lua
local test = {}

local aclass = {}
function aclass.funname(...)
end

test.aclass = aclass

```

**Comment by tangzx** [comment]
刚才没看到，和你下面的做法是一样的，总之目前类似`a.b.c`超过两层的不能提示
