### ISSUE TITLE
self关键字冲突

### ISSUE THREAD

**Issue by xp168** [EmmyLua/IntelliJ-EmmyLua#205]
![image](https://user-images.githubusercontent.com/7510080/48473053-9a53eb80-e832-11e8-8f65-7bed14e47378.png)

当内部使用self重新赋值时 ，导致所有的self指向有误 

![image](https://user-images.githubusercontent.com/7510080/48473455-7513ad00-e833-11e8-8912-ac33a9ac0ebc.png)

**Comment by tangzx** [comment]
一般情况下不会这样给self赋值，不过考虑到严谨性，后面有空再解决这个问题
