### ISSUE TITLE
匿名函数里面的函数不能跳转到定义

### ISSUE THREAD

**Issue by haolly** [EmmyLua/IntelliJ-EmmyLua#210]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [2018.2.4CE  IDEA]
 EmmyLua version | [1.2.6]
 OS                        | [Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
``` lua
self:register_button_event(self.handler.btn_dance, function()
    self:dance()
end)
```

What happens?（出现什么问题？）
-------------
dance() 函数不能跳转到定义

What were you expecting to happen?（期望？）
-----------------------------------------
和其他函数一样能跳转到定义

**Comment by tangzx** [comment]
这个是没问题的，你把上下文环境补充完整看看


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by haolly** [comment]
``` lua  test.lua
local base_view		= require "hello2" -- not ok
--local base_view		= require "hello" -- ok

local mt = base_view.new("name", 1)

function mt:_show()
    self:register_button_event(self.handler.btn_dance, function()
        self:dance()
    end)
end

function mt:dance()
end


return mt
```

``` lua
--- hello2.lua
local BASE = {}

local mt = setmetatable({}, BASE)


function mt.new(desc_path, ui_id)
    local ins = setmetatable({}, mt)
    mt.ctor(ins, desc_path, ui_id)
    return ins
end

return mt
```

```lua
---hello.lua
local mt = {}
function mt.new(view_id)
    local ins =  setmetatable({}, mt)
    ins:ctor(view_id)
    return ins
end

return mt
```

**Comment by tangzx** [comment]
试过了，没问题

**Comment by haolly** [comment]
难道是我的版本有问题嘛 😕  事实上，当 require "hello2"  的时候，所有的跳转都不起作用了，不仅仅是匿名函数里面的

**Comment by tangzx** [comment]
看看右下角有没有报错。可以试试菜单 File | Invalidate cache and restart

**Comment by haolly** [comment]
试了 File | Invalidate cache and restart, 结果是一样的

**Comment by haolly** [comment]
把 hello2.lua 中的 这一句删掉就好了 `local mt = setmetatable({}, BASE)`

**Comment by tangzx** [comment]
不错，是这的问题，解决了。不过还是建议你用`@class`注解
