### ISSUE TITLE
匿名函数里的参数不能识别

### ISSUE THREAD

**Issue by wwwfox** [EmmyLua/IntelliJ-EmmyLua#212]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IC2018.2.7
 EmmyLua version | 1.3.0-eap-11
 OS                        | Windows 7

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------

```lua
function funcNameA(id,id2)
end

function funcNameB(callfunc)
end

function funcNameC(id)
    if id == 1 then
        require("cc.bb.aa").new(id,function(id2)
            funcNameA(id, id2) -- 不能识别id,id2
        end):addToScene()
    elseif id == 2 then
        require("cc.bb.bb").new(id,function(id2)
            funcNameA(id) -- 可以识别id,id2
        end)
    end
    funcNameB(function(id2) 
        funcNameA(id,id2)  -- 不能识别id,id2
    end):addToScene()
    funcNameB(function(id2)
        funcNameA(id,id2) -- 可以识别id,id2
    end)
end
```

What happens?（出现什么问题？）
-------------
id,id2无法识别

What were you expecting to happen?（期望？）
-----------------------------------------
能够正确识别

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by ice1000** [comment]
tql
