### ISSUE TITLE
lua远程调式挂起u3d不能执行

### ISSUE THREAD

**Issue by jy01807853** [EmmyLua/IntelliJ-EmmyLua#214]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IC172
 EmmyLua version | 1.2.6-IDEA172
 OS                        | windowns 10
unity                      | 2017.3

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
必现，启动远程调式，启动成功，启动u3d连接成功，但是u3d卡死，停掉调试，u3d恢复运行，bug？

What happens?（出现什么问题？）
-------------
![qq 20190103181430](https://user-images.githubusercontent.com/44150157/50632619-6cae3780-0f83-11e9-9ca6-023d127b856c.png)
必现，启动远程调式，启动成功，启动u3d连接成功，但是u3d卡死，停掉调试，u3d恢复运行，bug？

What were you expecting to happen?（期望？）
-----------------------------------------

可以使用远程调式

Any logs, error output, etc?（有没有什么log,  error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

无错误日志

Any other comments?（其它说明）
------------------------
…

**Comment by tangzx** [comment]
格式已经给你更新了，下次注意。
描述太简单，无法测试，最好直接上传最简工程，打成zip
