### ISSUE TITLE
关于v1.3.0-eap-14-IDEA182的后续修改建议

### ISSUE THREAD

**Issue by qtcdxxyuc** [EmmyLua/IntelliJ-EmmyLua#216]
Environment（环境）
--------------
| name            | version                 |
| --------------- | ----------------------- |
| IDEA version    | [CLion2018.1.2,#CL183]  |
| EmmyLua version | [v1.3.0-eap-14-IDEA182] |
| OS              | [UBUNTU 18.04LTS]       |

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
在上次提交的`issue:#211`中已经修复了`bug`(在`run`按钮按下时,确实能够执行运行而不是调试).

现在有一条改进建议议.

What happens?（出现什么问题？）
-------------
在`run`按钮按下时,若当前`lua`经过修改(尚未保存),则此时执行的是的修改前的`lua`.

当希望执行修改后的`lua`时,我必须先保存然后再重新运行,才能执行新修改的`lua`.

What were you expecting to happen?（期望？）
-----------------------------------------
当`run`按钮按下时,会帮我保存当前已修改且尚未保存的`lua`然后执行.

或者提供一个选项可以选择运行前是否保存未修改的代码.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
NOT

Any other comments?（其它说明）
------------------------
个人认为设置成运行前保存比较符合`IDE`的统一行为.
在我使用的`clion`里,对的`c++`代码的处理即是,在点击运行时先保存然后再执行的.

**Comment by tangzx** [comment]
在IDEA下是正常的，可能在Clion下有问题？

**Comment by tangzx** [comment]
可以试试新版
