### ISSUE TITLE
注释不能手动换行

### ISSUE THREAD

**Issue by qtcdxxyuc** [EmmyLua/IntelliJ-EmmyLua#219]
Environment（环境）
--------------
| name            | version               |
| --------------- | --------------------- |
| IDEA version    | [CL183]               |
| EmmyLua version | 1.3.0-eap-23,clion3.3 |
| OS              | ubuntu 18.04LTS       |

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
书写注释时,形如:

```lua

---
---绑定一个服务.
---假定proto下的包名为foo.bar的包中有服务
---test_service{rpc baz(...)returns(...)
---则其name为 foo.bar.test_service
---其service应为table{baz = function(request)return response end}
```

注释在显示的时候是根据弹出的窗口大小自动换行显示的而不是按照注释中的书写方式换行.

What happens?（出现什么问题？）
-------------
注释不能手动换行

What were you expecting to happen?（期望？）
-----------------------------------------
添加手动换行按钮,或者提供`@code`,`@encode`这么一对标记符,期间的注释原样输出

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
not

Any other comments?（其它说明）
------------------------
not

**Comment by luchuanbaker** [comment]
这个好像是新版修改了md的渲染方式导致的，md渲染后换行直接丢弃了。。。旧版是正常的。
