### ISSUE TITLE
Attach调试问题集中反馈（Issues about attach debugger）

### ISSUE THREAD

**Issue by tangzx** [EmmyLua/IntelliJ-EmmyLua#221]
有问题的请到这里集中反馈，尽量说清楚情况，最好能提供重现环境（程序/代码/版本）

**Comment by tangzx** [comment]
#182 Attach方式调试断点取消后还是会断到 bug

**Comment by ccyr119** [comment]
还有断点的数量也会影响，调试的是删除不需要的断点，可以提升Attach的速度

**Comment by keeeepgo** [comment]
怎么在Rider中使用emmylua进行断点调试？它不像IntelliJ IDEA那样有Project Structure。

**Comment by tangzx** [comment]
> 怎么在Rider中使用emmylua进行断点调试？它不像IntelliJ IDEA那样有Project Structure。

暂不支持，调试要传递相对路径，没有source root就不好办了。

**Comment by tangzx** [comment]
> 怎么在Rider中使用emmylua进行断点调试？它不像IntelliJ IDEA那样有Project Structure。

进群用新版调试，可以不用设置source root
