### ISSUE TITLE
Hang when editing multiline strings

### ISSUE THREAD

**Issue by vstakhov** [EmmyLua/IntelliJ-EmmyLua#224]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | CL2018.3.4
 EmmyLua version | v1.2.6-IDEA182
 OS                        | OSX 10.13.6

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Create multiline string in Lua using `[[str<newline>str<newline>...]]`
2. Edit something in that string
3. Type `_` character

What happens?（出现什么问题？）
-------------

Some strange hint window appears on top of IDE (autocompletion I suppose). IDE hangs in a deadly matter using >100% CPU, the only way is to kill it hardly.

What were you expecting to happen?（期望？）
-----------------------------------------

No hang.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------

Due to full hang of IDE I was unable to get any logs.

Any other comments?（其它说明）
------------------------

**Comment by tangzx** [comment]
I couldn't reproduce this issue. Can you please show me some explicit test case?

**Comment by vstakhov** [comment]
I will try to: it happens quite often when I'm editing multi-line strings in Lua. However, it is hard to reproduce this issue in a stable matter indeed. I have tried to attach debugger to Clion process and it shows that there is likely a deadlock somewhere. So I assume it as a sync issue.
