### ISSUE TITLE
[Suggestion] Use a 'bunch' tool for maintaining support for multiple IDEA versions

### ISSUE THREAD

**Issue by yanex** [EmmyLua/IntelliJ-EmmyLua#229]
Hello @tangzx! Thank you for the awesome Lua plugin!

I plan to use it as the recommended way for writing Lua plugins for my macOS file manager. So I thought it might be a good idea to support the EmmyLua plugin development at least a bit.

(Are there any things I could do? Bugfixes, intentions/inspections? Debugger?)

I looked through the codebase, and I noticed you use patches for supporting older platform versions, such as 181 and 182. So I wanted to share my experience as a Kotlin plugin developer.

Some time ago we used branches for different platform versions (e.g. `master_182`). CI checked out these branches and rebased them on `master`. This allowed us to easily check out the 'platform' branch and fix the compatibility issues without losing history.

In essence, our branch structure looked like:
`master` ← main platform (e.g., 183).
`master_182` ← changes 182..183.
`master_181` ← changes 181..182.

In other words, to apply changes for 181, we first needed to rebase the `master_182` branch, and then rebase `master_181` on the result.
It was quite tiring to keep the patchset branches up-to-date, as we have to maintain plugins for multiple IDEA and Android Studio versions.

So we made a [bunch tool](https://github.com/JetBrains/bunches) that allows us to keep changes right in the repository. The only thing you need is to add the `.bunch` file to the repository root and describe all supported platforms there ([here is the .bunch file](https://github.com/JetBrains/kotlin/blob/master/.bunch) for the Kotlin repo). Whenever you encounter a breaking change in the platform, you create the 'bunch' file and include the required changes.
The `bunch` utility allows you to switch to the particular platform version (`bunch switch . 181`) and create the `bunched` versions of the commits (`bunch cp . <startingCommit> <bunchCommit> 182`).

Here's the example of bunched files:
For the primary (183) platform: https://github.com/JetBrains/kotlin/blob/master/idea/idea-analysis/src/org/jetbrains/kotlin/idea/search/IndexPatternBuilderAdapter.kt
For 182 platform: https://github.com/JetBrains/kotlin/blob/master/idea/idea-analysis/src/org/jetbrains/kotlin/idea/search/IndexPatternBuilderAdapter.kt.182

The key is to make 'bunched' files as small as possible.

The bunch tool saved us a ton of frustrating work, and I highly recommend it.

**Comment by tangzx** [comment]
Thanks ! The bunch tool sounds awesome, I'll try it!
And yes here's lots things to do, Bug fixes, intentions/inspections, documentation... Do any thing you are interested in and will help me a lot.
One of the biggest trouble so far is some issue like [ErrorReport#52](https://github.com/EmmyLua/EmmyLua-ErrorReport/issues/52)，index/stub issues. I don't know why and how to reproduce. I noticed that you are the official developer，can you help me the reason, thanks!

**Comment by tangzx** [comment]
Bunch is great! 👍
