### ISSUE TITLE
Implicit table constructors for expected class type fails

### ISSUE THREAD

**Issue by yanex** [EmmyLua/IntelliJ-EmmyLua#230]
Is the code below supposed to work?

```lua
---@class Context
---@field member string
local context = {}

---@class Foo : table
---@field id string
---@field action fun(context:Context):void
local foo = {}

---@param foo Foo
function builder(foo) end

builder {
    id = "str",
    action = function(context)
        context.member
    end
}
```

1. Can a `@class` inherit from `table`?
2. Should table literals infer its type from the parameter expected type?

**Comment by tangzx** [comment]
> 1. Can a `@class` inherit from `table`?

Yes, but that is redundant. every class implicitly extends table. just like class in java

> 2. Should table literals infer its type from the parameter expected type?
Yes, it should be.
OK
![image](https://user-images.githubusercontent.com/3354360/53316030-2c26c680-3901-11e9-8c5c-6669afdb4e44.png)
BUG
![image](https://user-images.githubusercontent.com/3354360/53316043-39dc4c00-3901-11e9-9e43-209062ab39da.png)

OK
![image](https://user-images.githubusercontent.com/3354360/53316103-7c058d80-3901-11e9-893f-5e048fd190ac.png)
BUG
![image](https://user-images.githubusercontent.com/3354360/53316111-87f14f80-3901-11e9-8ec7-45bdce743d05.png)

**Comment by yanex** [comment]
Making all classes implicitly extend 'table' pretty limits the `@class` annotation usage, as the other candidate for the class supertype is 'userdata'. The significant difference is that classes extending userdata can't be created from the Lua code.

So looks like there at least two possible solutions:
1. A class declared with a `userdata` supertype doesn't extend 'table': `@class Foo : userdata`.  
Passing tables as instances of such classes is prohibited.  
`@class Bar` still extends 'table' to preserve compatibility.
2. Add the new annotation on a class: `@builderSyntax` (name TBD). Only classes with this annotation can be passed as table literals.

The first solution feels more natural to me though it requires changes in the type system.
The second solution is more ad-hoc. However, the implementation should be a bit simpler.
