### ISSUE TITLE
给全局变量定义的方法内部的self没法识别

### ISSUE THREAD

**Issue by ccyr119** [EmmyLua/IntelliJ-EmmyLua#234]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | Intellij IDEA Community 2018.3.5
 EmmyLua version | v1.2.6-IDEA182
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 定义一个全局变量，使用@class 注解
2. 为该全局变量定义一个(实例)函数
3. 在该函数内使用self

What happens?（出现什么问题？）
-------------
给全局变量定义的方法内部的self没法识别

What were you expecting to happen?（期望？）
-----------------------------------------
全局变量的函数定义中的self能和局部变量的函数中的self一样能正常识别为对应的类型

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
无

Any other comments?（其它说明）
------------------------
无

**Comment by luchuanbaker** [comment]
刚刚测试了如下的代码：
---@class C
C = {}

function C:say()
  self.--在这里按.或者:的时候都会有代码提示的
end

**Comment by ccyr119** [comment]
找到原因了，是我这边有一个地方写错了，导致self变成了全局变量
self,CurrActionState = ActionState.Complete
点号协程逗号了。
