### ISSUE TITLE
Intellij+EmmyLua的组合能否支持远程解释器？

### ISSUE THREAD

**Issue by Cantoria** [EmmyLua/IntelliJ-EmmyLua#238]
What happens?（出现什么问题？）
-------------
我是lua新手，现在遇到了这样的业务场景：
有一个lua项目在服务器上，但我想在本地的Intellij中对服务器上的lua代码进行调试。且需要用到服务器上的lua解释器进行调试。
我是这么做的：
1、在本地的Intellij中设置了SFTP并安装了EmmyLua，在服务器上部署了Mobdebug；
2、在服务器上开启了Mobdebug，并在本地telnet测试端口可用；
3、在本地要测试的代码前加入了
`require("mobdebug").start("10.60.1.79", 8172)`
代码；
4、在本地的Edit Configurations进行配置Lua Application。我发现在配置中的Program选项只能配置本地的lua解释器，没有找到配置远程主机上的lua解释器。最后只在File-->Project Structure-->Project Settings-->Project-->Project SDK中找到了
![image](https://user-images.githubusercontent.com/13050299/55155444-57b3ff80-5192-11e9-9242-8a850c3ae6fa.png)

![image](https://user-images.githubusercontent.com/13050299/55155318-00ae2a80-5192-11e9-982f-c5396c61e56b.png)
这个未知的解释器（我保证这个路径是存在的，且这个lua解释器是可用的）。

What were you expecting to happen?（期望？）
-----------------------------------------
请问：
1、Intellij+EmmyLua的组合能否支持远程解释器？如果能，该怎么配置？
2、为什么本地的lua解释器可以被感知，远程服务器的lua解释器被识别为unknown？

Any other comments?（其它说明）
------------------------
谢谢lua大佬解答，在下不胜感激。

**Comment by luchuanbaker** [comment]
不需要配置这个是sdk，直接创建一个lua remote的调试配置，然后调试模式启动它，那个启动mobdebug的IP是你本机的ip，然后通过putty之类启动服务器上的lua，就会自动进入断点了。
远程调试的原理其实是本地emmylua创建了一个服务端，远程的lua代码启动的时候通过mobdebug连接到本地的emmylua监听的端口，然后他们才进行通信的。。。

**Comment by Cantoria** [comment]
> 不需要配置这个是sdk，直接创建一个lua remote的调试配置，然后调试模式启动它，那个启动mobdebug代码中的IP是你本机的ip，然后通过putty之类启动服务器上的lua，就会自动进入断点了。
> 远程调试的原理其实是本地emmylua创建了一个服务端，远程的lua代码启动的时候通过mobdebug连接到本地的emmylua监听的端口，然后他们才进行通信的。。。

请问怎么在服务器端创建lua remote并启动？

**Comment by Cantoria** [comment]
> 不需要配置这个是sdk，直接创建一个lua remote的调试配置，然后调试模式启动它，那个启动mobdebug代码中的IP是你本机的ip，然后通过putty之类启动服务器上的lua，就会自动进入断点了。
> 远程调试的原理其实是本地emmylua创建了一个服务端，远程的lua代码启动的时候通过mobdebug连接到本地的emmylua监听的端口，然后他们才进行通信的。。。

已经明白，多谢大神指点！
