### ISSUE TITLE
lua代码错误导致IDEA崩溃

### ISSUE THREAD

**Issue by yuz10** [EmmyLua/IntelliJ-EmmyLua#240]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IDEA 2018.3.6 或  Clion 2019.1
 EmmyLua version | v1.2.8
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
```
local p={}
for k,p in pairs(p) do
    local pk = p.k
end
```

What happens?（出现什么问题？）
-------------
IDEA卡死

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
CPU占用高

**Comment by tangzx** [comment]
回退到1.2.6看行不行

**Comment by tangzx** [comment]
1.2.8 以下代码导致卡死（纪录一下）
```lua
local a = {}

function a.b()
    a.foo = a.bar()
    return a.foo
end

function a.fee()
    a.b().c = 1
end
```
