### ISSUE TITLE
how to use code formatter 

### ISSUE THREAD

**Issue by chensunny** [EmmyLua/IntelliJ-EmmyLua#242]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version | [e.g. v1.2.5]
 OS                        | [e.g. OSX 10.13.4, Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. …
2. …
3. …

What happens?（出现什么问题？）
-------------
I can't find any  doc to use code formatter feature

What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by luchuanbaker** [comment]
有使用上的问题请到QQ群资讯，GitHub的issue用于提bug、改进。
