### ISSUE TITLE
如果能增加一个提取变量的功能就太棒了

### ISSUE THREAD

**Issue by HugoFang** [EmmyLua/IntelliJ-EmmyLua#244]
local a= c+d+e
local b=c+d+f+g
当选中c+d时,按下快捷键, 比如ctrl+alt +v 进行变量提取
提取后的代码
local cd=c+d
local a=cd+e
local b=cd+f+g
这个加入这个功能帮助就太大了

**Comment by HugoFang** [comment]
扩展下, 提取方法功能
选中一段代码 按下 ctrl+alt+m快捷键
将该段代码提取为一个方法....

**Comment by tangzx** [comment]
可以先用这个https://emmylua.github.io/postfix/var.html

**Comment by HugoFang** [comment]
原来有这个功能，太棒了

**Comment by ice1000** [comment]
原来有这个功能，太棒了
