### ISSUE TITLE
断点位置与has_breakpoint中打印的不一致

### ISSUE THREAD

**Issue by yzqlwt** [EmmyLua/IntelliJ-EmmyLua#246]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version | [e.g. v1.2.5]
 OS                        | [e.g.  Windows 10]

What happens?（出现什么问题？）
-------------
断点位置与has_breakpoint中打印的不一致

**Comment by tangzx** [comment]
具体一点？把打印的结果贴出来。
这种情况一般是由于：
* `source root`没设置正确，`source root`相当于c里面的include路径
* 宿主程序的 `lua_load` 提供的`chunkname`不正确

**Comment by yzqlwt** [comment]
> 具体一点？把打印的结果贴出来。
> 这种情况一般是由于：
> 
> * IDEA里的`source root`没设置正确，`source root`相当于c里面的include路径。调试器会根据这个得出相对路径传给mobdebug
> * 宿主程序的 `lua_load` 提供的`chunkname`不正确

source root 应该是设置正确了
目录结构是这样的
工程目录-----res, src...
src------------games, client....
client---------main.lua
尝试过src设为source root和把client设为source root 都不可以

**Comment by Aaron009** [comment]
我也遇到此问题了，我解决了。https://forum.cocos.com/t/lua/78205

**Comment by yzqlwt** [comment]
> 我也遇到此问题了，我解决了。https://forum.cocos.com/t/lua/78205

nice
