### ISSUE TITLE
Can't navigate to the source code

### ISSUE THREAD

**Issue by zhenlingcn** [EmmyLua/IntelliJ-EmmyLua#248]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | Pycharm 2019.1
 EmmyLua version | v1.2.7
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
```lua
require 'torch'
```
Source code run as properly. But I can't navigate to the source code.

What happens?（出现什么问题？）
-------------
I have the Torch source code and add the path to additional sources root. But when I click torch and try to navigate source code, nothing happens.

What were you expecting to happen?（期望？）
-----------------------------------------
I want this plugin can navigate the source code where locate in "%LUA_PATH%\bin\lua."

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
no

**Comment by tangzx** [comment]
Does the `torch.lua` actually exist? And, the `require` navigation depends on `source root` settings, have you configured the `source root`?

**Comment by zhenlingcn** [comment]
`torch.lua` is not located at project directory. I have installed it by Luarocks. So, the core issue is how I can navigate the source code introduced by Luarocks?

**Comment by adriweb** [comment]
You can add a (global) source root for it and it will work fine.

**Comment by luchuanbaker** [comment]
> `torch.lua` is not located at project directory. I have installed it by Luarocks. So, the core issue is how I can navigate the source code introduced by Luarocks?

You need create `torch.lua` file by yourself and write APIs in it according to https://github.com/torch/torch7/tree/master/doc

Then add the `torch.lua` file as a lua library to the project, then EmmyLua will support code complete for torch.

And if you have the source code for torch (which is lua file), you can just add it as lua libray to the project. 
To be exactly, EmmyLua can't find the source code of the modules installed by Luarocks(do they have source code?)

**Comment by luchuanbaker** [comment]
这么说吧，你需要自己写Torch的api文件，就是把Torch的api写到torch.lua文件中（方法只需要声明，不需要实现，可以通过注解给方法和参数增加注释）。
你通过luarocks安装的模块应该都没有源码吧，只有库，如果你想要看源码，EmmyLua肯定是看不了的，如果你想要EmmyLua给出代码提示，那么你就需要把官方的api文档转写成lua文件格式，然后作为lua的库添加到你的project中，然后就可以了。有什么不清楚了请加入官方QQ群询问。

**Comment by tangzx** [comment]
Some lua libraries are written in c/c++, like `cjson`, `luasocket`..., that means there's no lua source file to navigate. In this case you have to write API-Files(similar to `.d.ts` file for `typescript`) manually and add API-Files to your project.

**Comment by zhenlingcn** [comment]
> Some lua libraries are written in c/c++, like `cjson`, `luasocket`..., that means there's no lua source file to navigate. In this case you have to write API-Files(similar to `.d.ts` file for `typescript`) manually and add API-Files to your project.

Thanks a lot. After I read the Torch source code, I find these methods are implemented by c++, and they only wrapped by Lua. It's reasonable not to provide source code navigate function.
