### ISSUE TITLE
同名文件代码提示异常

### ISSUE THREAD

**Issue by imfox** [EmmyLua/IntelliJ-EmmyLua#249]
![1](https://raw.githubusercontent.com/imfox/imgStore/master/emmy/1.png)
![2](https://raw.githubusercontent.com/imfox/imgStore/master/emmy/2.png)
![3](https://raw.githubusercontent.com/imfox/imgStore/master/emmy/3.png)

MainConst 并没有声明.. 这个LOADING_MAIN_RES... 但还是提示了

**Comment by luchuanbaker** [comment]
不应该有这个问题啊，匿名的类是通过文件名加变量声明的文档偏移量作为匿名类的标识进行索引的，两个c所在的文件名不一样啊。
你弄一个最小的问题demo上传，让阿唐来看吧。
