### ISSUE TITLE
F8单步调试直接跳出调试，并没有进入下一步

### ISSUE THREAD

**Issue by happy253650035** [EmmyLua/IntelliJ-EmmyLua#251]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [2018.3.4]
 EmmyLua version | [v1.2.9-IDEA182]
 OS                        | [Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1.在任意行添加断点
2.开启调试
3.进入断点后点击F8进行单步调试

What happens?（出现什么问题？）
-------------
直接跳出调试，未进入下一步（点F7单步进入可以正常执行）

What were you expecting to happen?（期望？）
-----------------------------------------
可以进入下一步调试

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
无

Any other comments?（其它说明）
------------------------
…

**Comment by Zeromixis** [comment]
碰到了同样的问题

**Comment by luchuanbaker** [comment]
说一下开发的内容，比如是Unity、cocos、Openresty、lua.exe

**Comment by Zeromixis** [comment]
在Unity上 VsCode和IDEA都是如此 EmmyLua版本和IDE版本都是最新的

**Comment by tangzx** [comment]
旧版调试不再维护，试试新版本调试吧。进群下载
