### ISSUE TITLE
变量作用域语法提示错误：递归函数将局部变量认为是upvalue

### ISSUE THREAD

**Issue by Zolo-mario** [EmmyLua/IntelliJ-EmmyLua#252]
Environment（环境）
--------------
   name   |   version  
----------|----------
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 查看代码即可

What happens?（出现什么问题？）
-------------
简单的fact函数如下
```lua
local function fact(n)
    if n == 0 then
        return 1
    else
        return n * fact(n - 1)
    end
end
```
会显示函数体中的fact是upvalue（黄绿色下划线）

What were you expecting to happen?（期望？）
-----------------------------------------
fact是一个局部变量，不应该有这个提示

**Comment by sumneko** [comment]
fact是upvalue，见 http://cloudwu.github.io/lua53doc/manual.html#3.4.11
