### ISSUE TITLE
This plugin silently disables `inline variable` refactoring for ALL languages

### ISSUE THREAD

**Issue by dkandalov** [EmmyLua/IntelliJ-EmmyLua#256]
v1.2.10-IDEA182
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
Also broken in other IJ versions.

One of the worst bugs I've experienced because initially I blamed it on IJ eap versions. Then assumed it was some kind of misconfiguration. Then after finding IDE where `inline` worked, I spent hours doing "binary search" disabling IDE plugins and waiting for reindex.

**Comment by tangzx** [comment]
Fixed, please try  https://ci.appveyor.com/project/EmmyLua/intellij-emmylua-7n83m/builds/25572601/artifacts

**Comment by dkandalov** [comment]
Thanks a lot for a quick fix! 
I'm not using Lua on daily basis though so can't promise to try it very soon.

**Comment by rulatir** [comment]
@dkandalov thanks for doing the work! I even reported a bug against PHPStorm, only to find this.

**Comment by mdnorman** [comment]
I was having this same issue. I've tested this, and it seems to fix the problem with other languages without any adverse issues with editing LUA. Thanks!
