### ISSUE TITLE
希望增加一个功能，按下ctrl + / 输出三个横线而不是两个

### ISSUE THREAD

**Issue by zhanghuizong** [EmmyLua/IntelliJ-EmmyLua#257]
按下ctrl + / 快捷键，

**期望值：**
希望输出的是：---横线

主要觉得手动输入闲麻烦，而通过IDEA工具暂未发现可修改快捷键ctrl + /所对应的内容

**Comment by luchuanbaker** [comment]
你说的热键是快速注释，而且是eclipse中的，你把idea的热键改为eclipse的版本，就可以了。emmylua支持的。

**Comment by tangzx** [comment]
`ctrl + /` 生成的是常规注释
`--`  对应其它语言里的 `//`
`---` 对应其它语言里的 `/* */`，用来作为注解，注解的生成有快捷键，用`alt+enter`
