### ISSUE TITLE
功能需求：annotation系统，编辑时打完函数名字显示函数的概述

### ISSUE THREAD

**Issue by zoloypzuo** [EmmyLua/IntelliJ-EmmyLua#258]
需求的效果参见LDoc，还有Pycharm对Python的代码注释文档系统

我看到annotataion系统是由有@comment语法的，但是编辑时并不会提示这个

比如
```lua
---@type fun() @do something
function f() end
```

我希望打完f后提示do something

这个需求不是必须的

**Comment by tangzx** [comment]
这个 `@comment` 的确是个BUG，目前其实是没处理它。暂时建议这样注释
```lua
--- comment
---@type ...
```
另外你的type写的有问题，type只能给 local, global变量注释
```lua
--- do something
---@type fun():void
local f
```
