### ISSUE TITLE
Some suggestions and bugs...

### ISSUE THREAD

**Issue by adriweb** [EmmyLua/IntelliJ-EmmyLua#26]
Hello,
Great job on this plugin, it looks very promising and already has some features that are superior to Sylvanaar's Lua plugin that I was using until now... :)

Here is some feedback (I'll probably edit this message as I go):

### Bugs: 
- [x] `local a = function(...)` isn't recognized as a function, contrary to `local function a(...)`. ([screenshot](https://user-images.githubusercontent.com/660896/27486471-f6d80140-5830-11e7-9bff-fed58ed746b1.png))
- [ ] Blacklisting parameter hints (right click on them) doesn't work (no function name detected ,as far as I can tell)
- [x] When a variable (let's say `a`) is detected as being a string, for instance, autocompleting `a:` gives nothing, but `a.` lists all applicable string methods (with a string argument as first parameter). This should be the reverse: propose autocompletions on `a:` and not `a.`, and remove the first 's' argument as it is passed implicitely with the colon call.
- [x] Type info doesn't fully propagate, apparently. For instance, if function `a` returns a string, and `b` returns `a()`, then if `c = b()`, `c` won't be automatically recognized as a string.
- [x] Typo: it's "Tail call" not "Trail call".

### Modifications:
- [x] `private` support in `@field`. Which would autocomplete inside the class, but not anywhere else
- [ ] support for multiple inheritance in `@class`. Separated by commas after the `:`?
- [x] Improve the stdlib documentation by writing the parameters etc. in the emmylua doc format (with @return, type hinting, etc.)
- [x] Multiple return values annotation support for `@return`. Separated by commas?
- [x] Table of type support. For instance: `Vehicle[]` would be for a table of Vehicle instances. Useful for `pairs()` where the variables would get auto-typed as Vehicle.
- [x] Alt-Enter support on standalone function names, not only on table methods or function arguments. Right now we have to type `--- @return ...` manually.
- [x] Support backticks (`` ` ``) in comments/documentation to make it clear it's a piece of code or code reference.

### New:
- [x] Semantic highlighting support. See [this video](https://www.youtube.com/watch?v=8WRH59PQ5Dk) by JetBrains
- [x] metamethods name autocompletion (`__index`, `__tostring`, etc. The standard ones)
- [x] Propose to refactor things like `string.find(str, pattern)` into `str:find(pattern)`
- [x] Custom class constructor hint support (maybe `@constructor`?).
The class system I'm using is like: `function MyClass:new(arg1, arg2...)` (not `init`) called implicitely by the MyClass table `__call`, so it'd be helpful if `local test = MyClass("hello", 42)` would be recognized as calling the constructor, thus proposing parameters autocompletion etc.
- [x] [LuaCheck](https://github.com/mpeterv/luacheck) static analysis support (parsing its output to add inline annotations, for instance)
- [x] More refactoring options like "Introduce variable" (like Sylvanaar's in [this video](http://www.screencast.com/t/JoeypQp4A9WS)), methods, etc.
- [x] More code style options (about indenting, especially)
- [x] English documentation too :D

Edit :
- _Custom postfix completions_ isn't possible until Intellij supports it, see https://youtrack.jetbrains.com/issue/IDEA-122443.

Also, regarding the plugin itself, you should add support for automatically report crashes to you (bug tracker in JetBrains I think?). Sylvanaar's plugin (and others) are able to do that, so they gather user-reported bugs automatically (they just have to click a button to send a report when something goes wrong, and you get the backtrace)

**Comment by tangzx** [comment]
Thanks for your suggestions and bugs reporting. With typo and documentation I want to say : Sorry for my poor english..., documentation may be comes late
Some of those bugs/suggestions already in my plans.

**Comment by adriweb** [comment]
No problem, thanks and good luck :)

**Comment by adriweb** [comment]
Added:

- [ ] Table of type support. For instance: `Vehicle[]` would be for a table of Vehicle instances. Useful for `pairs()` where the variables would get auto-typed as Vehicle.

**Comment by tangzx** [comment]
Full useage of `@return` annotation is : `---@return MyType1[|MyType2]`,  Separated by `|`

**Comment by tangzx** [comment]
About multiple inheritance please see this issue #11

**Comment by adriweb** [comment]
For the return values, I was talking about multiple return values support, not mixed type support. For instance :
```lua
---@param a number
---@return number, number
function foo2(a)
  return a-1, a+1
end
```

Regarding multiple inheritances, it can be bad sometimes, but there are good use cases as well :)
But yes, having interfaces support (in the class system I'm using I have classes, singletons, multiple inheritances, and interfaces)

**Comment by tangzx** [comment]
oh, that's my mistake. useage shoud be like this
```lua
---@param a number
---@return number|string, number|string|table
function foo2(a)
  return a-1, a+1
end
```
but it doesn't work, seems like a bug, let me fix

**Comment by adriweb** [comment]
oh okay thanks :)
