### ISSUE TITLE
Cross file variable/class/module lookup & auto complete not working

### ISSUE THREAD

**Issue by Baertram** [EmmyLua/IntelliJ-EmmyLua#264]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | IC2019.1
 EmmyLua version | v1.2.10
 OS                        | Windows 10

I'm using EmmyLua in IntelliJ IDEA for the online RPG Elder Scrolls Online. I've parsaed the API files and build some API functions, global variables and other "classes" etc. to be able to lookup the functions and variables (CTRL+left lick) and use the CTRL+SPACE auto complete fucntions of IntelliJ IDEA.

The complete package of files: 
[eso-api-lua-intellij-baertram_API100028.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/3416845/eso-api-lua-intellij-baertram_API100028.zip)
-> See attachment

You must extract it and then add it to your EmmyLUA project's structure.

What are the steps to reproduce this issue?

In file ESO-api.classes.lua you'll find e.g. the following functions:
--- @param eventName number
--- @param millisecondsToRepeatCallbackFunctionAfter number (milliseconds)
--- @param callbackFunction function
--- @return isEventRegisteredNow bool
function EVENT_MANAGER:RegisterForUpdate(eventName, millisecondsToRepeatCallbackFunctionAfter, callbackFunction) end

--- @param eventName number
--- @return void
function EVENT_MANAGER:UnregisterForUpdate(eventName) end

------------------------------------------------
1. Type EVENT_MA
2. Press CTRL+SPACE to see auto complete popup
3. There is no EVENET_MANAGER or functions like EVENT_MANAGER:RegisterForUpdate shown

------------------------------------------------
or with file ESO-api.globals.lua there is defined the global variable
ABILITY_TYPE_AREAEFFECT = "22"

1. Type ABILITY_ 
2. Press CTRL+SPACE to see the auto complete popup
3. No entries are shown but there should be several entries from the globals api file, starting with ABILITY
------------------------------------------------
or with file ESO-api.globals.lua there is defined the global variable
1. Type ABILITY_TYPE_AREAEFFECT 
2. Move your mouse above the variable ABILITY_TYPE_AREAEFFECT: It's not showing it's value "22"
3. Press CTRL+LEFT MOUSE on this variable ABILITY_TYPE_AREAEFFECT 
4. It's not jumping to the file ESO-api.globals.lua

What happens?（出现什么问题？）
-------------
-No auto complete entries are shown for classes/variables from other project files
-No CTRL+LEFT MOUSE jump to declaration in other files works

What were you expecting to happen?（期望？）
-----------------------------------------
-Jumping to variable declaration in other project files should work via CTRL+LEFT mouse, but it isn't

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
No logs or errors

Any other comments?（其它说明）
------------------------
It's working if you declare the variables and classes in the same lua file where you try to do the auto complete via CTRL+SPACE or jump to via CTRL+LEFT MOUSE. But not if it's made in another file.
[eso-api-lua-intellij-baertram_API100028.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/3416855/eso-api-lua-intellij-baertram_API100028.zip)

**Comment by tangzx** [comment]
> 1. Type EVENT_MA
> 2. Press CTRL+SPACE to see auto complete popup
> 3. There is no EVENET_MANAGER or functions like EVENT_MANAGER:RegisterForUpdate shown

No definition for global variable `EVENT_MANAGER` found, Maybe you forgot the definition like `EVENT_MANAGER = {}`.

> 1. Type ABILITY_
> 2. Press CTRL+SPACE to see the auto complete popup
> 3. No entries are shown but there should be several entries from the globals api file, starting with ABILITY

It's OK in my case:
![image](https://user-images.githubusercontent.com/3354360/61636332-faefce00-acc7-11e9-9f00-f32cd53a912d.png)

**Comment by Baertram** [comment]
Thanks for the quick answer.
I'll test to define the variable EVENT_MANAGER = {}. The API doc I' generated the lua files from does not have the entries "explicit" so it would be hard to generate them for each table. I thought that the lua plugins (silvanaar was able to in the past but it isn't working anymore) could recognize the EVENET_MANAGER stuff itsself if you define a . or : function behind/below it.

Any idea why the 3rd mentioned problem is not working?

Type ABILITY_TYPE_AREAEFFECT
Move your mouse above the variable ABILITY_TYPE_AREAEFFECT: It's not showing it's value "22"
Press CTRL+LEFT MOUSE on this variable ABILITY_TYPE_AREAEFFECT
It's not jumping to the file ESO-api.globals.lua

**Comment by Baertram** [comment]
Update:
I've installed IntelliJ IDEA C19.1 on another PC and a fresh EmmyLua plugin.
CTRL+LEFT MOUSE CLICK jumps to the definition of the variables now.
This is weird :-(
Any idea if there are settings which disable this? It's not working on my main PC anymore but on the other one it does...

**Comment by tangzx** [comment]
I have no idea... , you can try `File | Invalidate Caches / Restart`
