### ISSUE TITLE
emmydebug 调式时，如果遇到string.split函数就无法单步调式

### ISSUE THREAD

**Issue by wwwfox** [EmmyLua/IntelliJ-EmmyLua#266]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [IC2019.1.3]
 EmmyLua version | [1.3.0-eap-64]
 OS                        | [Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
使用的是cocos lua 3.12
local strs = string.split("panel_detail,Task_detail,panel_title,ListView_task",",")
What happens?（出现什么问题？）
-------------
只要SetpOver时遇到string.split，或者函数中有调用string.split
就会退出调试
What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by tangzx** [comment]
请提供一下split的实现，以及说明一下是哪个调试？

**Comment by wwwfox** [comment]
function string.split(input, delimiter)
    input = tostring(input)
    delimiter = tostring(delimiter)
    if (delimiter=='') then return false end
    local pos,arr = 0, {}
    -- for each divider found
    for st,sp in function() return string.find(input, delimiter, pos, true) end do
        table.insert(arr, string.sub(input, pos, st - 1))
        pos = sp + 1
    end
    table.insert(arr, string.sub(input, pos))
    return arr
end
用的是新版调试

**Comment by tangzx** [comment]
用群里最新上传的版本
