### ISSUE TITLE
Run console does not support ANSI sequences (colors etc.)

### ISSUE THREAD

**Issue by adriweb** [EmmyLua/IntelliJ-EmmyLua#267]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2019.2
 EmmyLua version | 1.2.10
 OS                        | Linux

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Run a lua script that outputs text with ANSI sequences (like colors)

What happens?（出现什么问题？）
-------------
… Text is output raw (`[32mfoobar` for instance instead of having the word `foobar` in green)

What were you expecting to happen?（期望？）
-----------------------------------------
… Text should output formatted according to the ANSI escapes

Proposal:
---------
Like https://github.com/KronicDeth/intellij-elixir/pull/863/files, replace `OSProcessHandler` occurrences by `ColoredProcessHandler`. Maybe it is enough ?

**Comment by tangzx** [comment]
Fixed, but I don't how to test, Could you test it with this build?
https://ci.appveyor.com/project/EmmyLua/intellij-emmylua-7n83m/build/artifacts

**Comment by adriweb** [comment]
Yes, it works, thanks!
