### ISSUE TITLE
从Lua调试切换为C#调试时,Unity会报错~

### ISSUE THREAD

**Issue by SPingels** [EmmyLua/IntelliJ-EmmyLua#275]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [RD2019.2.2]
 EmmyLua version | [ v1.3.0.99]
 OS                        | [Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 设置相关的Lua调试环境.
![Snipaste_2019-09-12_17-30-04](https://user-images.githubusercontent.com/11756371/64772991-28e4e680-d584-11e9-9815-45287d27d239.png)

2. 在程序进入Lua环境的第一个文件中添加,如下代码.
![Snipaste_2019-09-12_17-30-47](https://user-images.githubusercontent.com/11756371/64773167-76f9ea00-d584-11e9-8010-11fdbd510f9f.png)

3. 在调试Lua源文件结束之后,将Debugger模式切换为Attach to Unity Editor.准备调试C#源文件.
![Snipaste_2019-09-12_17-31-30](https://user-images.githubusercontent.com/11756371/64773293-af99c380-d584-11e9-8f60-dbaeb8b5ebb5.png)

What happens?（出现什么问题？）
-------------
如上:当我准备调试C#端的源文件时.Unity会报如下异常.
![Snipaste_2019-09-12_17-32-04](https://user-images.githubusercontent.com/11756371/64773412-ea9bf700-d584-11e9-87f6-cf6b6b8d289f.png)

What were you expecting to happen?（期望？）
-----------------------------------------
当然,我知道在Debugger模式切换为Attach to Unity Editor时,将下面的代码注释掉Unity就不会报异常.
![Snipaste_2019-09-12_17-30-47](https://user-images.githubusercontent.com/11756371/64773167-76f9ea00-d584-11e9-8010-11fdbd510f9f.png)
但是个人觉得这样操作极奇不方便,希望作者能够将这个问题优化一下~

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
详细的log日志:
LuaException: [Emmy]connection refused
stack traceback:
	[builtin#19]: at 0x6142c850
	[C]: at 0x7fff4bd4a660
	[C]: in function 'tcpConnect'
	Main/GameRoot:16: in main chunk
LuaInterface.LuaState:LuaLoadBuffer(Byte[], String) (at Assets/ToLua/Core/LuaState.cs:2187)
LuaInterface.LuaState:DoFile(String) (at Assets/ToLua/Core/LuaState.cs:642)
LuaFramework.LuaManager:StartMain() (at Assets/Scripts/Manager/LuaManager.cs:55)
LuaFramework.LuaManager:InitStart() (at Assets/Scripts/Manager/LuaManager.cs:32)
LuaFramework.GameManager:OnInitialize() (at Assets/Scripts/Manager/GameManager.cs:233)
LuaFramework.GameManager:<OnResourceInited>m__0() (at Assets/Scripts/Manager/GameManager.cs:224)
LuaFramework.<Initialize>c__AnonStorey2:<>m__0(Object[]) (at Assets/Scripts/Manager/ResourceManager.cs:45)
LuaFramework.<OnLoadAsset>c__Iterator0`1:MoveNext() (at Assets/Scripts/Manager/ResourceManager.cs:147)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Any other comments?（其它说明）
------------------------
框架是使用的[LuaFramework](https://github.com/jarjin/LuaFramework_UGUI)

**Comment by SPingels** [comment]
按照上面的方式修改了,但是本机拒绝访问.
![Snipaste_2019-09-16_09-27-42](https://user-images.githubusercontent.com/11756371/64930572-920a7980-d864-11e9-8348-bc8f959c09d5.png)
这是错误日志.
![Snipaste_2019-09-16_09-28-03](https://user-images.githubusercontent.com/11756371/64930577-a0f12c00-d864-11e9-89bb-9295212a8aa6.png)
查看过端口占用问题,也没有发现端口被占用,暂时还不清楚是什么原因导致的.

**Comment by tangzx** [comment]
按照这种方式要**先启动Unity，再调试**，你是这样做的吗？如果是换个端口试试，并且注意Unity启动时有没有报端口被占用的错误提示

**Comment by SPingels** [comment]
如果我这边需要先进入调试状态,在启动Unity播放,就需要用dbg.tcpConnect(...)?

**Comment by tangzx** [comment]
可以这么理解。
调试器和IDE通过socket连接，所以要有一方当server端，当server的那个先启动

**Comment by SPingels** [comment]
虽然这样这个问题就回到最开始我提出的问题了,但是还是非常感谢~

**Comment by pig3800** [comment]
可以试试Lua得异常处理
