### ISSUE TITLE
Local functions highlighted as up-value

### ISSUE THREAD

**Issue by flaghacker** [EmmyLua/IntelliJ-EmmyLua#277]
name   |   version  
----------|----------
 IDEA version         | InteliJ 2019.2
 EmmyLua version | 1.3.0.99-IDEA182
 OS                        | Windows 10

In the following code:
```lua
local function foo()
    print("Hello World!")
end

local function bar()
    foo()
end
```

The call to `foo` is highlighted as an up-value:

![image](https://user-images.githubusercontent.com/7887115/64911728-bad82500-d725-11e9-8668-bc461289cbfa.png)

It should be highlighted as a local function instead. This issue is similar to #126.

**Comment by tangzx** [comment]
foo plays two roles: up-value & local function.
`local function foo() end` equals `local foo = function() end`

**Comment by adriweb** [comment]
> `local function foo() end` equals `local foo = function() end`

_Technically_, not 100% equal, because `local function foo() ... end` allows `foo` to be used inside its own definition, but `local foo = function() ... end` does not.

**Comment by flaghacker** [comment]
Is my understanding wrong? Is the call to `foo` from `bar` actually using it as an upvalue?
