### ISSUE TITLE
goto is marked as "invalid syntax"

### ISSUE THREAD

**Issue by olegrok** [EmmyLua/IntelliJ-EmmyLua#282]
Last available in JetBrains repo version:

![image](https://user-images.githubusercontent.com/8830475/66761227-3e636e00-eeac-11e9-86b6-e9ac7fd07b41.png)

**Comment by adriweb** [comment]
Works fine for me, maybe you need to set/use an SDK with a lua version >= 5.2 (or luajit) ?

**Comment by tangzx** [comment]
Change `Language level` to `Lua 5.2+` (File | Settings | Languages & Frameworks | EmmyLua)

**Comment by olegrok** [comment]
Ok, thanks

It works

@tangzx, please add LuaJIT to versions list
