### ISSUE TITLE
Incompatible with IntelliJ IDEA 2019.3 EAP

### ISSUE THREAD

**Issue by doublefx** [EmmyLua/IntelliJ-EmmyLua#284]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | 2019.3 EAP
 EmmyLua version | 1.3.0.99-IDEA182
 OS                        | Windows 10

What are the steps to reproduce this issue?
------------------------------------------------
1. Add the plugin

What happens?
-------------
Incompatible with the current IntelliJ IDEA version.

What were you expecting to happen?
-----------------------------------------
The plugin should be compatible.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
![image](https://user-images.githubusercontent.com/1222171/66913108-e5125080-f00b-11e9-9972-844e5624e319.png)

Any other comments?
------------------------
Windows 10 antivirus is reporting emmy.tool.exe as a trojan: Trojan:Win32/Tiggre!plock
file: C:\Users\doublefx\.IntelliJIdea2019.3\config\plugins\EmmyLua\classes\debugger\windows\x86\emmy.tool.exe

**Comment by tangzx** [comment]
Please try the latest build -> https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/artifacts

**Comment by doublefx** [comment]
It looks all good, many thanks Tangzx, do you want me to close the issue or you prefer to commit the change first?
