### ISSUE TITLE
Windows 10 antivirus is reporting emmy.tool.exe as Trojan:Win32/Tiggre!plock

### ISSUE THREAD

**Issue by doublefx** [EmmyLua/IntelliJ-EmmyLua#285]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2019.3 EAP
 EmmyLua version | 1.3.0.99-IDEA182
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Add the plugin
2. Run the Windows Antivirus

What happens?（出现什么问题？）
-------------
file: C:\Users\doublefx\.IntelliJIdea2019.3\config\plugins\EmmyLua\classes\debugger\windows\x86\emmy.tool.exe
Trojan:Win32/Tiggre!plock

What were you expecting to happen?（期望？）
-----------------------------------------
To be not a virus

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
![image](https://user-images.githubusercontent.com/1222171/66914541-e98c3880-f00e-11e9-958e-2d808c9587f5.png)

Any other comments?（其它说明）
------------------------
Reported as other comment in https://github.com/EmmyLua/IntelliJ-EmmyLua/issues/284

**Comment by tangzx** [comment]
see #263

**Comment by doublefx** [comment]
Duplicated with https://github.com/EmmyLua/IntelliJ-EmmyLua/issues/263
