### ISSUE TITLE
---@type fun 注解不能工作

### ISSUE THREAD

**Issue by zzx-cc** [EmmyLua/IntelliJ-EmmyLua#286]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2019.2.1 ultimate
 EmmyLua version | 1.3.0.99-IDEA182
 OS                        | win10

按以下方式可以工作，self, cfgNode都可以在函数内部获得提示
---@param self Graph.Graph
---@param cfgNode cfg.graph.Node
---@return Graph.GraphNode
local function CreateNode(self,cfgNode)

但如下方式，使用fun注解时，self cfgNode都没有提示
---@type fun(self:Graph.Graph):Graph.Graph
local function CreateNode(self,cfgNode)

**Comment by tangzx** [comment]
函数对象不能使用`---@type`，关于注解使用点击[这里](https://emmylua.github.io/zh_CN/annotation.html)

**Comment by zzx-cc** [comment]
感谢，了解了。按照这个约定，改成这种定义形式就符合了
---@type fun(self:Graph.Graph):Graph.Graph
local CreateNode =function (self,cfgNode）

**Comment by tangzx** [comment]
对函数而言不建议用`local foo = function() end` 的方式声名，直接 `local function foo()end`
你想要什么效果？cfgNode是可选参数？如果是这样用`@overload`
```lua
---@overload fun(self:Graph.Graph):Graph.Graph
---@param cfgNode Graph.Node
---@return Graph.Graph
local function CreateNode(self,cfgNode)
end
```
