### ISSUE TITLE
不能正确地跳转到函数定义

### ISSUE THREAD

**Issue by czy211** [EmmyLua/IntelliJ-EmmyLua#297]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IU2019.2.4
 EmmyLua version | v1.3.0
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
---@class A
A = {}

---@class B:A
B = {}

function A:func() end

---@type B
local b = CreateB()
b:func()

What happens?（出现什么问题？）
-------------
func()和A不在同一文件时b:func()无法跳转到定义func()的地方

What were you expecting to happen?（期望？）
-----------------------------------------
可以跳转到定义func()的地方

Any other comments?（其它说明）
------------------------
func()和A在同一文件时可以正常跳转
在VSCode上即使不在同一文件时也可以正常跳转

**Comment by tangzx** [comment]
没重现，请给个能重现的例子工程

**Comment by czy211** [comment]
test1.lua
```
---@class A
A = {}
---@class B:A
B  = {}

function A:test1() end

---@type B
local b = {}
b:test1()
b:test2()
```
test2.lua
```
function A:test2() end

---@type B
local b = {}
b:test1()
b:test2()
```
Ctrl 点击 test1 函数会跳转到 test1.lua 中定义函数的地方，但是 Ctrl 点击 test2 函数没有跳转到 test2.lua 文件
[test.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/5331938/test.zip)

**Comment by tangzx** [comment]
测试没有问题，用比较新的版本试试

**Comment by xJayLee** [comment]
Lua目录 Start Index
