### ISSUE TITLE
IntelliJ IDEA 2019.3 is incompatible with V1.3.0

### ISSUE THREAD

**Issue by shuijingy** [EmmyLua/IntelliJ-EmmyLua#307]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. 2019.3]
 EmmyLua version | [e.g. v1.3.0]
 OS                        | [e.g. OSX 10.13.4, Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. After up IDEA to 2019.3, errors occur.

What happens?（出现什么问题？）
-------------
Incompatible issue cause plugin disabled

What were you expecting to happen?（期望？）
-----------------------------------------
Support the latest IDEA

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
N/A

Any other comments?（其它说明）
------------------------
N/A

**Comment by CppCXY** [comment]
Download the latest version from emmylua ci

**Comment by netroby** [comment]
https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/artifacts
download latest from this works. 
and wish you upgrade the plugin into intellij emmylua repository.

**Comment by dselans** [comment]
Note: if you are primarily working with openresty - stay on Intellij 2019.2 (Openresty plugin requires Lua plugin which also doesn't work in IntelliJ 2019.3).

**Comment by knoxfighter** [comment]
It would be great, to have the plugin also updated in the jetbrains marketplace, so depending plugins, can also update to the new version.

**Comment by tangzx** [comment]
v1.3.1 is pending JetBrains approval
https://plugins.jetbrains.com/plugin/9768-emmylua
