### ISSUE TITLE
EmmyLua不支持最新版PyCharm2019.3

### ISSUE THREAD

**Issue by askiter** [EmmyLua/IntelliJ-EmmyLua#311]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [PyCharm 2019,3]
 EmmyLua version | [v1.3.0.99-IDEA182]
 OS                        | [Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. …
2. …
3. …

What happens?（出现什么问题？）
-------------
Plugin Error: Plugin "EmmyLua" is incompatible (target build range is 182 to 192.*).

What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by nitramwin** [comment]
Please see the following answer: https://github.com/EmmyLua/IntelliJ-EmmyLua/issues/312#issuecomment-563336684

**Comment by tangzx** [comment]
v1.3.1 is pending JetBrains approval
https://plugins.jetbrains.com/plugin/9768-emmylua
