### ISSUE TITLE
Key的类型提示有问题

### ISSUE THREAD

**Issue by hugeforest** [EmmyLua/IntelliJ-EmmyLua#313]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2019.2
 EmmyLua version | 1.3.0.131
 OS                        | Windows 10

bug，key的类型提示有问题
```lua
---@type table<number, table<number, number>>
local x = {}
for k :string, v :table<number, number> in pairs(x) do
	for k2 :string, v2 :number in pairs(v) do

	end
end
```
其中，k k2应该是number类型吧，不是string

**Comment by tangzx** [comment]
估计版本较旧，请尝试最新版
