### ISSUE TITLE
Rider 上使用插件 --{{{ --}}} 代码无法缩起

### ISSUE THREAD

**Issue by yangruihan** [EmmyLua/IntelliJ-EmmyLua#315]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | Rider 2019.3 Build #RD-193.5233.171
 EmmyLua version | 1.3.0-IDEA182
 OS                        | macOS 10.14.4

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
![image](https://user-images.githubusercontent.com/7806458/71055113-6c587d80-218f-11ea-9cbb-5d5176896ac0.png)

What happens?（出现什么问题？）
-------------
`--{{{` `--}}}`里的代码无法缩起

What were you expecting to happen?（期望？）
-----------------------------------------
`--{{{` `--}}}`里的代码可以缩起

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
无

Any other comments?（其它说明）
------------------------
无

**Comment by tangzx** [comment]
使用群里最新版本 1.3.1的
