### ISSUE TITLE
IDEA升级到2019.3以后，代码折叠功能失效

### ISSUE THREAD

**Issue by hugeforest** [EmmyLua/IntelliJ-EmmyLua#316]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2019.3]
 EmmyLua version | 1.3.0.135]
 OS                        |  Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
例如：
--{{{ region

--}}}

if true then

else

end
这些前面的+ -都消失了，不能折叠代码了

What happens?（出现什么问题？）
-------------
…

What were you expecting to happen?（期望？）
-----------------------------------------
请尽快修复，谢谢

**Comment by tangzx** [comment]
使用群里最新版本试试 1.3.1的
