### ISSUE TITLE
Adding additional comment characters

### ISSUE THREAD

**Issue by Erasio** [EmmyLua/IntelliJ-EmmyLua#319]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | #RD-191.7141.460
 EmmyLua version | v1.3.0.99
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Implement a preprocessor for the lua code with custom, special characters

What happens?（出现什么问题？）
-------------
All functionality of EmmyLua breaks down due to the file being formatted "incorrectly". 

What were you expecting to happen?（期望？）
-----------------------------------------
Exactly what happens.

Any other comments?（其它说明）
------------------------
This is not as much an bug or issue but rather a feature request / question for how to implement it myself. 
For our project we are preprocessing pretty much all of our lua files to introduce functionality such as namespaces and standard preprocessor utils (e.g. "#IF DEBUG" <code> "#ENDIF") 

Adding full support for something like this would be silly but I'm looking for a way to add two more character sequences to be recognized as comments. Ignoring these custom tools while allowing the rest of the code to be treated as usual by EmmyLua.

I've searched through the code already but due to never having worked with IntelliJ plugins or Kotil for that matter it's challenging to find the parsing location.
Any help about where I can find the comment parsing or how I can ignore lines starting with certain character sequences (single line only) would be incredibly helpful!

Thank you so much for all your work. It's been a huge help!

**Comment by tangzx** [comment]
So what is it looks like?
```lua
#IF DEBUG
function debug()
    -- debug code goes here
end
#ENDIF
```

**Comment by Erasio** [comment]
An example would be:

```lua
#namespace "Lib.Math"

#if DEBUG then
    function myFunc()
        &Log("myFunc in debug mode")
    end
#else 
    function myFunc()
        &Warning("myFunc in standalone mode")
    end
#end
```

**Comment by adriweb** [comment]
This feature should probably be behind a configuration flag somewhere in the settings, and not enabled by default.
Indeed this is not a core language feature and might only be useful for IDE purposes - any actual lua files meant to be run by a lua interpreter wouldn't be parsed successfully with this.
