### ISSUE TITLE
A question about standalone documentation generation.

### ISSUE THREAD

**Issue by winterwolf** [EmmyLua/IntelliJ-EmmyLua#335]
As far as I understand, EmmyLua is intended only to provide smart hints in IDE, but it is not possible to generate standalone HTML-documentation on its basis?

If so, then please explain why you came up with your syntax instead of using already existing [LDoc](https://stevedonovan.github.io/ldoc/manual/doc.md.html)?

**Comment by Benjamin-Dobell** [comment]
@winterwolf I'm not involved with EmmyLua project, but have done a lot of work on EmmyLua itself (massive pull request incoming shortly). I can't speak as to why the original devs made their decision, however here's my take...

LDoc makes it extremely difficult to document complex types:

**EmmyLua**:
```lua
@param key string @Key for which to look-up related strings
@return string[] @Related strings
function lookup(key)
end
```

**LDoc**:
```lua
@param key A string key for which to look-up related strings
@return a table (array) of related strings
function lookup(key)
end
```

LDoc is problematic as there's no sane way to extend this syntax to formally document the types type. LDoc's `description` is expected to be an arbitrary string, there's nowhere to insert a type. Even if you were to _informally_ try something like:

**EmmyLua / LDoc Hybrid Hypothetical**

First word of the description is _informally_ the type:

```lua
@param key string Key for which to look-up related strings
@return string[] Related strings
function lookup(key)
end
```

Great, seemingly works. Okay, but what if we want to document we may return nil. Also, we can take a table with a key "field" that's a string as an alternative to just a string key: 

```lua
@param key string | {key: string} Key for which to look-up related strings
@return string[] | nil Related strings
function lookup(key)
end
```

Uh oh, this is getting a lot harder to read, and to parse. EmmyLua by contrast just looks like:

```lua
@param key string | {key: string} @Key for which to look-up related strings
@return string[] | nil @Related strings
function lookup(key)
end
```

It's a small change, but it makes reading and parsing a lot simpler.

I've seen people replace `@param` with the type e.g. `@param key string` becomes `@string key`, however that also falls down real fast with complex types (unions etc.) 

_Basically_, LDoc wasn't designed to _formally_ document types. It's _really_ bad at it. EmmyLua is much more flexible and does much more. It also gives the EmmyLua devs more freedom to implement a _proper_ solution for documenting types (there are way more advanced things you can do than what's above), without trying to remain inter-operable with a legacy system.

That said... should there be a way to generate documentation for EmmyDoc?

Sure, absolutely, someone just needs to write it!
