### ISSUE TITLE
Crashes while writing JS Code inside big string

### ISSUE THREAD

**Issue by SamHoque** [EmmyLua/IntelliJ-EmmyLua#339]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [2019.3.2]
 EmmyLua version | [v1.3.2.142]
 OS                        | [Windows 10 LTSC]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Make a long string
2. Write some JS code
3. Profit

What happens?（出现什么问题？）

It tries to suggest you auto complete, but it crashes intelliJ
https://lynxclient.com/u/Vv7zxCOR.png

What were you expecting to happen?（期望？）
Nothing, do not suggest code completes.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
Nope

**Comment by tangzx** [comment]
already solved
