### ISSUE TITLE
Not Compatible with 2020.1 EAP

### ISSUE THREAD

**Issue by Mheetu** [EmmyLua/IntelliJ-EmmyLua#340]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2020.1 EAP
 EmmyLua version | v1.2.6
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Attempt to install

What happens?（出现什么问题？）
-------------
An error occurs:
> Plugin 'EmmyLua' is incompatible with this installation

What were you expecting to happen?（期望？）
-----------------------------------------
For the plugin to be installed

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
None.

Any other comments?（其它说明）
------------------------
Plugin is not built to be compatible with 2020.1 (201.6487.11-EAP-SNAPSHOT).

I attempted to update the package myself but there were compile errors. Unfortunately, I have no experience with developing in Kotlin or on the IntelliJ platform.

**Comment by dannybloe** [comment]
Can you please make a release that works with WebStorm 2020.1?

**Comment by Mheetu** [comment]
Here's a build... until the maintainer gets around to creating a release...

[IntelliJ-EmmyLua-1.3.2-IDEA201.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/4444537/IntelliJ-EmmyLua-1.3.2-IDEA201.zip)

**Comment by dannybloe** [comment]
Thank you!!

**Comment by DorkmasterFlek** [comment]
This is no longer an early access build.  2020.1 has been released and this plugin no longer works!

**Comment by Mheetu** [comment]
@DorkmasterFlek, it should work with all `201.*` releases... I just updated IntelliJ to 2020.1 and was able to install it without any issues.

**Comment by DorkmasterFlek** [comment]
@Mheetu I'm using WebStorm 2020.1 and it says the plugin is incompatible with the current version after updating.  I uninstalled it to try a fresh install, and now I cannot even find it in the marketplace presumably because it's not compatible.

**Comment by Mheetu** [comment]
Yea, they've not made a release for anything 2020 yet... the zip I uploaded should work until then though.

Glad you got it working. 👍🏼

**Comment by tangzx** [comment]
v1.3.3 is pending JetBrains approval
https://plugins.jetbrains.com/plugin/9768-emmylua
> The request will be processed within two business days.

**Comment by DorkmasterFlek** [comment]
Excellent, thank you!

**Comment by Mheetu** [comment]
It appears JetBrains has approved version 1.3.3 which is compatible with IDEA201.

Closing the issue.
