### ISSUE TITLE
EmmyLua attempts to autocomplete comments

### ISSUE THREAD

**Issue by OutputCoupler** [EmmyLua/IntelliJ-EmmyLua#344]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | Community 2019.2.4]
 EmmyLua version | 1.3.2.142-IDEA182
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Write a comment, especially one containing numbers or special characters

What happens?（出现什么问题？）
-------------
EmmyLua attempts to autocomplete, inserting incorrect characters which must be manually deleted

What were you expecting to happen?（期望？）
-----------------------------------------
EmmyLua should never attempt to automatically complete while typing comments, as comments are usually natural language, not code. Numbers and many special characters like the period and colon are especially problematic as they bring up the autocomplete list with all tokens in scope, which often results in a random token being inserted after these characters.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
No

Any other comments?（其它说明）
------------------------
Keep up the good work, the plugin is great!

**Comment by 133794m3r** [comment]
I wish I knew why it's doing it, as it tries to autocomplete _everything_ in it any keyword will trigger it's autocomplete. i makes it try to insert if and the like.
