### ISSUE TITLE
函数里定义的函数，代码提示项会变成Invalid

### ISSUE THREAD

**Issue by Siwwc** [EmmyLua/IntelliJ-EmmyLua#346]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IC193.6911.18
 EmmyLua version | v1.3.2.142
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
```
local fn = {}

function fn.Fun2()
    fn.Fun1()
end

function fn.Fun1()
    print("Fun1")
end
```
所有东西直接放在最外面，在输入fn.Fun1()时是能正常提示的
```
local function Test()
    local fn = {}

    function fn.Fun2()
        fn.Fun1()
    end

    function fn.Fun1()
        print("Fun1")
    end
end
```
把它们放在一个函数里，这时输入fn.Fun1()提示就会出问题。
首先输入"fn."时提示还是正常的；若再继续输入一个字符，此时的提示看着是正常的，但无法Enter输入提示项；再继续输入字符提示项就会变成Invalid。

What happens?（出现什么问题？）
-------------
函数里定义的函数，代码提示项会变成Invalid

What were you expecting to happen?（期望？）
-----------------------------------------
希望能函数里定义的函数也能正常提示

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
无

Any other comments?（其它说明）
------------------------
无

**Comment by tangzx** [comment]
已解决

**Comment by Siwwc** [comment]
提示项正确，没有变成Invalid了，但按Enter无法自动输入

**Comment by tangzx** [comment]
![AbJRWZ50rA](https://user-images.githubusercontent.com/3354360/95668972-5fd56380-0bad-11eb-9206-593300692219.gif)

怎么重现？

**Comment by Siwwc** [comment]
Idea已升至最新版本2020.2.3
EmmyLua插件版本1.3.4.157-IDEA202
下面是我这边的情况，有提示，但按Enter没有输上去





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EmmyLua/IntelliJ-EmmyLua"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月11日(星期天) 上午10:35
收件人:&nbsp;"EmmyLua/IntelliJ-EmmyLua"<IntelliJ-EmmyLua@noreply.github.com&gt;;
抄送:&nbsp;"triangle"<2821905224@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EmmyLua/IntelliJ-EmmyLua] 函数里定义的函数，代码提示项会变成Invalid (#346)





 

 
怎么重现？
