### ISSUE TITLE
Subclass doesn't inherit fields of parent class

### ISSUE THREAD

**Issue by winterwolf** [EmmyLua/IntelliJ-EmmyLua#354]
```lua
local class = require "middleclass"

---@class TestWindowSize Window size.
---@field w number Window width.
---@field h number Window height.
local TestWindowSize = class("TestWindowSize")

---@class TestWindow:TestWindowSize Window.
---@field flags table Additional options.
---@field scaled TestWindowSize Scaled size.
---@field last TestWindowSize Size before fullscreen.
local TestWindow = TestWindowSize:subclass("TestWindow")

return TestWindow
```

![screenshot-001](https://user-images.githubusercontent.com/42620439/80667701-893f7e80-8aa8-11ea-8887-6600f41f22f7.png)

Why class `TestWindow` doesn't have fields `w` and `h` from `TestWindowSize` ?

**Comment by adriweb** [comment]
Is it any better if you declare those fields as public or at least protected?

**Comment by winterwolf** [comment]
@adriweb I think they're public by default. Yes, it's available. I can add public keyword after each field declaration, but class still doesn't inherit these fields.

**Comment by winterwolf** [comment]
The problem is solved! Inherited fields are not in the class description, but they are in the class instance description.
