### ISSUE TITLE
Adding comment block on empty script causes error

### ISSUE THREAD

**Issue by Gokaic** [EmmyLua/IntelliJ-EmmyLua#357]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version | [e.g. v1.2.5]
 OS                        | [e.g. OSX 10.13.4, Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. start new .lua file
2. add an empty --[[]] comment block with nothing else

What happens?（出现什么问题？）
-------------
won't allow you to type or backspace. delete works, as does typing in overtype mode with insert key. also error at bottom shows expected #! but got --[[

What were you expecting to happen?（期望？）
-----------------------------------------
create a comment block to fill

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
expected #! but got --[[

Any other comments?（其它说明）
------------------------
…

**Comment by winterwolf** [comment]
Today is 2020, bro! Why do you report bugs of 2 years old soft?

I can't reproduce it on EmmyLua 1.3.3 and IDEA2020.1.1

**Comment by Gokaic** [comment]
My bad I went based on google to the wrong github. I'm using the 1.3.3.150

**Comment by winterwolf** [comment]
@Gokaic Oh, yes, you're right! I just copy-pasted the comment and don't get any errors, but when I type it myself, IDE stopped accepting keyboard signals.
