### ISSUE TITLE
Incompatible with IntelliJ IDEA 2020.2 EAP / Build #IU-202.4357.23

### ISSUE THREAD

**Issue by doublefx** [EmmyLua/IntelliJ-EmmyLua#360]
Incompatible with IntelliJ IDEA 2020.2 EAP / Build #IU-202.4357.23

I tried to uninstall / install as I did with some other plugins but I did not work for this one, it does not even appear anymore in the plugin list.

**Comment by brittyazel** [comment]
Agreed. IntelliJ 2020.2 is incompatible from my end as well.
