### ISSUE TITLE
Unable to modify default template

### ISSUE THREAD

**Issue by 133794m3r** [EmmyLua/IntelliJ-EmmyLua#362]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version     |  CL2020.2.1 
 EmmyLua versio n |1.3.3.150-IDEA201 
 OS                        | Parrot GNU/Linux 4.9

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Look through configuration.
2. No option to configure the default template file.
3. Still can't find it.

What happens?（出现什么问题？）
-------------
The default file template for "new lua file" doesn't exist in the settings menu.

What were you expecting to happen?（期望？）
-----------------------------------------
Like the default built-in languages I was expecting to be able to modify the default template to get some boiler-plate stuff out of the way.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
None at this time.

Any other comments?（其它说明）
------------------------
…

**Comment by tangzx** [comment]
see #97
