### ISSUE TITLE
Not compatible with Webstorm 2020.2

### ISSUE THREAD

**Issue by DorkmasterFlek** [EmmyLua/IntelliJ-EmmyLua#367]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | WS-202.6397.88
 EmmyLua version | 1.3.3.150-IDEA201
 OS                        | Windows 10, Ubuntu 20.04

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Try to install EmmyLua from plugin marketplace.

What happens?（出现什么问题？）
-------------
Plugin cannot be installed, it's incompatible with Webstorm 2020.2

What were you expecting to happen?（期望？）
-----------------------------------------
Plugin should be compatible with latest version of Webstorm.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------

Any other comments?（其它说明）
------------------------

**Comment by SvenAugustus** [comment]
2020.2 has released. update is going ?

**Comment by jiaaro** [comment]
Also, it would be nice if emmylua would either assume future releases will also work. Or, perhaps warn users but allow then to accept the risk and continue using emmylua.
