### ISSUE TITLE
Left click on variable does not highlight all occurrences anymore

### ISSUE THREAD

**Issue by Baertram** [EmmyLua/IntelliJ-EmmyLua#376]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Non-Bundled Plugins: com.tang, org.jetbrains.kotlin, training

 EmmyLua version | 1.3.4.157-IDEA202
 OS                        | Windows 10 10.0

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 
e.g. 
local myVar1 = "Hello world"
myVar1 = "New world"

Left click myVar1 variable in your source code. It will not highlight all occurences of that variable anymore!
Only if you press CTRL+left click to find the declaration of that variable at "local myVar1 = "Hellow world" and then left click the "local myVar1" it will highlight all occurrences of the variable.

In the past this also worked if I left clicked just "myVar1" anywhere in my code?

Please re-enable this feature again!

What happens?（出现什么问题？）
-----------------------------------------
No highlight to ALL occurrences of the variable anymore.

What were you expecting to happen?（期望？）
-----------------------------------------
All occurrences of the variable should be highlighted again-

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
Thank you for this plugin!

**Comment by Baertram** [comment]
Here are some screenshots to show what I mean
https://imgur.com/a/Rtj3hY5

**Comment by tangzx** [comment]
please upgrade to 1.3.5
