### ISSUE TITLE
Incompatible with IntelliJ IDEA 2020.3  / Build #IU-203.5981.155

### ISSUE THREAD

**Issue by CrazyPandas** [EmmyLua/IntelliJ-EmmyLua#381]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA 2020.3 (Ultimate Edition)
 EmmyLua version |  [v1.3.4.157-IDEA202]
 OS                        | [Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. update the IDEA to IntelliJ IDEA 2020.3 / Build #IU-203.5981.155

What happens?（出现什么问题？）
-------------
Incompatible

What were you expecting to happen?（期望？）
-----------------------------------------
can use this plugin.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------

none.

Any other comments?（其它说明）
------------------------
hope EmmyLua can update.

**Comment by staudenmayerc** [comment]
Having the same problem, we just introduced EmmyLua into our workflow and now we can't update WebStorm.  We would appreciate a timely fix, if feasible.

**Comment by Abbila** [comment]
I'm having the same problem too，望，组织尽快更新一下。

**Comment by DorkmasterFlek** [comment]
Same issue.  Please update this!  We had the same issue with the 2020.2 update, and the only thing that needed to change was the "untilBuild".  Does this need to be set?  Can we just assume that it will work with future IDE versions unless proven otherwise to avoid this issue on every new major version?

**Comment by rafaskb** [comment]
> 
> 
> Same issue. Please update this! We had the same issue with the 2020.2 update, and the only thing that needed to change was the "untilBuild". Does this need to be set? Can we just assume that it will work with future IDE versions unless proven otherwise to avoid this issue on every new major version?

That would be perfect, EmmyLua is the only reason I hold back from updating IntelliJ, and sometimes this process takes weeks.
I understand the official maintainer is probably busy and doesn't have the time to constantly update the library, so assuming the plugin will work unless proven otherwise would be a great solution in the long run.

**Comment by Yum1x** [comment]
I'm waiting for an update, i've downgraded until this not happens.

**Comment by tangzx** [comment]
Done! Update of EmmyLua 1.3.5.185-IDEA203 is pending JetBrains' approval

https://plugins.jetbrains.com/plugin/9768-emmylua/versions
https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/artifacts

**Comment by rulatir** [comment]
What we need is a simple alternative installation method that can be used to circumvent JetBrains' consistent tardiness with approving plugin updates. Waiting for weeks before somebody at JetBrains sits down on their ass and ticks a checkbox is simply unacceptable.

**Comment by rulatir** [comment]
I tried installing the zip, and now the IDE fails to start:

![obraz](https://user-images.githubusercontent.com/677694/101288377-8652fc00-37f6-11eb-8ff6-99993c0d0bc7.png)

**Comment by tangzx** [comment]
@rulatir did you install another lua plugin（Luanalysis）?

**Comment by CrazyPandas** [comment]
> Done! Update of EmmyLua 1.3.5.185-IDEA203 is pending JetBrains' approval
> 
> https://plugins.jetbrains.com/plugin/9768-emmylua/versions
> https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/artifacts

Good Job. Thanks for your hard work!

**Comment by rulatir** [comment]
> @rulatir did you install another lua plugin（Luanalysis）?

Apparently yes, but it kinda wasn't me, it was PHPStorm. It suggested Luanalysis as an alternative when it couldn't load EmmyLua, and I may have okayed that suggestion too quickly.

I managed to recover the IDE by manually adding `com.tang` to `disabled_plugins.txt`, after which I could use the settings dialog to disable the conflicting plugin and re-enable EmmyLua.
