### ISSUE TITLE
继承的显示有问题

### ISSUE THREAD

**Issue by hugeforest** [EmmyLua/IntelliJ-EmmyLua#388]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 1.3.5.173 - IDEA202 
 EmmyLua version | 2020.2.4 
 OS                        | Windows 10 

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
代码：
---@class class_a
local class_a = {}

function class_a:a1()
end

function class_a:new()
end

---@class class_b:class_a
local class_b = class_a:new()
function class_b:b1()
end

---@class class_c:class_b
local class_c = class_b:new()
function class_c:c1()
end
---@class class_d:class_b
local class_d = class_b:new()

class_c:

What happens?（出现什么问题？）
-------------
其中,b继承a，c继承b，
class_c:后不显示b的相关函数

tip：---@class的c在代码那里是小写，贴到github发表转大写了，我也无奈

**Comment by hugeforest** [comment]
更新到1.3.5.185，bug消除了

**Comment by tangzx** [comment]
好，那这个关闭了
