### ISSUE TITLE
Issue with Android Studio 4.1.1

### ISSUE THREAD

**Issue by Mikhael-Danilov** [EmmyLua/IntelliJ-EmmyLua#394]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | Android Studio 4.1.1 Build #AI-201.8743.12.41.6953283, built on November 5, 2020
 EmmyLua version | 1.3.5.194-IDEA201
 OS                        | Ubuntu 20.04

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Install EmmyLua plugin from settings->plugins->marketplace

What happens?（出现什么问题？）
-------------
IDE becomes unusable: 

- Project files become non-editable (Editor just not start)
- Settings menu become non-accessible through menu or global search

What were you expecting to happen?（期望？）
-----------------------------------------
IDE stays usable

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by tangzx** [comment]
fixed, the new version is pending JetBrains' approval

https://plugins.jetbrains.com/plugin/9768-emmylua/versions
https://ci.appveyor.com/api/buildjobs/jtchljsf6gkolh7y/artifacts/build%2Fdistributions%2FIntelliJ-EmmyLua-1.3.5.198-IDEA201.zip
