### ISSUE TITLE
Autocomplete freezes the IDE when typing in literal strings ([[..]])

### ISSUE THREAD

**Issue by LoganDark** [EmmyLua/IntelliJ-EmmyLua#403]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | WebStorm 2018.2
 EmmyLua version | 1.2.7-IDEA182
 OS                        | macOS 10.14.6

What are the steps to reproduce this issue?
------------------------------------------------
1. Be in a multiline string to some function
2. Type Lua code in a multiline string
3. The autocomplete comes up and then your IDE freezes

Pasting into the string without triggering autocomplete does not freeze.

What happens?
-------------
IDE freezes

What were you expecting to happen?
-----------------------------------------
No freeze

Any logs, error output, etc?
------------------------------
![Recording](https://user-images.githubusercontent.com/4723091/103632263-e7a2e380-4ef8-11eb-917c-1fe3d9992373.gif)

Any other comments?
------------------------
No

**Comment by savinov** [comment]
Same problem.

IntelliJ IDEA 2019.3.1
Build #IU-193.5662.53, built on December 18, 2019
Linux 4.15.0-133-generic

EmmyLua: 1.3.3.150-IDEA182
