### ISSUE TITLE
plugin prevents IDE from working

### ISSUE THREAD

**Issue by mhenselin** [EmmyLua/IntelliJ-EmmyLua#414]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IC-203.7148.57
 EmmyLua version | 1.3.5.194-IDEA203
 OS                        | Linux

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. start IDE

What happens?（出现什么问题？）
------------------------------------------------
IDE does not work properly, scripts are endlessly loading

What were you expecting to happen?（期望？）
-----------------------------------------
IDE running

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
./.

Any other comments?（其它说明）
------------------------
reference to automated bug report:
https://github.com/EmmyLua/EmmyLua-ErrorReport/issues/690

**Comment by Quenix** [comment]
I am experiencing the same problem here. W10, latest intellij version and emmylua. Were you able to fix it?

**Comment by CppCXY** [comment]
uninstall plugin> invalidate caches > wait finish >reinstall emmylua.
