### ISSUE TITLE
最新的开发版idea无法安装emmylua插件

### ISSUE THREAD

**Issue by Johnny-dot** [EmmyLua/IntelliJ-EmmyLua#417]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [Version: 2020.3.3 Build: 203.7717.56 版本:uitimate]
 EmmyLua version | [1.3.6.215-IDEA211]
 OS                        | [18362.1139, Windows 10企业版]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 无法安装
2. 无法安装
3. 无法安装

What happens?（出现什么问题？）
-------------
…

What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by MrShenhongbo** [comment]
Me too.
