### ISSUE TITLE
openresty remote debug 

### ISSUE THREAD

**Issue by yuz10** [EmmyLua/IntelliJ-EmmyLua#42]
when I debug in openresty it always disconnect immediately after connecting.
 

![image](https://user-images.githubusercontent.com/14816818/29876319-fe26412c-8dce-11e7-9f7f-e464fe0aff09.png)

as mentioned in http://notebook.kulchenko.com/zerobrane/debugging-openresty-nginx-lua-scripts-with-zerobrane-studio

> I first tried to use the non-blocking socket API that OpenResty provides, but couldn't get the debugging to work because socket calls that were supposed to be blocking were returning too early, which was breaking the interaction between the debugger in the application and the IDE. Based on advice from Yichun Zhang (agentzh), the maintainer of the OpenResty bundle, I then tried to use the same luasocket library that ZeroBrane Studio is using and got it all working.

is it possible that the luasocket library in luaj engin dont match openresty

**Comment by rulatir** [comment]
I am experiencing the exact same symptom. EmmyLua is now at 1.2.10. I fail to see any real resolution to this issue here. Why is it closed? I would like to request reopening.

**Comment by laozhang007** [comment]
I met the same problem. Emmylua is 1.3.0.99. Hope to slove that.

**Comment by Ostico** [comment]
Same issue with EmmyLua 1.3.2.142-IDEA182

**Comment by omervk** [comment]
Issue persists in 1.3.6.215-IDEA211
