### ISSUE TITLE
无法跳转到require的lua脚本声明

### ISSUE THREAD

**Issue by hafijy** [EmmyLua/IntelliJ-EmmyLua#420]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | #RD-211.6693.105
 EmmyLua version | 1.3.6.215-IDEA211
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. rider从2020.3更新到2021.1
2. 重新下载EmmyLua插件
3. 找到项目中lua脚本里的require的内容，按F12跳转到声明

What happens?（出现什么问题？）
-------------
无法找到要转到的声明

What were you expecting to happen?（期望？）
-----------------------------------------
能够跳转到声明

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
无

Any other comments?（其它说明）
------------------------
在进行更新前的1.3.5.198-IDEA201版本能够正常找到

**Comment by CppCXY** [comment]
rider2021你需要在unity的Editor->project settings->Editor/ Additional extensions to include 里面添加lua
