### ISSUE TITLE
Broke my IntelliJ

### ISSUE THREAD

**Issue by PojahnM** [EmmyLua/IntelliJ-EmmyLua#424]
Installed EmmyLua, restarted IntelliJ and now crashes while I try to open it.

Environment
--------------
   name   |   version  
----------|----------
 IDEA version | 2020.3(Can't check exact version since it's broken!)
 EmmyLua version  | Latest I guess?
 OS | MacOS 11.3 (20E232)

What are the steps to reproduce this issue?
------------------------------------------------
Just install it.

What happens?
-------------
When I try to open IntelliJ, I get an error message and then shuts down.

Any logs, error output, etc?
------------------------------
Pic of stacktrace(couldn't copy the text. Whenever I tried I got a new modal in my face with a NPE error) https://ibb.co/w679QmZ

**Comment by PojahnM** [comment]
Question: How do I manually uninstall it?

**Comment by CppCXY** [comment]
lua plugin conflict.

**Comment by PojahnM** [comment]
I never installed any lua plugin before.

**Comment by Baertram** [comment]
The most recent IntelliJ IDEA Update (cannot see the actual version as it it always freezing before I'm able to do so) is indexing the EmmyLua jar file and is never coming back then:
https://i.imgur.com/IyAL71c.png

The only workaround is to end the task of IntelliJ IDEA via the task manager, and then manually delete the EmmyLua files mentioned at the screenshot so the indexing is not trying to crawl them.

After that you can check the IntelliJ IDEA version: 
IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0

**Comment by cata0309** [comment]
I experience the same issue in GoLand @Baertram. Is there any solution that would leave EmmyLua functional?

**Comment by cata0309** [comment]
Building the plugin from source does not fix the issue

**Comment by Baertram** [comment]
I was somehow able to fix this via uninstalling the plugin, deleting the compete folders of he plugin and caches created in IntelliJ folders (c:\users\...\  e.g. AppData etc. as well), invalidating caches within IntelliJ IDEA UI and restarting it again.
Re-installing the plugin then fixed it for me after 3 tries.
Not sure WHAT exactly was fixing it but since then it did not happen anymore.

But I get several errors now related to EmmyLUA as well if I try to index many files from local subfolders. Everything else though seems to work.

**Comment by cata0309** [comment]
What do you think @tangzx ?

**Comment by jc-dgit** [comment]
Similar happened here on macOS 11.2.3 (Big Sur).  Installed lua and luarocks using Homebrew, then installed the EmmyLua plugin via IDEA Marketplace.

Message at the bottom of the gui shows "Indexing Lua 5...", with the IDEA GUI then locking up completely (beach ball) and never coming back (waited ~20 mins).

Had to kill -9 the main IDEA gui process.  Restarted IDEA, and it immediately starting "Indexing Lua 5" again... locking up the gui.  kill -9 again.

My workaround was to `brew uninstall lua luarocks` (then delete the left over config files), then start IDEA again (with the intention to remove EmmyLua).  But, before I uninstalled the plugin, I decided to try installing Lua and Luarocks a second time.

Now, the weird hang of IDEA isn't happening.  It _seems_ to all be working.  No idea how to investigate the problem though, but this above info might be useful for figuring out something useful. :smile:

**Comment by jc-dgit** [comment]
Looking through the reported issues, both #50 and #414 could be the same as this too.

**Comment by CDAGaming** [comment]
Can affirm the same issue has been occurring on my end.

**Comment by CDAGaming** [comment]
One month later, still occuring on latest version. Definitely won't be recommending this software in the future. Best of luck.

**Comment by adriweb** [comment]
You could always check if the Luanalysis fork has the same issue.

**Comment by jc-dgit** [comment]
> One month later, still occuring on latest version. Definitely won't be recommending this software in the future. Best of luck.

Same.  Just deleted it and moved on personally.

**Comment by frowcallaway** [comment]
It actually breaks all IDEA based IDE's
Pycharm broke when I tried to use the plugin same with Rider, Webstorm and CLion

**Comment by CppCXY** [comment]
> It actually breaks all IDEA based IDE's Pycharm broke when I tried to use the plugin same with Rider, Webstorm and CLion

check first if there are other lua plugins installed, if then only one can be retained.
then rebuild the index: File>Invalid Caches

**Comment by Baertram** [comment]
> It actually breaks all IDEA based IDE's Pycharm broke when I tried to use the plugin same with Rider, Webstorm and CLion

Works fine for me with EmmyLua 1.3.7.2-IDEA222 installed, on IntelliJ IDEA 2022.2.2
As CppCXY said try to remove other LUA plugins and invalidate teh caches and indices.
https://i.imgur.com/cJYJNcU.png

**Comment by andres-canva** [comment]
Idea had a simple syntax highlighting for Lua files before I installed (and uninstalled) the plugin. Any ideas on how to make my IDE go back to normal? I tried invalidating caches already, didn't work.

**Comment by CppCXY** [comment]
Please upgrade to 2022.3 and install emmylua 1.3.8

**Comment by andres-canva** [comment]
Not an option for me to upgrade my IDEA version. I just found the solution:
1. Go to **Settings -> Editor -> File Types**
2. Remove the `*.lua` pattern from the **Text** file type.
