### ISSUE TITLE
How to document named arguments (tables)

### ISSUE THREAD

**Issue by arnoson** [EmmyLua/IntelliJ-EmmyLua#425]
Environment（环境）
--------------
   name   |   version  
----------|----------
 OS                        | Windows 10

Is there any way to document named arguments that I haven't found yet?
What im looking for is to document something like this:

```lua
function test(args)
  print(args.arg1)
  print(args.arg2)
end

test{ arg1 = 10, arg2 = "somestring" }
```

I guess a notation like this would be great:
```lua
---@param args table{ arg1: number, arg2: string }
function test(args) end
```

**Comment by thedaneeffect** [comment]
I suppose you would define a class and give it the fields of the arguments you desire.

```lua
---@class MyArgs
---@field arg1 number
---@field arg2 string

---@param args MyArgs
function test(args)
    print(args.arg1)
    print(args.arg2)
end

test { arg1 = 10, arg2 = "somestring" }
```

**Comment by CppCXY** [comment]
---@param args {arg1: number, arg2: string}
function test(args)
end

**Comment by arnoson** [comment]
Thanks for your quick replies!

I use this [lua plugin for vscode ](https://marketplace.visualstudio.com/items?itemName=sumneko.lua) and both techniques don't seem to work properly, although the plugin uses EmmyLua.

_Here the detailed param Information is not displayed, only the type of the `MyArgs` class:_

![screenshot-1](https://user-images.githubusercontent.com/15122993/117422854-5bddaa00-af20-11eb-9e2c-2c2ef781ede4.png)

_And here the syntax is not recognized:_

![screenshot-2](https://user-images.githubusercontent.com/15122993/117423129-a7905380-af20-11eb-8aad-6fd6799fabab.png)

So I guess the second solution should work great if another part of the plugin wasn't interfering. I will try out to use EmmyLua directly to see if it solves the problem.

**Comment by arnoson** [comment]
sumneko/lua-language-server#511
