### ISSUE TITLE
IDE Freeze on lua 5.2 indexing

### ISSUE THREAD

**Issue by ghost** [EmmyLua/IntelliJ-EmmyLua#429]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IC2021.1
 EmmyLua version | 1.3.6.215-IDEA211
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Install Plugin
2. Start new Project
3. wait for the freeze

What happens?（出现什么问题？）
-------------
After project creating the lua 5.2 indexing frzeeze the IDE

What were you expecting to happen?（期望？）
-----------------------------------------
Loading the project indexing lua 5.2 and run normally

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

thread dump freeze: https://ghostbin.com/paste/cX12G
idea.log: https://ghostbin.com/paste/rvtRC

Any other comments?（其它说明）
------------------------
…

**Comment by raven2cz** [comment]
I have same problem. After installing the plugin to intellij or clion, it freeze whole ide in the indexing process. I have installed 5.2, 5.3 and 5.4 lua in the system.
I'm using linux arch, but it is independent on the OS.

**Comment by CppCXY** [comment]
> I have same problem. After installing the plugin to intellij or clion, it freeze whole ide in the indexing process. I have installed 5.2, 5.3 and 5.4 lua in the system.
> I'm using linux arch, but it is independent on the OS.

maybe use File>Invalid Cache can fix it,

**Comment by raven2cz** [comment]
It is fresh clean installation, just install clion and add emmy - freeze in indexing time.
It is more stations, not just this one. 
Maybe it will be some problem with luacheck. I tried to install luacheck, start ide, kill indexing thread, add path to the luacheck, and restart. Now it seems that it works.

**Comment by opBandwidth** [comment]
> > I have same problem. After installing the plugin to intellij or clion, it freeze whole ide in the indexing process. I have installed 5.2, 5.3 and 5.4 lua in the system.
> > I'm using linux arch, but it is independent on the OS.
> 
> maybe use File>Invalid Cache can fix it,

Thank you, same thing happened to me. This solution fixed it for me :)
(I enabled every Optional Options)

**Comment by xianzheTM** [comment]
I have same prpblem.I have found this problem in several versions in the past.

**Comment by tianshuang** [comment]
> > I have same problem. After installing the plugin to intellij or clion, it freeze whole ide in the indexing process. I have installed 5.2, 5.3 and 5.4 lua in the system.
> > I'm using linux arch, but it is independent on the OS.
> 
> maybe use File>Invalid Cache can fix it,

It worked.

**Comment by Techcable** [comment]
I think PR #511 should fix your issue .

The logs have expired from the pastebin, so it is not possible for me to know for sure.

Please comment if you are still having problems.

**Comment by facboy** [comment]
still freezing for me on 2022.2.4.

**Comment by CppCXY** [comment]
> still freezing for me on 2022.2.4.

only release for 2022.3

**Comment by ilesm** [comment]
Freezing for me also. IntelliJ 2022.1.4 build #IU-221.6008.13, EmmyLua 1.3.6.251-IDEA213. File > Invalidate Caches didn't resolve it. Disabling the EmmyLua plugin resolves it.

**Comment by CppCXY** [comment]
> Freezing for me also. IntelliJ 2022.1.4 build #IU-221.6008.13, EmmyLua 1.3.6.251-IDEA213. File > Invalidate Caches didn't resolve it. Disabling the EmmyLua plugin resolved it.

please upgrade to 2022.3
