### ISSUE TITLE
table内的函数，代码无法自动补全

### ISSUE THREAD

**Issue by icetoggle** [EmmyLua/IntelliJ-EmmyLua#430]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [CL2020.3]
 EmmyLua version | [v1.3.5.194]
 OS                        | [Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. CMD_MAP.test = {
    func = function(self, a, b, c)
          --这里的代码无法正常自动补全
          print("hello world")
    end
}

What happens?（出现什么问题？）
-------------
注释的地方，代码无法自动补全

What were you expecting to happen?（期望？）
-----------------------------------------
table里的函数内，代码也能自动补全

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
https://ghostbin.com/paste/UYAXd
Any other comments?（其它说明）
------------------------
…

**Comment by CppCXY** [comment]
![image](https://user-images.githubusercontent.com/40318218/122496274-0d8ef100-d01e-11eb-9331-ec13568a3883.png)
