### ISSUE TITLE
代码补全提示时，提示项包含了文件中出现的所有字符串

### ISSUE THREAD

**Issue by HaoWShi** [EmmyLua/IntelliJ-EmmyLua#432]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2020.2
 EmmyLua version | v1.3.5
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 定义一个lua文件
2. 触发智能补全操作

What happens?（出现什么问题？）
-------------
代码补全项中，有很多补全项是文件中出现的字符串，不符合语法规范
![image](https://user-images.githubusercontent.com/20752268/123358962-feb8b900-d59e-11eb-90b7-29256438f1eb.png)

What were you expecting to happen?（期望？）
-----------------------------------------
补全提示项中按照当前的语义进行代码补全提示

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
**不太理解当前补全提示项包含所有字符串的含义，所以提出这个issue**

**Comment by tangzx** [comment]
可以在设置里关闭
![image](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/3354360/908c4193-b08c-41a9-9898-d0bafde7a89b)
