### ISSUE TITLE
Conflict with Luanalysis plugin

### ISSUE THREAD

**Issue by solcesby** [EmmyLua/IntelliJ-EmmyLua#434]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA 2021.1.3 (Ultimate Edition) Build #IU-211.7628.21
 EmmyLua version | 1.3.6.215-IDEA211
 OS                        |  Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Install EmmyLua  plugin
2. Install Luanalysis plugin
3. Restart IDE

What happens?（出现什么问题？）
-------------
Critical error at startup

What were you expecting to happen?（期望？）
-----------------------------------------
Normal startup

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
https://ghostbin.com/paste/G9qVl

Any other comments?（其它说明）
------------------------
…

**Comment by CppCXY** [comment]
Idea installing two plug-ins in the same language will cause a crash
