### ISSUE TITLE
Fennel support?

### ISSUE THREAD

**Issue by noncom** [EmmyLua/IntelliJ-EmmyLua#435]
How do you think, is it possible to add Fennel (https://fennel-lang.org/) support to EmmyLua?

Fennel is a small Clojure-inspired LISP dialect for Lua and it would be really awesome to have support for it on the IDEA platform, at least syntax highlighting, even without any advanced features. I think that EmmyLua would be a perfect way to work with both Lua and Fennel.

**Comment by CppCXY** [comment]
No,But you can fork and modify the source code to be compatible with fennel

**Comment by noncom** [comment]
Okay, I'll see if I will be able to get to that!

**Comment by noncom** [comment]
Ok, I've started it and I'm slowly progressing. I only work on it when I have spare time and I have to learn how IDEA language plugins work along the way, so it won't be soon, but hopefully I will manage.

**Comment by noncom** [comment]
Yeah, sorry, I couldn't work on this much more. A whole bunch of other stuff had drawn my attention away. Not sure I'll be able to return to this.
