### ISSUE TITLE
IDEA中无法附加调试器到任意进程

### ISSUE THREAD

**Issue by binhong87** [EmmyLua/IntelliJ-EmmyLua#441]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2021.2.3
 EmmyLua version | 1.3.5
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 点击菜单Run->Attach to Process

What happens?（出现什么问题？）
-------------
附加调试对话框中只有Java Read Only的进程，没有其它进程了（无法附加到运行Lua的应用程序）

What were you expecting to happen?（期望？）
-----------------------------------------
可以列出所有进程，可以附加到任意进程进行调试

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
感谢支持

**Comment by CppCXY** [comment]
附加调试因为报毒从emmylua主体中移除，后形成独立插件emmylua attach，该插件并未上架。可以自己加群下载

**Comment by binhong87** [comment]
> 附加调试因为报毒从emmylua主体中移除，后形成独立插件emmylua attach，该插件并未上架。可以自己加群下载

搞定了，感谢！
