### ISSUE TITLE
EmmyLua 断点调试unity，很容易让unity崩溃

### ISSUE THREAD

**Issue by zengdonghai** [EmmyLua/IntelliJ-EmmyLua#448]
Environment（环境）
--------------
   unity   |   2021.1.25
----------|----------
 IDEA version         | [vscode v1.63.2]
 EmmyLua version | [v0.3.49]
 OS                        | [Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. uinty断点调试，开始结束调试多几次，unity很容易崩溃
2. …
3. …

What happens?（出现什么问题？）
-------------
emmylua_core.dll 容易导致unity崩溃

What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by zengdonghai** [comment]
unity版本是 2021.1.25

**Comment by CppCXY** [comment]
[emmylua-pr-0.3.103.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/7819090/emmylua-pr-0.3.103.zip)
用这个
