### ISSUE TITLE
Intellij crash while loading lua 5.3

### ISSUE THREAD

**Issue by anas-elgarhy** [EmmyLua/IntelliJ-EmmyLua#449]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         |IU 2021.3.1
 EmmyLua version  |V1.3.6.222
 OS                          |Windows 10

What are the steps to reproduce this issue?
------------------------------------------------
1. Open the IDEA

What happens?
-------------
Crash the idea

What were you expecting to happen?
-----------------------------------------
Load the lua 5.3

**Comment by CppCXY** [comment]
Make sure that no other lua plugins are installed.
Uninstall emmylua, rebuild the index(File>Invalid caches), and then install it

**Comment by Anas-Elgarhy** [comment]
I did this and it didn't work

**Comment by noel-debug** [comment]
I encouter the same issue with different jetbrains ides
