### ISSUE TITLE
"Indexing process should not rely on non-indexed file data."

### ISSUE THREAD

**Issue by SteyerCaansHerzog** [EmmyLua/IntelliJ-EmmyLua#450]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA Ultimate 2021, PhpStorm 2021
 EmmyLua version | 1.3.5.194-IDEA203 + older versions
 OS                        | Windows 11

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Work on a large Lua project
2. Edit Lua file
3. Save the file
4. Wait for EmmyLua to process the file

What happens?（出现什么问题？）
-------------
An IDE error will occur. Not every time, but most of the time.

IDE Error Occurred:
 - "Indexing process should not rely on non-indexed file data"
 - "To reindex this file IDEA has to be restarted"

What were you expecting to happen?（期望？）
-----------------------------------------
I expect no error to occur.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
https://ghostbin.com/oxd6T

Any other comments?（其它说明）
------------------------
…

**Comment by tangzx** [comment]
try version 1.4.+
