### ISSUE TITLE
Expression Expected using backticks

### ISSUE THREAD

**Issue by xnubil** [EmmyLua/IntelliJ-EmmyLua#452]
Environment（环境）
--------------
   Webstorm |   2021.2.1
----------|----------
 IDEA version         | WS-213.6461.79
 EmmyLua version | 1.3.6.222-IDEA213
 OS                        | Win 11

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Use backticks ( ` ) as Jenkin hash for FiveM development

What happens?（出现什么问题？）
-------------
Expression expected error
https://i.imgur.com/7rS6JWo.jpeg

What were you expecting to happen?（期望？）
-----------------------------------------
No error

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
Code example
```
Vehicles = {
--- Compacts
['asbo'] = {
['name'] = 'Asbo',
['brand'] = 'Maxwell',
['model'] = 'asbo', 
['price'] = 4000,
['category'] = 'compacts',
['hash'] = `asbo`,  -- < ERROR
['shop'] = 'pdm',
},
['blista'] = {
['name'] = 'Blista',
['brand'] = 'Dinka',
['model'] = 'blista',
['price'] = 13000,
['category'] = 'compacts',
['hash'] = `blista`,  -- < ERROR
['shop'] = 'pdm',
}
}
```

Any other comments?（其它说明）
------------------------
Formatting code is not possible due to expression error

**Comment by CppCXY** [comment]
' is not a delimiter supported by lua
