### ISSUE TITLE
reinstall EmmyLua之后卡死

### ISSUE THREAD

**Issue by 564155611** [EmmyLua/IntelliJ-EmmyLua#453]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version | [e.g. v1.2.5]
 OS                        | [e.g. OSX 10.13.4, Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. …第一次安装这个插件后能够启动IDEA,但是运行LUA Project中src下的lua文件报错,说找不到Hello.lua不存在,
2. …然后重新安装reinstall EmyLua->重启IDEA,就出现报错PersistenceException:C:\Users\fanx\AppData\Local\JetBrains\IntelliJIdea2021.3\caches\names.dat
3. …然后删除这个caches中的names.dat数据,重启IDEA结果没有报错,但是卡死:
![image](https://user-images.githubusercontent.com/73692902/150516502-f018e88e-5d88-4ed0-9348-60f47bcb0fa6.png)
卡在这个位置已经有30minutes了

What happens?（出现什么问题？）
-------------
…
卡在这个界面![image](https://user-images.githubusercontent.com/73692902/150516613-cc8034fe-c8ea-446d-b2eb-0e8745c4ae17.png)无法继续

What were you expecting to happen?（期望？）
-----------------------------------------
…期望能够正常使用

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
无

Any other comments?（其它说明）
------------------------
…无

**Comment by KSDaemon** [comment]
+1. Disabling EmmyLua plugin allow to work.... But...
