### ISSUE TITLE
com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.

### ISSUE THREAD

**Issue by FizzleFuze** [EmmyLua/IntelliJ-EmmyLua#455]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2021.3.1 Community Build#IC-213.6461.79 on Dec 28, 2021
 EmmyLua version | 1.3.6.22
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Open a .lua file
2. Scroll through it

What happens?（出现什么问题？）
-------------
"IDE error occurred...
Exception in plugin EmmyLua"

What were you expecting to happen?（期望？）
-----------------------------------------
No error

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
https://ghostbin.com/Zq1u6

Any other comments?（其它说明）
------------------------
This happens multiple times every day which I use IntelliJ IDEA, though it seems to be only with certain files.

**Comment by tangzx** [comment]
try new version 1.4.+
