### ISSUE TITLE
cant go to definition of function in deep table

### ISSUE THREAD

**Issue by yuz10** [EmmyLua/IntelliJ-EmmyLua#46]
```lua
local a = {}
a.b = {}
function a.b.c() end
```

in call of function a.b.c(), press ctrl+click, cant go to the definition

**Comment by tangzx** [comment]
Yes, it is a known bug, will be fixed in later version

**Comment by tangzx** [comment]
closed by [a859177](https://github.com/EmmyLua/IntelliJ-EmmyLua/commit/a859177712daced249deb39caff2cf27149048d6)
