### ISSUE TITLE
@language injection does not support language names with spaces in the name

### ISSUE THREAD

**Issue by varon** [EmmyLua/IntelliJ-EmmyLua#462]
￼![lang-fail](https://user-images.githubusercontent.com/1936994/156044350-a9b4d6af-0166-48f6-a4d9-946eb4351ac6.jpg)

Language injection does not parse languages correctly with a space in the name. This makes it impossible to inject Shell Script into a string in EmmyLua, which would help a lot to have!

I have tried the following workarounds:
```lua
--- @language 'Shell Script'
--- @language "Shell Script"
--- @language [Shell Script]
```
They do not work and throw parse errors.

Any other comments?（其它说明）
------------------------

This is hugely important - I'd be happy to donate to the project to get this sorted out if you guys are accepting bug bounties!

is there a workaround for this?

**Comment by ApeaSuperz** [comment]
Need it too
