### ISSUE TITLE
断点调试时间久了，Unity崩溃退出

### ISSUE THREAD

**Issue by huangshallwe** [EmmyLua/IntelliJ-EmmyLua#463]
Environment（环境）
--------------
   Unity   |   2018.4.1f1  
----------|----------
 IDEA version         | [JetBrains Rider 2020.2.4]
 EmmyLua version | [v1.3.5.194-IDEA202]
 OS                        | [Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Unity断点调试xlua，断点时间稍微久一点(一分钟)， Unity就崩溃退出

What happens?（出现什么问题？）
-------------
Unity崩溃退出

What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------

**Comment by CppCXY** [comment]
尝试从https://github.com/EmmyLua/EmmyLuaDebugger/releases 下载最新的emmy_core看是不是还有崩溃问题。

**Comment by huangshallwe** [comment]
> [试用从 https://github.com/EmmyLua/EmmyLuaDebugger/releases](https://github.com/EmmyLua/EmmyLuaDebugger/releases)下载最新的 emmy_core 看是不是还有崩溃问题。
感谢，

> 尝试从 https://github.com/EmmyLua/EmmyLuaDebugger/releases 下载最新的 emmy_core 看是不是还有崩溃问题。

感谢， 使用最新的emmy_core.dll已经正常了
