### ISSUE TITLE
(Question) Cant figure out how customize plugin

### ISSUE THREAD

**Issue by Yum1x** [EmmyLua/IntelliJ-EmmyLua#464]
I'm trying extend the EmmyLua Plugin functionalities, Lua 5.4 has a 'Power Patch' that becomes with Compound Operators and others many(small) features.

I'm trying do it by myself, as a new and inexperienced developer, i'm getting stucked at something that I cant figure out.

I want use '+=' and '-=' without catch an exception. After editing some files, I cant make it work. Could someone do a review and tell what i'm doing wrong?
There is what I did: https://github.com/Yum1x/IntelliJ-EmmyLua/commit/be6455d0e17617255e8d5d3f1fb6c1e4084f553c

**Comment by CppCXY** [comment]
’+=‘ should be assign operator，so assignStat of lua.bnf should be modified.
if implement this feature，formatting also requires relative modifications。
