### ISSUE TITLE
Incompatible lastest version of IntellJ IDEA v2022.1

### ISSUE THREAD

**Issue by supernghia89** [EmmyLua/IntelliJ-EmmyLua#471]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [e.g. IC221.5080]
 EmmyLua version | [e.g. v1.3.6.225]
 OS                        | [e.g. Windows 11]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. …
2. …
3. …

What happens?（出现什么问题？）
-------------
Incompatible lastest version of IntellJ IDEA v2022.1

What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

![image](https://user-images.githubusercontent.com/15607260/163752844-9f1d10f0-b241-4c90-9a90-8bf9eaf748f7.png)

Any other comments?（其它说明）
------------------------
…

**Comment by CppCXY** [comment]
download https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/artifacts

**Comment by rulatir** [comment]
Why is this a recurring issue? Don't JetBrains release early access versions of their IDEs, so plugin authors can fix incompatibilities and complete the approval process before the official release?

**Comment by CppCXY** [comment]
The truth is that the author of emmylua is too busy.

**Comment by supernghia89** [comment]
> download https://ci.appveyor.com/project/EmmyLua/intellij-emmylua/build/artifacts

Many thanks. Keep up the good work !

**Comment by decadence** [comment]
Plugin version 1.3.6.251-IDEA213 works with PhpStorm 2022.1, uploaded yesterday.

**Comment by caerulescens** [comment]
I had this issue as well; the IDE becomes unresponsive during indexing.

**Comment by CppCXY** [comment]
> the IDE becomes unresponsive during indexing.

`File> Invalid caches.`
After the idea is updated, the previous index may be invalid
