### ISSUE TITLE
Local variable problems

### ISSUE THREAD

**Issue by nick-nh** [EmmyLua/IntelliJ-EmmyLua#475]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IC-221.5591.52
 EmmyLua version |1.3.6.251-IDEA213
 OS                        |Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
write simple code:

local a = 5

local function b(x)
    return x+a
end

print(b(4))

What happens?（出现什么问题？）
-------------
in Problems "Current file" tab have problem

Local variable "a"

What were you expecting to happen?（期望？）
-----------------------------------------

No problem in such code

Any other comments?（其它说明）
---------------------

In big files Problems tab fills only that kind notes

![изображение](https://user-images.githubusercontent.com/11758539/170968196-c6edeb83-3729-490f-a6e0-0b6cc3ea2b16.png)

**Comment by CppCXY** [comment]
![image](https://user-images.githubusercontent.com/40318218/171080688-4152e807-d9b2-48b0-b36c-29b42d493144.png)
not found this bug

**Comment by nick-nh** [comment]
In your image TODO tab, not Problems.

**Comment by CppCXY** [comment]
Ok,  I known,  later I will ask author why

**Comment by CppCXY** [comment]
this feature just to warn you this is an upvalue
