### ISSUE TITLE
Local function highlights as local variable

### ISSUE THREAD

**Issue by Pentasis** [EmmyLua/IntelliJ-EmmyLua#476]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ 2022.1.2
 EmmyLua version | 1.3.6.251-IDEA213
 OS | Windows 10

local function someName is highlighted in the same way as a local variable. In the settings there is no way to set a highlight color for a local function, only local/global variable and global function.
![Screenshot (82)](https://user-images.githubusercontent.com/7046024/172151927-348fce61-a3cc-4cd2-997e-c2743d7fc38a.png)

**Comment by tangzx** [comment]
try this build:
https://github.com/EmmyLua/IntelliJ-EmmyLua/actions/runs/5183580607
