### ISSUE TITLE
IDEA Ultimate freeze when indexing JDK 1.8

### ISSUE THREAD

**Issue by GBLodb** [EmmyLua/IntelliJ-EmmyLua#482]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA 2022.1.2 (Ultimate Edition) Build #IU-221.5787.30, built on June 1, 2022
 EmmyLua version | 1.3.6.251-IDEA213
 OS                        | Windows 10 Professional 21H1, 19043.1766, Windows Feature Experience Pack 120.2212.4180.0

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
Import any Java Gradle project.

What happens?（出现什么问题？）
-------------
IDEA Ultimate freeze when indexing JDK 1.8 

What were you expecting to happen?（期望？）
-----------------------------------------
Finish indexing jdk normally.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
[idea.log](https://gist.github.com/GBLodb/5e5575d1fff4c55a5107b3a0df0de572)
[Thread Dump](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/8995170/threadDumps-freeze-20220628-030825-IU-221.5787.30.zip)

Any other comments?（其它说明）
------------------------
Using JDK: Eclipse Adoptium jdk-8.0.322.6-hotspot

[Report on YouTrack](https://youtrack.jetbrains.com/issue/IDEA-296930/IDEA-Ultimate-freeze-when-indexing-JDK-18)

**Comment by CppCXY** [comment]
maybe `invalide caches` can help. or use oracle jdk

**Comment by GBLodb** [comment]
> maybe `invalide caches` can help. or use oracle jdk

Yeah, the index is after a invalid cache restart. I haven't try change the JDK yet but I still think this could be considered as a bug.

**Comment by CppCXY** [comment]
The indexing mechanism of intellij itself is complex and has many problems. Many many problems and bad reviews come from index freezing. I am not the author and cannot give an accurate answer

**Comment by tangzx** [comment]
fixed in 1.4.+
