### ISSUE TITLE
Incompatible with IntelliJ IDEA 2022.2 EAP (#IC-222.3153.4)

### ISSUE THREAD

**Issue by mtwango** [EmmyLua/IntelliJ-EmmyLua#483]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | #IC-222.3153.4, 2022.2 EAP  (Community Edition)
 EmmyLua version | 1.3.6.251-IDEA213
 OS                        | Windows 11, Version 10.0.22000.739

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Use 2022.2 EAP version.

What happens?（出现什么问题？）
-------------
Plugin is incompatible with IDEA 2022.2 EAP.

**Comment by derolli1976** [comment]
How about the update for IDEA 2022.2? DataGrip 2022.2 is already available, but this plugin is the reason we cannot update.

**Comment by CppCXY** [comment]
I will inform the author

**Comment by kluevandrew** [comment]
Any updates?

**Comment by CppCXY** [comment]
> Any updates?

download from
https://github.com/EmmyLua/IntelliJ-EmmyLua/actions/runs/2764698912

**Comment by kluevandrew** [comment]
Now it works with installation from JetBrains Marketplace. I believe that issue may be closed.
