### ISSUE TITLE
Invalid in autocomplete

### ISSUE THREAD

**Issue by AndRo-Marian** [EmmyLua/IntelliJ-EmmyLua#484]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2019.2.4
 EmmyLua version | 1.3.3.150-IDEA182
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Create a simple lua file
2. Paste the content on it:
```
function Timer()
    local timer = {};

    function timer:Start()
    end

    function timer:Stop()
    end

    function timer:IsRunning()
        self:|
    end

    return timer;
end
```
4. Start typing for autocomplete on 'IsRunning' after self:St

What happens?（出现什么问题？）
-------------
Good autocomplete suggestions, after typing the second character 't' after 'S' all gets Invalid.

What were you expecting to happen?（期望？）
-----------------------------------------
The suggestions to remain good as before.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
![B4vidxTM6P](https://user-images.githubusercontent.com/48178307/176680625-9ff726ef-96a6-4b53-96d4-bcc7dc9bc1f6.gif)

**Comment by CppCXY** [comment]
update to lastest

**Comment by CppCXY** [comment]
You need to upgrade intellij idea first

**Comment by AndRo-Marian** [comment]
I can't update to newer because I found this version to work best for my. Compared to bugs that broken things that was working good before. So I stick to this for now.
