### ISSUE TITLE
无法使用emmylua

### ISSUE THREAD

**Issue by lanchengkai** [EmmyLua/IntelliJ-EmmyLua#493]
--------------
   name   |   version  
----------|----------
 IDEA version         | VSCODE
 EmmyLua version | 最新
 OS                        | Windows 10

重装电脑后，重新安装VSCODE 以及 JDK 但是不管怎么重新安装JAVA EmmyLua一直报错，无法正确显示代码提示(提示hover调用失败)

好像是堆栈问题，但是我的代码是0，就只是单纯的用不来emmylua
![QQ图片20220814194309](https://user-images.githubusercontent.com/62948104/184535153-8090b00d-b33d-41e8-b7a6-c110a2680754.png)

**Comment by CppCXY** [comment]
退几个版本呢

**Comment by lanchengkai** [comment]
我现在尝试退到 4.19 目前还没发现问题
