### ISSUE TITLE
emmy_core.dll: invalid ELF header

### ISSUE THREAD

**Issue by chenyyyang** [EmmyLua/IntelliJ-EmmyLua#499]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA 2022.2.1 (Community Edition) Build #IC-222.3739.54, built on August 16, 2022
 EmmyLua version | 1.3.7.2-IDEA222
 OS                        | win11 WSL Ubuntu-20.04

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 在windwos11下IDEA 更改apisix lua代码，添加对应的debug code
2. 在WSL中运行apisix start

What happens?（出现什么问题？）
-------------
走到require 代码立即报错
2022/09/14 12:07:30 [error] 30603#30603: *713 lua entry thread aborted: runtime error: error loading module 'emmy_core' from file '/mnt/c/emmy_core.dll':
        /mnt/c/emmy_core.dll: invalid ELF header
stack traceback:
coroutine 0:
        [C]: in function 'require'
       /apisix/apisix-2.13.1/apisix/plugins/open-api.lua:32: in function 'phase_func'
        /apisix/apisix-2.13.1/apisix/plugin.lua:746: in function 'run_plugin'
       /apisix/apisix-2.13.1/apisix/init.lua:481: in function 'http_access_phase'

What were you expecting to happen?（期望？）
-----------------------------------------
进行单步调试

**Comment by CppCXY** [comment]
既然是在wsl上跑代码，你应该去require so，而不是dll

**Comment by chenyyyang** [comment]
@CppCXY  感谢，已经fix了
