### ISSUE TITLE
Code style settings are empty

### ISSUE THREAD

**Issue by DoctorGester** [EmmyLua/IntelliJ-EmmyLua#5]
![image](https://cloud.githubusercontent.com/assets/3684394/23860175/346bb1b0-0817-11e7-96ae-e65b6b35f52a.png)

This leads to issues with space vs tabs recognition, it always thinks that Lua code should use tabs.

**Comment by tangzx** [comment]
Sorry, the code style is uncompleted, please wait for next version :smile:

**Comment by dustingraham** [comment]
I see you added Spaces around operators, before comma, after comma, and after field sep (separator), thanks for those.

I realize there's a lot to add, but the one addition that would make me most happy would be:

Tabs and Indents -> Keep indents on empty lines.

**Comment by tangzx** [comment]
Formatting & code style settings are `Experimental` feature currently. It's in my plans, please wait...

**Comment by sharonovd** [comment]
Two issues prevent me from using formatter everywhere:
1) 'Continuation indent' seems to be not working - it acts like always set to 'zero'
2) Our code is full with simple one-liners like this one:
if not ok then return false, err end
Formatter expands them to three lines; could you please make that configurable?

Everything else is cool!

**Comment by tangzx** [comment]
@sharonovd Available in next version

![2017-11-21_16-47-40](https://user-images.githubusercontent.com/3354360/33062966-ea81af1e-cedb-11e7-8ecd-f2641321403d.gif)
