### ISSUE TITLE
Endless 'Updating indices'

### ISSUE THREAD

**Issue by kpa6uu** [EmmyLua/IntelliJ-EmmyLua#50]
Hello. I have a problem on macOS Sierra 10.12.6 with endless indices updating.
On linux xubuntu this plugin works fine on the same project.

I tried to invalidate(update) cache by PHPStorm function, but it didn't help.

Can you please fix this problem?
What logs i can send to you?

Thanks.

**Comment by tangzx** [comment]
Yes, please upload idea log, click menu `Help`->`Show log in Finder`

**Comment by kpa6uu** [comment]
@tangzx 

[emmylua_phpstorm_log.txt](https://github.com/tangzx/IntelliJ-EmmyLua/files/1302512/emmylua_phpstorm_log.txt)

**Comment by tangzx** [comment]
@kpa6uu :ok:

**Comment by kpa6uu** [comment]
@tangzx works fine after last update. Thanks!

**Comment by antonalechnovic** [comment]
oh again ffs
