### ISSUE TITLE
Incompatible with 2022.3 EAP

### ISSUE THREAD

**Issue by Alexsey** [EmmyLua/IntelliJ-EmmyLua#504]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | WebStorm 2022.3 EAP
 EmmyLua version | 1.3.7.2
 OS                        | OSX 12.6

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Update the IDE to 2022.3 EAP

What happens?（出现什么问题？）
-------------
The plugin is not running and giving an alert "Incompatible: requires EDE build 222.* or earlier"

What were you expecting to happen?（期望？）
-----------------------------------------
It would be nice if the plugin would work :)

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------

<img width="762" alt="Screenshot 2022-10-21 at 13 33 44" src="https://user-images.githubusercontent.com/6392013/197176375-329b837d-659a-44a9-aa73-3a5c5dec3eca.png">

**Comment by CppCXY** [comment]
Usually Intellij-Emmylua will only adapt within one week of the official version update, 
Or you can try changing the configuration to adapt to the EAP version

**Comment by Alexsey** [comment]
Thank you for the quick reply! I assume the minimal changes would be to change in `build.gradle.kts` in line 47 `222.*` to `223.*` right?

**Comment by CppCXY** [comment]
yes, if that can pass compile.

**Comment by Alexsey** [comment]
Unfortunately, my local env is not compatible with the build process :( Considering that my pet project with Lua is on-hold, I'll probably wait for the official release. Thank you for your time
