### ISSUE TITLE
Unable to set "Sources Root" for Mobdebug configuration on Jetbrains Rider 2022.2.4 with EmmyLua Plugin

### ISSUE THREAD

**Issue by david-grem-armstrong** [EmmyLua/IntelliJ-EmmyLua#508]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | RD-222.4459.9
 EmmyLua version | v 1.3.7.2-IDEA222
 OS                        | OSX 12.6

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Install the EmmyLua plug-in for JetBrains Rider
2. Add a Mobdebug configuration
3. Attempting to run gives a "Error: Sources root not found." message
4. There seems to be no way to set the sources root in Rider

What happens?（出现什么问题？）
-------------
I can't use the Mobdebug debugger

What were you expecting to happen?（期望？）
-----------------------------------------
I should be able to set the sources root in some settings panel somewhere (and the EmmyLua documentation should tell me where that is) and then I should be able to use the Mobdebug debugger.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
"Error: Sources root not found"

Any other comments?（其它说明）
------------------------
…

**Comment by CppCXY** [comment]
use emmylua attach debugger, Or emmy new debugger

**Comment by CppCXY** [comment]
the emmylua documentation hasn't been updated for a long time, and mobdebug has long been deprecated.
we recommend using `Emmy New Debug`, which has superior performance.
`Emmylua attach debugger` was also fine, but it was removed from the Emmylua plugin due to a virus, you can get from 
[EmmyLua-AttachDebugger-1.0.9.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/10100960/EmmyLua-AttachDebugger-1.0.9.zip)

**Comment by david-grem-armstrong** [comment]
Unfortunately, I'm on in an OSX development environment, so the .dll libs won't work for me. I originally attempted to use "Emmy Debugger(NEW)", but I couldn't get my project to properly load and called into emmy_core.dylib. My project has a Lua layer on top of a C# layer. Do you have any recommendations on how to get C# to called into the emmy_core.dylib correctly?

**Comment by CppCXY** [comment]
if you use, xlua or other unity lua plugin, please recompile the xlua.dylib or other-plugin.dylib with C macro `LUA_USE_DLOPEN` and `LUA_USE_MACOSX`. then you can paste the code into you codebase
```lua
local dbg = require "emmy_core"
dbg.tcpListen("localhost", 9966)
dbg.waitIDE()
```
first play the game in unity, and then start debug configuration

**Comment by CppCXY** [comment]
EmmyLua has special support for `xlua` and `tolua`, which can reflect explicit Unity variables when debugging

**Comment by david-grem-armstrong** [comment]
I'm using tolua as the Unity plug-in for running Lua and when attempting the above code, I get an error that emmy_core can't be found. Is there something special I need to do for Unity to be able to load emmy_core?

**Comment by CppCXY** [comment]
in Emmy Debug(NEW), it generate code contain `package.cpath = package.cpath .. ` copy also.

**Comment by CppCXY** [comment]
Or you copy emmy_core.dylib under `unity project` mean
- Assets/
- others
- emmy_core.dylib

**Comment by david-grem-armstrong** [comment]
Based on this recommendation, I will close this issue and move further questions/issues to new thread directed at Emmy Debugger(NEW) https://github.com/EmmyLua/IntelliJ-EmmyLua/issues/513 Thanks
