### ISSUE TITLE
Infinite indexing in IntelliJ Ultimate 2022.2.4, MacOS Ventura 13.0.1 (deadlock detected by Yourkit)

### ISSUE THREAD

**Issue by Techcable** [EmmyLua/IntelliJ-EmmyLua#510]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA 2022.2.4 (Ultimate Edition)
 EmmyLua version | 1.3.7.2-IDEA222
 OS                        | MacOS Ventura 13.0.1

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Clear caches & restart in IntelliJ Ultimate
2. After clearing caches, open a Rust + Python project
3. This will cause IntelliJ to re-index
4. Project freezes [...]

What happens?（出现什么问题？）
-------------
The entire application freezes.

[YourKit](https://www.yourkit.com) detects a deadlock in EmmyLua I've pasted below.

Disabling EmmyLua fixes the issue.

What were you expecting to happen?（期望？）
-----------------------------------------
I can have EmmyLua enabled, and the application should still work.

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

https://gist.github.com/Techcable/bd377d5688b771a16b47dde23d9da132

Any other comments?（其它说明）
------------------------
Similar to some other issues. However, I am not sure its the same. Deadlocks can be very difficult to debug, so I thought I'd post the information [YourKit](https://www.yourkit.com) identified.

It looks like the `Ty` class can't even finish running its class initializer `<clinit>` ([link](
https://gist.github.com/Techcable/bd377d5688b771a16b47dde23d9da132#file-yourkit-deadlock-intellij-txt-L1183 )). This is caused by a deadlock in the `static` fields or a `static {  }` block. 

If the class initializer of `Ty` can't finish, nothing else in the `Ty` class can run!

**Comment by Techcable** [comment]
Based on the stack trace, it seems like the root of the problem is `com.tang.intellij.lua.ty.Ty.<clinit>()` at `Ty.kt:198`:

https://github.com/EmmyLua/IntelliJ-EmmyLua/blob/4d101b82ec81a129dab821d9b92d88fcffb47fd5/src/main/java/com/tang/intellij/lua/ty/Ty.kt#L198

I strongly suspect this triggers some sort of a dependency cycle in class initialization. If this is the case, consider using [Kotlin's lazy properties](https://kotlinlang.org/docs/delegated-properties.html#lazy-properties).

I am seeing `Ty.<clinit>` in the thread dumps of #459 , #482, 

Possibly the cause of #429 , but the pastebin of the thread dump expired so I cannot tell.

**Comment by CppCXY** [comment]
can you make a pr fix this?

**Comment by Techcable** [comment]
Yes. I am working on it right now 😄  It looks like the issue is simple to fix!

If you look in stack you will also see
`waiting on the Class initialization monitor for com.tang.intellij.lua.ty.TyClass`

**Comment by Techcable** [comment]
This is closed by #511
