### ISSUE TITLE
Rider如何为Lua Remote Debug设置Sources?

### ISSUE THREAD

**Issue by liushengliuyun** [EmmyLua/IntelliJ-EmmyLua#514]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [Rider JetBrains Rider 2022.3]
 EmmyLua version | [1.3.7.2-IDEA222]
 OS                        | [ Windows 10]

问题描述: Rider设置Remote Debug时, 报Sources root not found, 但是又找不到设置Sources的地方.

**Comment by CppCXY** [comment]
前话: rider2022.3如果已经发布你得emmylua版本应该是1.3.8

rider没有project structure,所以不能设置Sources.所以不能使用mobdebug.
而emmylua并不推荐使用mobdebug, 或许你看过emmylua githubio上的文档,但是这个文档早已过时.
emmylua有自己的C++实现的远程调试器和附加调试器.
远程调试器叫emmy debug(NEW) 你可以在configuration里面看到.一般用那个就可以了

**Comment by liushengliuyun** [comment]
@CppCXY 

确实用 emmy debug(NEW)设置监听, 然后再运行脚本的话可以任意断点了. 谢谢大师!
