### ISSUE TITLE
module 'socket' not found:

### ISSUE THREAD

**Issue by JiaRG** [EmmyLua/IntelliJ-EmmyLua#527]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA 2022.3.2 (Ultimate Edition)
 EmmyLua version | 1.3.8-IDEA223
 OS                        | Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
debug lua script

What happens?（出现什么问题？）
------------------------------------------------
可以正常run，但是不能debug
module 'socket' not found

What were you expecting to happen?（期望？）
-----------------------------------------
正常debug

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
```
Start mobdebug server at port:8172
Waiting for process connection...
lua.exe: ...17.56.plugins/EmmyLua/debugger/mobdebug/mobdebug.lua:102: module 'socket' not found:

	no field package.preload['socket']

	no file 'D:\Develop\Lua\5.1\lua\socket.luac'
```

Any other comments?（其它说明）
------------------------
为啥会加载socket.luac这个呢，安装的路径有socket.lua
lua是通过 https://github.com/rjpcomputing/luaforwindows 安装的
之前能debug的啊

**Comment by CppCXY** [comment]
emmylua的调试方式其实是emmy new debug

**Comment by JiaRG** [comment]
@CppCXY 大佬，我该咋弄，新手只是用来本地调试下脚本😂

**Comment by JiaRG** [comment]
莫名其妙又好使了。。😂

**Comment by CppCXY** [comment]
有问题加群问

**Comment by JiaRG** [comment]
好的。
有时会出现个这问题：
![image](https://user-images.githubusercontent.com/31472350/218639904-176b1f1d-9ad5-4b41-942a-1716c6d49e4b.png)
重新debug的时候就一直卡在这
重试几次就好了
