### ISSUE TITLE
Q: is there a way to exclude directories?

### ISSUE THREAD

**Issue by tanis2000** [EmmyLua/IntelliJ-EmmyLua#528]
I am using EmmyLua with CLion and a CMake-based project. I would like to be able to exclude the cmake-build-debug folder as it contains the files created by the build itself which means that all my .lua files get copied there, too. This is confusing EmmyLua as it sees duplicate definitions. On top of that it looks like this is also causing quite some exceptions.

Is there already a way to exclude that directory? Or would you take into consideration to add this feature?

Thanks!

**Comment by CppCXY** [comment]
settings>Editor> File Types> Ignored Files and Folders

**Comment by tanis2000** [comment]
Thanks!
