### ISSUE TITLE
[Fatal] buuuuuuuuuuuuuuuuuuuuuuuuuuuuuug

### ISSUE THREAD

**Issue by CppCXY** [EmmyLua/IntelliJ-EmmyLua#531]
IDEA 2023.1

在---@private 注释上键入 ---会导致整个IDE卡死
[test.zip](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/11148302/test.zip)

@tangzx

**Comment by tangzx** [comment]
了解了，明天看看
