### ISSUE TITLE
IDEA崩溃

### ISSUE THREAD

**Issue by JackeyInNottingham** [EmmyLua/IntelliJ-EmmyLua#533]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [2023.1]
 EmmyLua version | [1.3.11]
 OS                        | [ OSX 12.2.1]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 打开工程之后随便输入一个逗号，IDEA就崩溃了，只能强制退出，无报错
2. 关闭插件之后可以任意编辑

**Comment by CppCXY** [comment]
duplicate #532
