### ISSUE TITLE
大文件无法加入 IntelliSense，能否拆分小文件

### ISSUE THREAD

**Issue by zolo-mario** [EmmyLua/IntelliJ-EmmyLua#535]
使用 UnLua  框架，引擎 C++ 类会生成一个 UE.lua IntelliSense 文件，太大了导致无法提示

我打算拆分到多个小文件，小文件的格式应该是怎么样的，使得 EmmyLua 能完整地提示所有 UE.XXX 类

![image](https://user-images.githubusercontent.com/57245542/232830603-be86628a-c0a4-40ee-9539-4f123ec6a16c.png)

**Comment by zolo-mario** [comment]
尝试了一下直接拆就行，EmmyLua 会自动合并，求确认下

![image](https://user-images.githubusercontent.com/57245542/232832212-e27090cb-bcbb-4cf4-b6a3-4a96a96cd68a.png)

**Comment by CppCXY** [comment]
这里有设置, 不用拆分.
![KCXUSJ8LCOF8C F~08Y1W27](https://user-images.githubusercontent.com/40318218/232948027-17171532-a24d-4dca-8b08-0c93492e563f.png)

**Comment by zolo-mario** [comment]
原来是在这里，已解决
