### ISSUE TITLE
Inherited Methods no longer show up on 1.3.20-IDEA231

### ISSUE THREAD

**Issue by nfet** [EmmyLua/IntelliJ-EmmyLua#537]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2023.1.x 2023.2.3.x
 EmmyLua version | 1.3.20-IDEA231
 OS                        | OSX 13.31.1 Ventura

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------

```lua

---@class MyClass
local A = {}
function A:Hello() end

```

What happens?（出现什么问题？）
-------------
-- typing 'A:'  and code complete does not show 'Hello()' method

What were you expecting to happen?（期望？）
-----------------------------------------
A:Hello() to show as list of options

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by nfet** [comment]
The fix for now is to roll back to previous version. I'm currently using IDEA Ultimate 2023.1.1
- https://plugins.jetbrains.com/plugin/9768-emmylua/versions/stable/306019

**Comment by CppCXY** [comment]
1.3.11 will cause the editor to freeze. you best to return 2022.3. 
it will take some time for version 1.4.x to arrive

**Comment by tangzx** [comment]
Fixed in version 1.4.0+
