### ISSUE TITLE
Rider 2023.1.1 无法正确给出 Lua 提示

### ISSUE THREAD

**Issue by qintianchen** [EmmyLua/IntelliJ-EmmyLua#540]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | JetBrains Rider 2023.1.1 Build RD-231.8770.54
 EmmyLua version | 1.3.20-IDEA231
 OS                        | Windows 11

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 安装 Unreal 5.1 和 Rider
2. 新建 Unreal 空工程，通过 Rider 打开 .sln
3. Rider 中新建目录 /Content/Scripts，右键 Scripts 然后 attach to solution
4. 在 Scripts 下新建 Lua 脚本测试提示

What happens?（出现什么问题？）
无法正确提示。例如一个文件中声明全局的表 Utils，并声明一些成员变量和函数。另一个文件中尝试访问 Utils，提示 Utils 是一个全局变量，但是无法自动列出它的成员变量和函数。

What were you expecting to happen?（期望？）
可以正确列出它的成员变量和函数。

Any logs, error output, etc?（有没有什么log, error输出？）

Any other comments?（其它说明）

**Comment by CppCXY** [comment]
退回到2022.3, 2023.1的所有emmylua版本暂时都有问题

**Comment by ye-zi-china** [comment]
2023版本提示异常，回退到2022版本提示正常

**Comment by qintianchen** [comment]
回退到 2022 版本一切正常。

**Comment by tangzx** [comment]
请使用 1.4.+ 版本
https://github.com/EmmyLua/IntelliJ-EmmyLua/actions/runs/5173708201
