### ISSUE TITLE
Crashes IntelliJ IDEA 2023 if you install this plugin!

### ISSUE THREAD

**Issue by singharaj-usai** [EmmyLua/IntelliJ-EmmyLua#542]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [IntelliJ IDEA 2023]
 EmmyLua version | [v1.3.7]
 OS                        | [Windows 11]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Installing this plugin via the marketplace plugin will crash Intellij!
2. Only way to stop the program from crashing is going to AppData > Roaming > Jetbrains > IntelliJ > Plugins > then delete EmmyLua folder, this has been going on for months without it being fixed, so please avoid downloading this plugin!

What happens?（出现什么问题？）
-------------
Crashes Intellij

What were you expecting to happen?（期望？）
-----------------------------------------
For the plugin to download properly

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Extremely long error output, but the only way to stop the program from crashing is going to AppData > Roaming > Jetbrains > IntelliJ > Plugins > then delete EmmyLua folder

Any other comments?（其它说明）
------------------------
…

**Comment by CppCXY** [comment]
But emmylua 1.3.7 cannot be installed on 2023.1

**Comment by singharaj-usai** [comment]
Yes you can, it's on the plugins marketplace in the program, it should be removed until they fix it

**Comment by tangzx** [comment]
fixed in 1.4.+
