### ISSUE TITLE
no OO support

### ISSUE THREAD

**Issue by ScottIngram** [EmmyLua/IntelliJ-EmmyLua#543]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | IntelliJ IDEA 2023.1.2 Build #IU-231.9011.34, built on May 15, 2023
 EmmyLua version | 1.3.20-IDEA231
 OS                        | OSX 12.6.5

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. use OO syntax with a colon :
2. function Foo:Bar()
3. self:Bar()
4. try to use code navigation of IntelliJ and click self:Bar()

What happens?（出现什么问题？）
-------------
InteliJ has no idea where is Bar()

What were you expecting to happen?（期望？）
-----------------------------------------
InteliJ to jump from self:Bar() to the function definition of Foo:Bar()

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
none.

Any other comments?（其它说明）
------------------------
see pix
![timer-1](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/1865213/b7e09979-0822-4d6a-9969-c38571617e8d)
![timer-2](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/1865213/42ae8e93-2a6c-4bfd-9d19-cc172e79a6d1)
![timer-3](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/1865213/c4320909-3b72-445b-a6a0-f07f88a9962c)
![timer-4](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/1865213/e26bafac-2578-401f-8df3-a68dcd786521)

**Comment by CppCXY** [comment]
it is a bug of 1.3.20, please rollback to idea 2022.3

**Comment by ScottIngram** [comment]
that fixed it for me.  Thanks!

**Comment by CDAGaming** [comment]
@CppCXY Any word on a fix? Experiencing this issue as well...

**Comment by CppCXY** [comment]
> @CppCXY Any word on a fix? Experiencing this issue as well...

downgrade emmylua version to 1.4.6, maybe it's not available in the plugin store, try searching for it on Git Actions.

**Comment by CDAGaming** [comment]
Nice, that worked like a charm, thank you!
