### ISSUE TITLE
1.4.3-IDEA231版本卡死

### ISSUE THREAD

**Issue by esrrhs** [EmmyLua/IntelliJ-EmmyLua#551]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | CLion 2023.1.3
 EmmyLua version | 1.4.3-IDEA231
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
打开一个大的lua工程

What happens?（出现什么问题？）
-------------
整个ide卡死

What were you expecting to happen?（期望？）
-----------------------------------------

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------

**Comment by CppCXY** [comment]
https://github.com/EmmyLua/IntelliJ-EmmyLua/actions/runs/5206248623
试一下1.4.6 或者加群反馈

**Comment by esrrhs** [comment]
用这个版本后ok了
