### ISSUE TITLE
Code completion not as complete as in 1.3.7.2

### ISSUE THREAD

**Issue by nielsvaes** [EmmyLua/IntelliJ-EmmyLua#559]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | PyCharm 2023.2.1 (Community Edition)
 EmmyLua version | 1.4.7
 OS                        | Windows 11

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
For example, I have a Lua file that looks like this: 
![image](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/7821618/6b109971-6bc6-4082-ad3d-4967157bc232)

I'm just trying to get code completion for all the functions you see here on the `POLYGON` class.

What happens?（出现什么问题？）
-------------
Only the first "level: of the table is shown (`POLYGON`) in the code completion, but not all the functions associated with it. 

![image](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/7821618/70b6f1b6-336b-4917-8152-5c5541832559)

Things I've tried that didn't solve the issue:
* Installing 1.4.8 in PyCharm 2023.2.1
* Adding the folders to the `Lua Additional Sources Root` in `File > Settings > Languages & Frameworks > EmmyLua`

What were you expecting to happen?（期望？）
-----------------------------------------
More code completion. 

In PyCharm 2022.2.5 (Community Edition) with EmmyLua 1.3.7.2-IDEA222, I get completion for all the functions.

![image](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/7821618/f0b1860d-ed77-4a94-b5a4-c8762800fbd9)

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------

Any other comments?（其它说明）
------------------------
PyCharm 2023.2.1 (Community Edition)
Build #PC-232.9559.58, built on August 22, 2023
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 20
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    cn.yiiguxing.plugin.figlet (1.2.1)
    Batch Scripts Support (1.0.13)
    com.intellij.plugin.adernov.powershell (2.0.10)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    com.tang (1.4.7-IDEA231)
    ru.meanmail.plugin.requirements (2022.4.1)

**Comment by CppCXY** [comment]
https://github.com/EmmyLua/IntelliJ-EmmyLua/actions/runs/5777749632 for 1.4.8

**Comment by nielsvaes** [comment]
I must have done something wrong when I tried to install 1.4.8 earlier, because it does indeed seem to work now. My bad!
