### ISSUE TITLE
Can't break point lua with Emmy Debugger(NEW)

### ISSUE THREAD

**Issue by ahyee** [EmmyLua/IntelliJ-EmmyLua#561]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2022.3.3
 EmmyLua version | 1.3.8
 OS                        | Window 11

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. Run debugger in rider and insert a breakpoint
2. Run unity 2022.3.5 and try to hit the breakpoint

What happens?（出现什么问题？）
-------------
The IDE didn't stop at the breakpoint despite the log was printed out. And also the IDE showed its connected as below

Server(localhost:9966) open successfully, wait for connection...
Connected.

What were you expecting to happen?（期望？）
-----------------------------------------
Expect the IDE to stop at breakpoint

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
My Lua files was located outside of Unity Assets folder, not sure if this matter.

**Comment by CppCXY** [comment]
This may be because your chunkname does not comply with the general rules of Lua. The general format for a Lua chunkname is aaa/b/ccc.lua. You can check the chunkname by printing debug.getinfo(1).source or use dbg.breakHere() to forcefully break and inspect it. If you are developing with Unity's xLua, you can modify the custom loader. If you are using a different framework, you can try modifying the usage of the lua loadbuffer interface.

**Comment by ahyee** [comment]
This is what I printed out with debug.getinfo

@UI/UIVillage 

but the break point still didnt worked.

**Comment by CppCXY** [comment]
you can try `dbg.breakHere()`, this code needs to be inserted after `dbg.tcpConnect`, is your editor Rider?

**Comment by ahyee** [comment]
Yes I'm using Rider. I notice some of my lua file used . instead of /. Will it affect the file that i going to debug which is using /?

**Comment by CppCXY** [comment]
It is correct to use `require 'aaaa.bbbbbbbb.cccccc'` in the code, but the corresponding chunkname needs to be changed to `a/b/c`. Have you tried using `dbg.breakHere()`?

**Comment by ahyee** [comment]
dbg.breakHere() do work however I cant step over etc for it

**Comment by CppCXY** [comment]
Files outside of the assets may not be indexed by Rider. You can try using other editors like Visual Studio Code or IntelliJ IDEA.

**Comment by ahyee** [comment]
I see.. I will test out others.
I using Xlua in Unity. Is this what you mean by modify custom loader?

luaEnv.AddLoader((ref string filePath) => ReadFile(filePath));

private static byte[] ReadFile(string path)
    {
        if (path == "emmy_core")
            return null;
            
        path = path.Replace('.', '/');
        var fileFullPath = $"{FileService.GetAssetRootPath()}/lua_root/{path}.lua";
        return System.IO.File.ReadAllBytes(fileFullPath);
    }

**Comment by CppCXY** [comment]
You can take a look at the documentation for the `AddLoader` function. It requires you to return the real path to `filePath`. In other words, you need to modify the `ReadFile` parameter to be `ref string path` and assign `fileFullPath` to `path`.

**Comment by ahyee** [comment]
thanks
