### ISSUE TITLE
Issue with autocompletion

### ISSUE THREAD

**Issue by Paneedah** [EmmyLua/IntelliJ-EmmyLua#564]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | 2023.2.3
 EmmyLua version | 1.4.7-IDEA231
 OS                        | Windows 11

What are the steps to reproduce this issue?
------------------------------------------------
1. Follow any of the guides / example codes
2. You will notice that using the `:` key does not give any suggestions.

What happens?
-------------
Autocompletion doesn't seem to work for `:`, use of `.` works however only for documented things.

![image](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/76911089/d4538d11-8bdb-447f-b715-2d515ffd91ac)

Exact replica of https://emmylua.github.io/annotations/param.html on the EmmyLua documentation.

Expected result:

![image](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/76911089/caf8aaeb-a7c9-4c51-837b-c537e52904bc)

**Comment by Paneedah** [comment]
Tested with EmmyLua `1.4.3-IDEA231` and it seems to be working fine again.

**Comment by CppCXY** [comment]
try 1.4.8 at git action

**Comment by Paneedah** [comment]
> try 1.4.8 at git action

Using this version seems to have solved the issue.
