### ISSUE TITLE
Addition assignment flagged as invalid

### ISSUE THREAD

**Issue by Corofides** [EmmyLua/IntelliJ-EmmyLua#567]
Environment（环境）
--------------
   IntellijIDEA   |   version  
----------|----------
 IDEA version         | 17.0.5+1-b653.23 x86_64
 EmmyLua version | 1.3.8
 OS                        | OSX 11.6

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
Create a lua script
local varName = 0
varName += 1

What happens?（出现什么问题？）
-------------
Highlighted red
Error appears '= unexpected'

What were you expecting to happen?（期望？）
-----------------------------------------
No error should be valid as it's correct syntax and compiles/ runs correctly

Any other comments?（其它说明）
------------------------
Thanks for the plugin. It's really great!

**Comment by CppCXY** [comment]
No, Lua does not have the syntax '+=' that you mentioned. This is not a standard Lua syntax. Perhaps the version of Lua you are using is a custom or extended version that is not supported by EmmyLua. If you want better support, I recommend using the lua-language-server (sumneko-lua) plugin for VSCode.

**Comment by Corofides** [comment]
Ah, you are correct. The SDK I was using was adding them in. Sorry about that.

<img width="827" alt="image" src="https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/2250364/473620f6-c1c8-4809-a4e0-bee64acf2c93">
