### ISSUE TITLE
编辑器卡顿，无法重命名

### ISSUE THREAD

**Issue by chenfeng11111** [EmmyLua/IntelliJ-EmmyLua#571]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | idea ultimate Build #IU-233.11799.300, built on December 12, 2023
 EmmyLua version | 1.4.9
 OS                        | win11

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. emmyLua require-like function names设置为"requireLua"
2. 导入附件文件
3. ctrl+6重命名变量

What happens?（出现什么问题？）
-------------
idea卡在scanning files。反复尝试偶尔会导致idea卡死
正常编辑时也会出现变量字体和提示刷新不及时的问题

What were you expecting to happen?（期望？）
-----------------------------------------
解决卡住的问题

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
附件文件，如果注释34行则一切正常，取消注释之后问题又会出现
[卡顿代码.txt](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/13682249/asd.txt)

**Comment by tangzx** [comment]
@chenfeng11111 这个应该也是一样的，用 v1.4.10 解决

**Comment by chenfeng11111** [comment]
还是有问题，麻烦大佬再看看

https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/51077830/75bbc2c8-53b1-45c3-9b4a-761e772a4d70

**Comment by tangzx** [comment]
@chenfeng11111 试试这个 https://github.com/EmmyLua/IntelliJ-EmmyLua/actions/runs/7370807972

**Comment by chenfeng11111** [comment]
解决了，谢谢
