### ISSUE TITLE
使用.var导致编辑器卡死

### ISSUE THREAD

**Issue by chenfeng11111** [EmmyLua/IntelliJ-EmmyLua#572]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | idea ultimate Build #IU-233.11799.300, built on December 12, 2023
 EmmyLua version | 1.4.9
 OS                        | win11

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. 导入附件文件
2. 259行"behavior._hero._dirX2000110[behavior._behaviorOrder]" 使用.var
3. …

What happens?（出现什么问题？）
-------------
编辑器卡死

What were you expecting to happen?（期望？）
-----------------------------------------
功能正常使用

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…
[asd.txt](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/13702894/asd.txt)

**Comment by CppCXY** [comment]
已经上报了, 但是不知道什么时候会解决

**Comment by CppCXY** [comment]
这边建议用vscode, 或者没有调试需求, 可以使用intellij-sumnekolua插件

**Comment by tangzx** [comment]
好像不能复现 @chenfeng11111 
![20231222235624_rec_](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/3354360/991fc4bc-5cad-4d07-9fb4-ee95fd0bebea)

**Comment by CppCXY** [comment]
https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/40318218/59417b1d-7dae-4c6c-ac54-e22d18c184e4

是可以复现的

**Comment by chenfeng11111** [comment]
https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/51077830/da524841-960b-4b08-88b0-cc525b000331

**Comment by tangzx** [comment]
@chenfeng11111 尝试一下这个 https://github.com/EmmyLua/IntelliJ-EmmyLua/actions/runs/7340236452

**Comment by chenfeng11111** [comment]
可以正常运行了，非常感谢
