### ISSUE TITLE
Macros cannot be used in the working directory of the run configuration.

### ISSUE THREAD

**Issue by Autumn-one** [EmmyLua/IntelliJ-EmmyLua#575]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | [IntelliJ IDEA 2023.3.2]
 EmmyLua version | [1.4.11-IDEA231]
 OS                        | [Windows11]

I hope to set the working directory in the Lua run configuration template to always be relative to the directory of the running file. This way, I don't need to reset the run configuration for whatever Lua project I open. However, currently, the working directory in the Lua run configuration template does not support macros, so I cannot specify a dynamic path to meet my needs.

![image](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/26438145/fb4c429a-2229-41e3-86bc-567cef8736f4)
![image](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/26438145/857a8af9-f53a-4a2d-9d79-d8a7df873a86)

**Comment by CppCXY** [comment]
我的意思是我已经在群里回答过你了, 既然是这样就没必要发这里了, 因为发这里通常也是我回复你,那结果也是一模一样.
emmylua的lua application/Lua Remote是不会继续维护的前者是因为jb认为emmylua的attach debugger有毒所以把大部分功能砍掉了, 后者是因为他并非emmylua自己的调试器. 如果你只是想简单启动运行lua脚本, idea-emmylua并不是最好的选择, 我也推荐了vscode的lua-debug插件, 试试你就知道了.
