### ISSUE TITLE
Intellij IDEA 2024.1.1 中，在函数内输入可能会导致函数内的语法着色发生闪烁

### ISSUE THREAD

**Issue by Yoctillion** [EmmyLua/IntelliJ-EmmyLua#582]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         | 2024.1.1
 EmmyLua version | v1.4.13-IDEA241
 OS                        | Windows 10

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
在函数内输入时，若出现 Intellisence 提示变量名等情况，会导致此函数内的语法着色发生闪烁，如图
![GIF 24-05-06 20-59-13](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/11324635/fc3cfea8-e449-48fa-bca2-835b0d4a032a)
如果文件足够大（如 500 行），在函数内任意输入（包括空格、换行等）都会导致类似的现象
在函数外输入不会触发此问题

What were you expecting to happen?（期望？）
-----------------------------------------
参考 2023.3.6 下的表现
![GIF 24-05-06 21-04-17](https://github.com/EmmyLua/IntelliJ-EmmyLua/assets/11324635/6a602fe3-879a-4fd6-b0cf-c2b3cfe79ef5)

**Comment by CppCXY** [comment]
intellij版本要不行了,快试试vscode吧

**Comment by CppCXY** [comment]
可以试试这个插件: https://plugins.jetbrains.com/plugin/25076-emmylua2/edit

**Comment by Yoctillion** [comment]
> 可以试试这个插件: https://plugins.jetbrains.com/plugin/25076-emmylua2/edit

试了下，感觉速度确实快了点（但是这个问题还是会有）
一些自动补全的内容（补全 end、括号、自动缩进）和 live template 等看起来还有些问题，内存占用也变高了一些，期待后续更新吧

**Comment by Yoctillion** [comment]
官方已在 2024.2.2 中修复
