### ISSUE TITLE
EmmyLua/debugger/emmy/mac/x64/emmy_core.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

### ISSUE THREAD

**Issue by qeekblackstar** [EmmyLua/IntelliJ-EmmyLua#587]
Expect an Array: error loading module 'emmy_core' from file '/Users/xxx/Library/Application Support/JetBrains/Rider2022.3/plugins/EmmyLua/debugger/emmy/mac/x64/emmy_core.dylib':
	dlopen(/Users/xxx/Library/Application Support/JetBrains/Rider2022.3/plugins/EmmyLua/debugger/emmy/mac/x64/emmy_core.dylib, 0x0006): tried: '/Users/xxx/Library/Application Support/JetBrains/Rider2022.3/plugins/EmmyLua/debugger/emmy/mac/x64/emmy_core.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/xxx/Library/Application Support/JetBrains/Rider2022.3/plugins/EmmyLua/debugger/emmy/mac/x64/emmy_core.dylib' (no such file), '/Users/xxx/Library/Application Support/JetBrains/Rider2022.3/plugins/EmmyLua/debugger/emmy/mac/x64/emmy_core.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
stack traceback:
	[C]: in ?
	[C]: in upvalue '_require'
	[string "Packages/toy.strategy/Assets/Lua/toy.lua"]:100: in function 'require'
	[string "Packages/pm.iap.strategy/Assets/Lua/Strategy/flow_action.lua"]:2: in main chunk
UnityEngine.Debug:LogError (object)

**Comment by qeekblackstar** [comment]
Emmylua 1.3.8-IDEA223 not work in Mac M2 Apple Silicon

**Comment by CppCXY** [comment]
you can download from https://github.com/EmmyLua/EmmyLuaDebugger/releases
