### ISSUE TITLE
Release for IntelliJ 243?

### ISSUE THREAD

**Issue by BreakBB** [EmmyLua/IntelliJ-EmmyLua#593]
It looks like 02f8464075337dc4cad0c648bf50f15d9ac4fa21 hasn't been released yet to support the latest IntelliJ version (2024.3).

![image](https://github.com/user-attachments/assets/5a46ae3f-2586-485a-b81c-c45affc62c4f)

What's blocking this or was it just an oversight?

**Comment by dawnbreaks** [comment]
+1
