### ISSUE TITLE
Lua调用C#读取ByteBuffer时，没设断点的情况下，U3D整个卡住

### ISSUE THREAD

**Issue by Think-Jumper** [EmmyLua/IntelliJ-EmmyLua#65]
当Lua调用C#里面的函数，例如：
Lua: 
local data = buffer:ReadBufferForLua()
C#:
         public byte[] ReadBufferForLua()
        {
            byte[] bytes = reader.ReadBytes((int)(reader.BaseStream.Length));
            return bytes;
        }
就一定会卡在Lua这句代码这里。请作者看下是什么问题

**Comment by Think-Jumper** [comment]
When I use lua code call the C# function, such as like that：
Lua:
local data = buffer:ReadBufferForLua()
C#:
public byte[] ReadBufferForLua()
{
byte[] bytes = reader.ReadBytes((int)(reader.BaseStream.Length));
return bytes;
}
it will struck at the lua code up like tha, please help me to check if is there is a bug.

**Comment by mengchengbo** [comment]
我也遇到了同样的问题，现在有解决方案吗？

**Comment by tangzx** [comment]
暂时没有，等下一个大版本

**Comment by tangzx** [comment]
已解决
