### ISSUE TITLE
Error: LuaInject.dll could not be loaded into theprocess

### ISSUE THREAD

**Issue by woshihuo12** [EmmyLua/IntelliJ-EmmyLua#70]
附加进程调试出现此错误，防火墙杀毒软件都关闭了。

**Comment by tangzx** [comment]
看看是不是目标程序使用了管理员权限启动而IDEA没有

**Comment by woshihuo12** [comment]
这行报错上面还有一行报错，但idea显示乱码 也不知道报的是什么错误。 至于管理员 我unity没设管理员 我idea设了。

**Comment by tangzx** [comment]
再找找原因，这个问题一般都是杀毒软件或者权限问题导致的

**Comment by woshihuo12** [comment]
原因找到了不是权限的问题。而是我将plugin文件夹里的装着 tolua.dll的 x86_64 名字改为了 x64 就会出这种问题。
