### ISSUE TITLE
Multiple files debugging

### ISSUE THREAD

**Issue by slanska** [EmmyLua/IntelliJ-EmmyLua#74]
First, thanks a lot for a really nice tool. I just started using Lua (LuaJIT technically) for my pet project and found that editing features are just great. I have a question regarding debugging though. I am able to debug Entry File, as specified in debug configuration, but my other lua files in the same folder, referenced via 'require', are ignored. Breakpoints do not work, seems like debugger "does not see" other files in the project. Is it intentional or I am missing something?
(I am using CLion on Mac, if it matters). Thanks again!

**Comment by tangzx** [comment]
Does the  `source root` (s) are correct ? And, can you try it with IDEA ? I'm not familiar with CLion

**Comment by slanska** [comment]
Sorry for late reply, I just noticed your answer. Yes, I figured it out (after Google translation of plugin documentation in Chinese) that source folders have to be configured as Sources (Mark Directory As... | Source). Thanks.
