### ISSUE TITLE
lua.exe 找不到

### ISSUE THREAD

**Issue by spartawhy117** [EmmyLua/IntelliJ-EmmyLua#78]
windows下载官方编译好的exe压缩包，包括3个exe和一个dll到一个路径，然后设置了环境变量，调试和运行会报错Program [lua.exe] not found。但是在cmd中执行lua命令正常。
![image](https://user-images.githubusercontent.com/9450028/32701486-bed4ea5a-c811-11e7-9f17-95c6b2615999.png)

**Comment by tangzx** [comment]
设置完环境变量后，有没有重启idea?
实在不行你可以先填完整路径

**Comment by spartawhy117** [comment]
是给插件设置lua.exe的完整位置吗，需要在哪设置

**Comment by tangzx** [comment]
![image](https://user-images.githubusercontent.com/3354360/32712844-8a481f12-c881-11e7-95ca-ca07f9ad2b69.png)
运行配置 program

**Comment by spartawhy117** [comment]
ok了，谢谢解答。因为我看的较早的博客有的说不支持配置环境位置，结果现在支持了
