### ISSUE TITLE
Debug is invalid on linux

### ISSUE THREAD

**Issue by FayneWang** [EmmyLua/IntelliJ-EmmyLua#80]
linux环境下，创建好 lua项目好，编写一个lua脚本。执行“Debug...”菜单项，不能进行Deubg。提示如下：
Cannot run program "/home/wzz/.IntelliJIdea2017.2/config/plugins/EmmyLua/classes/debugger/windows/Arch.exe": error=13, Permission denied

**Comment by tangzx** [comment]
非windows要选择remote debugger(mobdebug)
