### ISSUE TITLE
infer type cause StackOverflowError

### ISSUE THREAD

**Issue by tangzx** [EmmyLua/IntelliJ-EmmyLua#81]
```lua
local function test()
    return test
end
```

**Comment by yuchting** [comment]
我不知道和我这个堆栈有关系没。

![6 mcx4dr8 kkydqx v 644e](https://user-images.githubusercontent.com/1817716/33066152-8023fc62-cee5-11e7-93c1-726bba4e74dd.png)

**Comment by tangzx** [comment]
像是
