### ISSUE TITLE
require 到局部(全局)变量之后，无法定位函数了

### ISSUE THREAD

**Issue by yuchting** [EmmyLua/IntelliJ-EmmyLua#85]
local Config = require("Config")
Config:foo()

鼠标放到 foo 上面，goto 定义（Ctrl+鼠标左键），无法跳转到 Config.lua 文件中的foo定位。

源码文件夹都已经设置好，跨文件的变量寻找是正常的。

**Comment by yuchting** [comment]
补充一下，一共三个文件：

![image](https://user-images.githubusercontent.com/1817716/33469258-b117dc30-d69c-11e7-9b0a-4bdadfd7efe0.png)

![image](https://user-images.githubusercontent.com/1817716/33469265-c6778b16-d69c-11e7-95cc-ce27ebae0e94.png)

![image](https://user-images.githubusercontent.com/1817716/33469275-dd6c6850-d69c-11e7-8a5c-e7551714f4fa.png)

**Comment by tangzx** [comment]
`TableConfig.lua`里加了`module("Common", ...)` 是什么用处？ 对于这种是做了特殊处理的，最好能不用它（官方也不推荐），然后在 `local TableConfig = class(...` 上加上 class 注解 `---@class TableConfig`，最后确认两点：

- [ ] `TableConfig.lua`文件最后有 `return TableConfig`
- [ ] Sources root 设置正确（从代码情况来看，应该是 `Common` 文件夹的父级目录为 Sources root）

建议多用注解系统发挥EmmyLua的最大优势，文档有说明 https://emmylua.github.io/index.html
