### ISSUE TITLE
希望@field能与@class分开，在另一个文件也能对某个class声明新的field

### ISSUE THREAD

**Issue by wy19910222** [EmmyLua/IntelliJ-EmmyLua#91]
![image](https://user-images.githubusercontent.com/12708341/34194047-beff65f8-e591-11e7-92fb-ab6048cecab4.png)
![image](https://user-images.githubusercontent.com/12708341/34194049-c2b626c8-e591-11e7-86ba-bfc63d335206.png)
比如我这调用了LuaClass.Class函数，函数内会把生成的table赋值给LuaClass[className]，但是推断不出来，所以我还得通过LuaClass.BaseManager = BaseManager再赋值一遍，才能让EmmyLua知道LuaClass里面有个BaseManager。
**所以希望第二遍的赋值只在注解之中，而不用被程序运行到。**

**Comment by tangzx** [comment]
---@field public <Class> field Type
