### ISSUE TITLE
Indexing never finishes - v 1.22

### ISSUE THREAD

**Issue by slanska** [EmmyLua/IntelliJ-EmmyLua#95]
First of all, thank you for the new version of your plugin. One thing I noticed is that after plugin update indexing never ends, and because of that a) CPU runs pretty high, b) intellisense is not available.

**Comment by tangzx** [comment]
@slanska try invalidate and restart idea via menu "File - Invalidate and restart", if doesn't work, please upload your idea log "help - show log in explorer"

**Comment by slanska** [comment]
'Invalidate and restart' did not help. I am attaching idea.log from today (note that I am using CLion, not IntelliJ IDEA, though it probably shouldn't matter).

[idea.log](https://github.com/EmmyLua/IntelliJ-EmmyLua/files/1617235/idea.log)

**Comment by tangzx** [comment]
It seems strange, there's no error about emmylua in the log. Any other infos?

**Comment by slanska** [comment]
Eventually indexing was completed. Not sure how long it took, though - I just left it running.
