### ISSUE TITLE
how can i mofify the lua head description

### ISSUE THREAD

**Issue by Rootjhon** [EmmyLua/IntelliJ-EmmyLua#97]
for now , that auto add like

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by {}.
--- DateTime: {}
---

======split=====

i wana modify it.

**Comment by tangzx** [comment]
Sorry, you can't modify the embedded file template.
But you can add your own templates via `File` -> `New` -> `Edit file template...`
![image](https://user-images.githubusercontent.com/3354360/35036212-987d0be6-fbae-11e7-8eef-1c465838a103.png)

**Comment by Rootjhon** [comment]
get it ,thinks.
